/*
 * ring.cpp — the 8-LED WS2812 ring around the encoder, as the pager's second
 * output channel.
 *
 * The screen says what happened. The ring says that something happened, from
 * across a room, without being read. That is the whole division of labour, and
 * it is why almost everything here is a *state* rather than a flash: while an
 * unread message exists the ring breathes in that message's colour, and it
 * keeps breathing until somebody acknowledges it.
 *
 *
 * RMT coexistence with the IR transmitter — the thing that had to be settled
 * ------------------------------------------------------------------------
 * ir.cpp already owns an RMT TX channel (rmtInit(PIN_IR_TX, RMT_TX_MODE,
 * RMT_MEM_NUM_BLOCKS_2, 1000000)), and WS2812 also wants one. The numbers, from
 * the SoC caps header the build actually compiles against
 * (framework-arduinoespressif32-libs/esp32s3/include/soc/esp32s3/include/soc/
 * soc_caps.h):
 *
 *   SOC_RMT_GROUPS                  1
 *   SOC_RMT_CHANNELS_PER_GROUP      8
 *   SOC_RMT_TX_CANDIDATES_PER_GROUP 4     <- only four of the eight can transmit
 *   SOC_RMT_MEM_WORDS_PER_CHANNEL   48    <- one "memory block" is 48 symbols
 *
 * A channel asking for N memory blocks takes its own block plus the blocks of
 * the N-1 TX channels after it, so IR's two blocks cost two of the four TX
 * candidates and leave two. That is what this file spends, and it means the
 * ESP32-S3's TX side is now fully committed: a third RMT TX consumer added
 * later will fail at rmtInit() rather than quietly steal a channel.
 *
 * The Arduino core's wrapper (cores/esp32/esp32-hal-rmt.c in arduino-esp32
 * 3.3.9) keys everything on the *pin*: rmtInit() allocates one rmt_obj_s per
 * pin, each with its own IDF channel handle from rmt_new_tx_channel(), its own
 * copy encoder, its own event group and its own mutex — RMT_MUTEX_LOCK() takes
 * busptr->g_rmt_objlocks, not a global. The only shared lock, g_rmt_block_lock,
 * is held across allocation and released before any transmission. So two pins
 * transmit concurrently with no interlock between them, and a ring refresh
 * cannot stall or corrupt a frame the IR channel is clocking out.
 *
 * FastLED was never a candidate, for the reason recorded in the reference
 * firmware for this same board (tembed-pager/firmware/platformio.ini): it
 * claims every RMT TX channel on the first show() and installs a non-shared RMT
 * interrupt handler, which on a board that also transmits IR is a collision by
 * construction.
 *
 * Adafruit NeoPixel was that reference's choice and it is the right one there —
 * but that firmware builds on espressif32@6.13.0 (arduino-esp32 2.x, IDF 4) and
 * this one builds on arduino-esp32 3.3.9 (IDF 5), and on IDF 5 NeoPixel 1.12.3
 * is no longer a driver at all. Its whole ESP32 path (esp.c, the HAS_ESP_IDF_5
 * branch) is:
 *
 *     rmtInit(pin, RMT_TX_MODE, RMT_MEM_NUM_BLOCKS_1, 10000000);
 *     ... pack numBytes*8 rmt_data_t on the stack ...
 *     rmtWrite(pin, led_data, numBytes * 8, RMT_WAIT_FOR_EVER);
 *
 * — the very core wrapper this file would call anyway. Adding the library would
 * buy nothing and cost three things: a blocking rmtWrite() that parks the loop
 * task for the length of the bit stream, a variable-length rmt_data_t array on
 * that task's stack (768 bytes here) rather than in .bss, and a second copy of
 * the pixel buffer. So the ring is driven through the same rmt* wrapper ir.cpp
 * uses, with rmtWriteAsync() instead — identical peripheral arrangement to the
 * proven reference, minus the blocking.
 *
 * Timings below are NeoPixel's, unchanged, because they are what is known to
 * work on this board's ring: a 10MHz channel, so one tick is 100ns.
 *
 *
 * Not blocking, and not glitching
 * -------------------------------
 * The 800kHz bit stream is generated by the peripheral, not the CPU: 192 bits
 * at 1.2us is about 230us of hardware transmission per frame, started by a
 * non-blocking rmtWriteAsync() and never waited on. loop() spends only the
 * encode — 192 iterations of two bitfield stores — and ring_poll() runs at most
 * once every RING_FRAME_MS, so the ring costs a bounded fraction of a
 * millisecond twenty-five times a second and cannot delay ir_poll().
 *
 * Two guards keep the stream itself intact:
 *
 *   - the symbol buffer is not touched while the peripheral owns it. A frame is
 *     encoded only after rmtTransmitCompleted() says the previous one is done;
 *     otherwise the frame is dropped and retried on the next pass.
 *   - a frame is only sent when the composed pixels differ from the last ones
 *     actually accepted, so a still ring — the common case — puts nothing on
 *     the wire at all.
 *
 * With one memory block the copy encoder's refill interrupt would fire every 24
 * symbols (30us); two blocks halve that to every 48 (60us), which is the margin
 * that WiFi and AsyncTCP interrupt latency is being padded against — the same
 * reasoning, and the same choice, as ir.cpp's two blocks. If two blocks cannot
 * be had the init falls back to one rather than leaving the ring dark, and says
 * which it got.
 *
 * A glitched WS2812 frame is a wrong colour for 40ms and self-corrects on the
 * next one. That asymmetry is the point of the arrangement above: the failure
 * that must not happen is a glitched IR blast, and IR is on its own channel,
 * with its own memory, its own mutex and its own interrupt, untouched by any of
 * this.
 *
 *
 * Brightness, gamma and night
 * ---------------------------
 * ring_level() is where a colour becomes a drive value, and the order of the
 * three operations is deliberate:
 *
 *   1. the channel is scaled by the effect's envelope, in perceptual space —
 *      this is what a breath or a comet tail means;
 *   2. the result is gamma-encoded through ring_gamma[], because a WS2812's
 *      output is roughly linear in its PWM value while the eye is not. Without
 *      it a breath is a snap to full followed by a plateau, and at the bottom
 *      of the ramp every colour collapses towards grey;
 *   3. only then is the global cap applied, linearly. That keeps "50%" meaning
 *      half the drive current — a power cap with a predictable effect — rather
 *      than a second gamma curve multiplied into the first.
 *
 * The cap is runtime-settable over HTTP because its value is provisional by
 * design; 50 is a starting point to be dialled in against the actual room, not
 * a measurement.
 *
 * Night silence is absolute: inside the window the ring does not light, not
 * even for an unread critical, which already breathes on the (dim) screen.
 * Boundaries come from clock_local_time() and therefore from whatever POSIX TZ
 * string SPIFFS holds — this file knows no city and no offset, and must not
 * learn one. When the clock has never been set the ring stays lit: a node that
 * has not reached NTP is usually a freshly booted or offline one, and a pager
 * that goes dark because it lost the time is broken in the direction that loses
 * messages.
 */

/* --- Geometry and rates --- */

#define RING_LEDS         8
#define RING_BITS         (RING_LEDS * 3 * 8)

/* 40Hz. Fast enough that a breath has no visible steps and a comet head moves
   smoothly, slow enough that the RMT channel is busy under 1% of the time. */
#define RING_FRAME_MS     25

/* WS2812 bit cells at 100ns per tick, from Adafruit NeoPixel's IDF 5 path. */
#define RING_T0H          4
#define RING_T0L          8
#define RING_T1H          8
#define RING_T1L          4

/* The reset that latches a frame is the line sitting low between writes, which
   rmtSetEOT(LOW) guarantees; at RING_FRAME_MS apart that gap is four orders of
   magnitude longer than the ~50us the part needs, so no reset symbol is sent. */

/* --- Effect durations --- */

#define RING_COMET_MS     640    /* one lap, 80ms a pixel */
#define RING_COMET_TAIL   3
#define RING_WIPE_MS      560    /* fill, then fade */
#define RING_WIPE_FADE_MS 160
#define RING_KNOB_HOLD_MS 400    /* the dot lingers this long after the last detent */
#define RING_BREATHE_MS   4000   /* info and warn */
#define RING_BREATHE_CRIT_MS 2000 /* matches the clock face's rule breathe */

/* The breath's floor, in envelope units before gamma. Zero would make the ring
   vanish at the bottom of every cycle, and "you have messages" must not blink
   out of existence — this is a faint ember rather than darkness. */
#define RING_BREATHE_MIN  80

/* --- Configuration --- */

#define RING_CFG_FILE     "/ring.json"
#define RING_CFG_TMP      "/ring.tmp"
/* Settings arrive on the web-server task; the flash write is deferred to
   loop(), the one task allowed to spend milliseconds. Same arrangement, and the
   same reason, as the notification store's snapshot. */
#define RING_CFG_DELAY_MS 1500

#define RING_BRIGHT_DEFAULT     50
#define RING_NIGHT_FROM_DEFAULT 0        /* 00:00 */
#define RING_NIGHT_TO_DEFAULT   (8 * 60) /* 08:00 */

#define RING_TEST_MAX_S   60
#define RING_TEST_DEF_S   8

/* --- Palette ---
 *
 * The three level colours are the RGB888 equivalents of the RGB565 the clock
 * face already uses (COL_INFO, COL_ACCENT, COL_CRIT), so that a message which
 * is amber on the screen is the same amber on the ring rather than a second
 * opinion about what "warn" looks like. Green belongs to acknowledgement only
 * and appears nowhere else in the UI. */

struct RingColor { uint8_t r, g, b; };

static const RingColor RING_C_INFO = { 41, 239, 173};  /* teal   <- COL_INFO   */
static const RingColor RING_C_WARN = {255, 162,  41};  /* amber  <- COL_ACCENT */
static const RingColor RING_C_CRIT = {230,  57,  41};  /* red    <- COL_CRIT   */
static const RingColor RING_C_ACK  = { 60, 220,  80};  /* green, acknowledge   */
static const RingColor RING_C_OFF  = {  0,   0,   0};

static const RingColor &ring_level_color(uint8_t level) {
    switch (level) {
        case NOTIFY_CRIT: return RING_C_CRIT;
        case NOTIFY_WARN: return RING_C_WARN;
        default:          return RING_C_INFO;
    }
}

/* pow(i / 255, 2.6) * 255, rounded. 2.6 is the exponent Adafruit's LED work
   settled on for WS2812 parts and it is what makes a linear envelope look
   linear. 256 bytes of flash. */
static const uint8_t ring_gamma[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   2,   2,   2,   2,   2,   2,   2,   2,   3,   3,   3,   3,
      3,   3,   4,   4,   4,   4,   5,   5,   5,   5,   5,   6,   6,   6,   6,   7,
      7,   7,   8,   8,   8,   9,   9,   9,  10,  10,  10,  11,  11,  11,  12,  12,
     13,  13,  13,  14,  14,  15,  15,  16,  16,  17,  17,  18,  18,  19,  19,  20,
     20,  21,  21,  22,  22,  23,  24,  24,  25,  25,  26,  27,  27,  28,  29,  29,
     30,  31,  31,  32,  33,  34,  34,  35,  36,  37,  38,  38,  39,  40,  41,  42,
     42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
     58,  59,  60,  61,  62,  63,  64,  65,  66,  68,  69,  70,  71,  72,  73,  75,
     76,  77,  78,  80,  81,  82,  84,  85,  86,  88,  89,  90,  92,  93,  94,  96,
     97,  99, 100, 102, 103, 105, 106, 108, 109, 111, 112, 114, 115, 117, 119, 120,
    122, 124, 125, 127, 129, 130, 132, 134, 136, 137, 139, 141, 143, 145, 146, 148,
    150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
    182, 184, 186, 188, 191, 193, 195, 197, 199, 202, 204, 206, 209, 211, 213, 215,
    218, 220, 223, 225, 227, 230, 232, 235, 237, 240, 242, 245, 247, 250, 252, 255,
};

/* --- State --- */

static bool ring_ready = false;
static uint8_t ring_blocks = 0;          /* memory blocks the channel actually got */

/* Everything the endpoints can write is volatile: those handlers run on the
   web-server task while ring_poll() reads the same words on the loop task. All
   of them are single aligned scalars, so the worst a collision can cost is one
   frame composed from a half-applied setting — 25ms of the old brightness. */
static volatile bool ring_enabled = true;
static volatile uint8_t ring_brightness = RING_BRIGHT_DEFAULT;   /* percent, 0..100 */
static volatile uint16_t ring_night_from = RING_NIGHT_FROM_DEFAULT;
static volatile uint16_t ring_night_to = RING_NIGHT_TO_DEFAULT;

static volatile bool ring_cfg_dirty = false;
static volatile unsigned long ring_cfg_save_at = 0;

/* One-shot overlays. Only one can run at a time: they are all half a second
   long and stacking them would say nothing a single one does not. */
enum { RING_FX_NONE = 0, RING_FX_COMET, RING_FX_WIPE };
static volatile uint8_t ring_fx = RING_FX_NONE;
static volatile uint8_t ring_fx_level = NOTIFY_INFO;
static volatile unsigned long ring_fx_start = 0;

/* Knob tracking. ui_poll() hands over each detent; the position is free-running
   modulo the ring so that turning past the last pixel arrives at the first,
   exactly as the menu wraps rather than clamps. */
static int ring_knob_pos = 0;
static unsigned long ring_knob_at = 0;

/* Progress, 0..100, or -1 for "no job". Fed from loop(); nothing in ir.cpp
   knows this exists. */
static int ring_progress_pct = -1;

/* Test pattern, so colours can be judged without inventing a notification. */
enum { RING_TEST_NONE = 0, RING_TEST_BREATHE, RING_TEST_LEVELS };
static volatile uint8_t ring_test = RING_TEST_NONE;
static volatile uint8_t ring_test_level = NOTIFY_INFO;
static volatile unsigned long ring_test_until = 0;

/* GRB bytes as they go on the wire, and the last set the peripheral accepted. */
static uint8_t ring_frame[RING_LEDS][3];
static uint8_t ring_sent[RING_LEDS][3];
static bool ring_sent_valid = false;

/* 768 bytes, in .bss rather than on the loop task's stack. */
static rmt_data_t ring_sym[RING_BITS];

/* --- Colour maths --- */

/* One channel of one pixel: perceptual scale, gamma encode, then the linear
   cap. See the header comment for why that order and not another. */
static uint8_t ring_level(uint8_t channel, uint8_t envelope) {
    uint16_t perceptual = ((uint16_t)channel * envelope) / 255;
    return (uint8_t)(((uint16_t)ring_gamma[perceptual] * ring_brightness) / 100);
}

static void ring_put(uint8_t frame[RING_LEDS][3], int i, const RingColor &c,
                     uint8_t envelope) {
    if (i < 0 || i >= RING_LEDS) return;
    frame[i][0] = ring_level(c.g, envelope);   /* WS2812 takes GRB on the wire */
    frame[i][1] = ring_level(c.r, envelope);
    frame[i][2] = ring_level(c.b, envelope);
}

/* 0 -> 255 -> 0 across cycle_ms, phased on the wall clock rather than on the
   effect's start, so that a ring which changes colour mid-breath continues the
   breath instead of restarting it. */
static uint8_t ring_triangle(unsigned long now, unsigned long cycle_ms) {
    unsigned long pos = now % cycle_ms;
    unsigned long half = cycle_ms / 2;
    unsigned long up = (pos < half) ? pos : (cycle_ms - pos);
    return (uint8_t)(up * 255 / half);
}

/* --- Night window --- */

/* from == to is an empty window, which is how the silence is turned off without
   a fourth setting. from > to wraps midnight, which is the shape most people
   actually want (22:00 to 07:00). */
static bool ring_night_now() {
    if (ring_night_from == ring_night_to) return false;
    struct tm t;
    if (!clock_local_time(t)) return false;   /* time unknown -> stay lit */
    int m = t.tm_hour * 60 + t.tm_min;
    if (ring_night_from < ring_night_to)
        return m >= ring_night_from && m < ring_night_to;
    return m >= ring_night_from || m < ring_night_to;
}

/* --- Effect triggers (called from loop(), ui.h and the endpoints) --- */

static void ring_fire(uint8_t fx, uint8_t level) {
    ring_fx = fx;
    ring_fx_level = level;
    ring_fx_start = millis();
}

static void ring_knob(int steps) {
    if (steps == 0) return;
    ring_knob_pos = (ring_knob_pos + steps) % RING_LEDS;
    if (ring_knob_pos < 0) ring_knob_pos += RING_LEDS;
    ring_knob_at = millis();
}

static void ring_progress_set(int pct) {
    if (pct < 0) pct = 0;
    if (pct > 100) pct = 100;
    ring_progress_pct = pct;
}

static void ring_progress_clear() {
    ring_progress_pct = -1;
}

/* --- Frame composition ---
 *
 * Priority, highest first:
 *
 *   knob      a hand is on the control; that hand's feedback outranks anything
 *             the ring was saying on its own
 *   test      an operator asked for this pattern explicitly
 *   one-shot  arrival or acknowledgement, half a second each
 *   progress  a job is running and its position is the information
 *   breathe   unread messages exist
 *   dark      nothing to say
 *
 * `now` is passed in rather than read here: ring_poll() retires expired effects
 * against one timestamp, and composing against a second one taken microseconds
 * later would let an effect be drawn one millisecond past its own end — which
 * for the wipe's fade is the difference between reaching zero and wrapping past
 * it to full brightness.
 */
static void ring_compose(uint8_t frame[RING_LEDS][3], unsigned long now) {
    memset(frame, 0, RING_LEDS * 3);

    /* Disabled, or inside the night window: composed dark and pushed once, so
       the ring goes out rather than freezing on its last frame. */
    if (!ring_enabled || ring_night_now()) return;

    if (now - ring_knob_at < RING_KNOB_HOLD_MS) {
        ring_put(frame, ring_knob_pos, RING_C_WARN, 255);
        return;
    }

    if (ring_test != RING_TEST_NONE) {
        if (ring_test == RING_TEST_LEVELS) {
            /* Two pixels each with a gap between, so the three can be compared
               side by side at whatever brightness is currently set. */
            ring_put(frame, 0, RING_C_INFO, 255);
            ring_put(frame, 1, RING_C_INFO, 255);
            ring_put(frame, 3, RING_C_WARN, 255);
            ring_put(frame, 4, RING_C_WARN, 255);
            ring_put(frame, 6, RING_C_CRIT, 255);
            ring_put(frame, 7, RING_C_CRIT, 255);
        } else {
            uint8_t env = RING_BREATHE_MIN +
                          (uint8_t)((255 - RING_BREATHE_MIN) *
                                    ring_triangle(now, RING_BREATHE_MS) / 255);
            for (int i = 0; i < RING_LEDS; i++)
                ring_put(frame, i, ring_level_color(ring_test_level), env);
        }
        return;
    }

    if (ring_fx == RING_FX_COMET) {
        unsigned long el = now - ring_fx_start;
        int head = (int)(el * RING_LEDS / RING_COMET_MS);
        const RingColor &c = ring_level_color(ring_fx_level);
        /* Head at full, then a tail that falls away behind it. The tail is what
           makes the lap read as a direction rather than a chase of blinks. */
        static const uint8_t tail[RING_COMET_TAIL + 1] = {255, 110, 45, 15};
        for (int t = 0; t <= RING_COMET_TAIL; t++) {
            int p = head - t;
            if (p < 0) p += RING_LEDS;
            ring_put(frame, p % RING_LEDS, c, tail[t]);
        }
        return;
    }

    if (ring_fx == RING_FX_WIPE) {
        unsigned long el = now - ring_fx_start;
        unsigned long fill_ms = RING_WIPE_MS - RING_WIPE_FADE_MS;
        int lit = (int)(el * RING_LEDS / fill_ms);
        if (lit > RING_LEDS) lit = RING_LEDS;
        uint8_t env = 255;
        if (el > fill_ms) {
            unsigned long f = el - fill_ms;
            if (f > RING_WIPE_FADE_MS) f = RING_WIPE_FADE_MS;
            env = (uint8_t)(255 - (f * 255 / RING_WIPE_FADE_MS));
        }
        for (int i = 0; i < lit; i++) ring_put(frame, i, RING_C_ACK, env);
        return;
    }

    if (ring_progress_pct >= 0) {
        /* The lit arc is the progress. The pixel at the boundary carries the
           fraction, so eight LEDs read as rather more than eight steps, and it
           never goes fully dark while a job is running — a blast that has not
           yet sent its first frame is still a blast, and an unlit ring would
           say the opposite. */
        int scaled = ring_progress_pct * RING_LEDS;         /* 0..800 */
        int whole = scaled / 100;
        int part = scaled % 100;
        for (int i = 0; i < whole && i < RING_LEDS; i++)
            ring_put(frame, i, RING_C_WARN, 255);
        if (whole < RING_LEDS) {
            int env = part * 255 / 100;
            if (env < 40) env = 40;
            ring_put(frame, whole, RING_C_WARN, (uint8_t)env);
        }
        return;
    }

    uint8_t top;
    if (notify_top_unread_level(top)) {
        unsigned long cycle = (top == NOTIFY_CRIT) ? RING_BREATHE_CRIT_MS
                                                   : RING_BREATHE_MS;
        uint8_t env = RING_BREATHE_MIN +
                      (uint8_t)((255 - RING_BREATHE_MIN) *
                                ring_triangle(now, cycle) / 255);
        for (int i = 0; i < RING_LEDS; i++)
            ring_put(frame, i, ring_level_color(top), env);
    }
}

/* --- Transmission --- */

static void ring_encode() {
    const uint8_t *bytes = &ring_frame[0][0];
    int s = 0;
    for (int b = 0; b < RING_LEDS * 3; b++) {
        uint8_t v = bytes[b];
        for (int bit = 7; bit >= 0; bit--) {
            bool one = (v >> bit) & 1;
            ring_sym[s].level0 = 1;
            ring_sym[s].duration0 = one ? RING_T1H : RING_T0H;
            ring_sym[s].level1 = 0;
            ring_sym[s].duration1 = one ? RING_T1L : RING_T0L;
            s++;
        }
    }
}

/* --- Persistence --- */

static void ring_cfg_save() {
    JsonDocument doc;
    doc["on"] = ring_enabled;
    doc["b"] = ring_brightness;
    doc["nf"] = ring_night_from;
    doc["nt"] = ring_night_to;
    String out;
    serializeJson(doc, out);
    write_spiffs_file_atomic(RING_CFG_FILE, RING_CFG_TMP, out);
}

static void ring_cfg_mark_dirty() {
    unsigned long at = millis() + RING_CFG_DELAY_MS;
    if (!ring_cfg_dirty || (long)(at - ring_cfg_save_at) < 0) ring_cfg_save_at = at;
    ring_cfg_dirty = true;
}

/* A file that is missing, truncated or nonsense leaves the compiled defaults
   standing: the ring is a notification channel, and the worst outcome of a bad
   config read is that it silently stops being one. */
static void ring_cfg_load() {
    String raw = read_spiffs_file(RING_CFG_FILE);
    if (raw.length() == 0) return;
    JsonDocument doc;
    if (deserializeJson(doc, raw) != DeserializationError::Ok) return;
    if (doc["on"].is<bool>()) ring_enabled = doc["on"].as<bool>();
    if (doc["b"].is<int>()) {
        int b = doc["b"].as<int>();
        if (b >= 0 && b <= 100) ring_brightness = (uint8_t)b;
    }
    if (doc["nf"].is<int>() && doc["nt"].is<int>()) {
        int f = doc["nf"].as<int>(), t = doc["nt"].as<int>();
        if (f >= 0 && f < 1440 && t >= 0 && t < 1440) {
            ring_night_from = (uint16_t)f;
            ring_night_to = (uint16_t)t;
        }
    }
}

/* --- Poll --- */

static const char *ring_effect_name() {
    if (!ring_ready) return "unavailable";
    if (!ring_enabled) return "disabled";
    if (ring_night_now()) return "night";
    if (millis() - ring_knob_at < RING_KNOB_HOLD_MS) return "knob";
    if (ring_test == RING_TEST_LEVELS) return "test-levels";
    if (ring_test == RING_TEST_BREATHE) return "test-breathe";
    if (ring_fx == RING_FX_COMET) return "comet";
    if (ring_fx == RING_FX_WIPE) return "wipe";
    if (ring_progress_pct >= 0) return "progress";
    uint8_t top;
    if (notify_top_unread_level(top)) return "breathe";
    return "idle";
}

/* Called every loop() pass; does real work RING_FRAME_MS apart at most. */
static void ring_poll() {
    if (!ring_ready) return;

    unsigned long now = millis();
    static unsigned long last_frame = 0;
    if (now - last_frame < RING_FRAME_MS) return;
    last_frame = now;

    if (ring_cfg_dirty && (long)(now - ring_cfg_save_at) >= 0) {
        ring_cfg_dirty = false;
        ring_cfg_save();
    }

    /* Arrivals and acknowledgements are consumed whatever the ring is doing —
       including while it is disabled or silenced — so that a night's worth of
       them cannot queue up and all fire at eight in the morning. Both flags are
       taken every pass and the arrival wins the frame; leaving the other one
       standing would show it a moment later, on top of whatever came next. */
    uint8_t level;
    bool acked = notify_take_ring_ack();
    if (notify_take_ring_arrival(&level)) ring_fire(RING_FX_COMET, level);
    else if (acked) ring_fire(RING_FX_WIPE, NOTIFY_INFO);

    if (ring_fx == RING_FX_COMET && now - ring_fx_start >= RING_COMET_MS)
        ring_fx = RING_FX_NONE;
    if (ring_fx == RING_FX_WIPE && now - ring_fx_start >= RING_WIPE_MS)
        ring_fx = RING_FX_NONE;
    if (ring_test != RING_TEST_NONE && (long)(now - ring_test_until) >= 0)
        ring_test = RING_TEST_NONE;

    uint8_t want[RING_LEDS][3];
    ring_compose(want, now);

    if (ring_sent_valid && memcmp(want, ring_sent, sizeof(want)) == 0) return;

    /* The peripheral reads ring_sym asynchronously after rmtWriteAsync(), so
       the buffer must not be rewritten until it says it is finished. At 230us
       of transmission against a 25ms frame this never fires in practice; it is
       here because "never in practice" is not the same as "never". */
    if (!rmtTransmitCompleted(PIN_WS2812)) return;

    memcpy(ring_frame, want, sizeof(ring_frame));
    ring_encode();
    if (rmtWriteAsync(PIN_WS2812, ring_sym, RING_BITS)) {
        memcpy(ring_sent, want, sizeof(ring_sent));
        ring_sent_valid = true;
    }
}

/* --- Endpoints --- */

static const SkillEndpoint ring_endpoints[] = {
    {"GET",  "/ring",      "Ring state and settings: brightness, night window, current effect"},
    {"POST", "/ring",      "Set {enabled, brightness, night_from, night_to} — any subset"},
    {"POST", "/ring/test", "Show a pattern {effect, level, seconds} without queueing a message"},
    {NULL, NULL, NULL}
};

static const char *ring_describe() {
    return "## Skill: ring\n\n"
           "The 8-LED WS2812 ring around the encoder (GPIO14), driven by the\n"
           "RMT peripheral on its own TX channel. It is the pager's second\n"
           "output: the screen says what happened, the ring says that something\n"
           "happened, from across a room.\n\n"
           "### Endpoints\n\n"
           "| Method | Path | Description |\n"
           "|--------|------|-------------|\n"
           "| GET | /ring | `{\"enabled\":true,\"brightness\":50,\"night_from\":\"00:00\",\"night_to\":\"08:00\",\"night_now\":false,\"effect\":\"breathe\",\"level\":\"warn\",\"unread\":2}` |\n"
           "| POST | /ring | `{\"enabled\":true,\"brightness\":35,\"night_from\":\"23:30\",\"night_to\":\"07:00\"}` — every field optional |\n"
           "| POST | /ring/test | `{\"effect\":\"levels\"\\|\"breathe\"\\|\"comet\"\\|\"wipe\"\\|\"off\",\"level\":\"warn\",\"seconds\":8}` |\n\n"
           "A POST that names a setting it cannot parse changes nothing at all,\n"
           "rather than applying the fields it understood. Window boundaries\n"
           "take `\"HH:MM\"` with two digits each, or minutes past midnight.\n\n"
           "### What it shows\n\n"
           "While any message is unread the ring **breathes** in the colour of\n"
           "the most severe one — teal for info, amber for warn, red for crit,\n"
           "the same three the screen uses — and it keeps breathing until they\n"
           "are acknowledged. That is a state, not a flash: it is what tells you\n"
           "there is something waiting when you are not looking at the panel.\n\n"
           "On top of that: a comet lap when a message arrives, in that\n"
           "message's colour; a green wipe when one is acknowledged; an amber\n"
           "dot that follows the knob while you turn it; and, while a long job\n"
           "runs, a lit arc that is the job's progress — an IR blast drives this\n"
           "without knowing the ring exists.\n\n"
           "### Brightness\n\n"
           "`brightness` is a percentage, 0 to 100, applied to every pixel as a\n"
           "linear cap on drive current. It defaults to 50 and is meant to be\n"
           "dialled in live against the actual room rather than guessed at; the\n"
           "value survives a reboot.\n\n"
           "Colours are gamma-corrected (2.6) before the cap. Without that a\n"
           "breath looks like a snap to full followed by a plateau, and at the\n"
           "bottom of the ramp teal and amber both turn to grey.\n\n"
           "### Night silence\n\n"
           "Between `night_from` and `night_to` the ring does not light at all —\n"
           "including for a critical, which already breathes on the screen, and\n"
           "including a test pattern, which reports `suppressed` rather than\n"
           "lighting. Times are local, taken from the POSIX TZ string in\n"
           "`POST /clock/tz`; this skill knows no city and no offset. Set the\n"
           "two boundaries equal to switch the silence off. A window whose start\n"
           "is later than its end wraps midnight, so `23:30`-`07:00` is the\n"
           "night you would expect.\n\n"
           "If the clock has never been set the ring stays lit: a node that has\n"
           "not reached NTP is usually a freshly booted one, and going dark\n"
           "because the time is unknown fails in the direction that loses\n"
           "messages.\n\n"
           "### Example\n\n"
           "```\n"
           "curl -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' \\\n"
           "  -d '{\"brightness\":35,\"night_from\":\"23:30\",\"night_to\":\"07:00\"}' \\\n"
           "  http://seed.local:8080/ring\n"
           "curl -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' \\\n"
           "  -d '{\"effect\":\"levels\",\"seconds\":15}' http://seed.local:8080/ring/test\n"
           "```\n";
}

static void ring_time_str(uint16_t mins, char *out, size_t n) {
    snprintf(out, n, "%02u:%02u", (unsigned)(mins / 60), (unsigned)(mins % 60));
}

/* Accepts "HH:MM" or a plain minute count, because one of those is what a
   person types and the other is what a script already has.
 *
 * Parsed by hand rather than with sscanf(): nothing else in this firmware calls
 * the scanf family, and linking it in for five characters costs roughly 25KB of
 * flash. Five characters exactly — "8:30" is rejected rather than guessed at,
 * which also makes the format that comes back out the only one accepted. */
static bool ring_parse_time(JsonVariantConst v, uint16_t &out) {
    if (v.is<const char *>()) {
        const char *s = v.as<const char *>();
        if (!s || strlen(s) != 5 || s[2] != ':') return false;
        for (int i = 0; i < 5; i++) {
            if (i == 2) continue;
            if (s[i] < '0' || s[i] > '9') return false;
        }
        int h = (s[0] - '0') * 10 + (s[1] - '0');
        int m = (s[3] - '0') * 10 + (s[4] - '0');
        if (h > 23 || m > 59) return false;
        out = (uint16_t)(h * 60 + m);
        return true;
    }
    if (v.is<int>()) {
        int m = v.as<int>();
        if (m < 0 || m > 1439) return false;
        out = (uint16_t)m;
        return true;
    }
    return false;
}

static void ring_state_json(JsonDocument &doc) {
    char from[8], to[8];
    ring_time_str(ring_night_from, from, sizeof(from));
    ring_time_str(ring_night_to, to, sizeof(to));

    doc["ready"] = ring_ready;
    doc["leds"] = RING_LEDS;
    doc["pin"] = PIN_WS2812;
    doc["mem_blocks"] = ring_blocks;
    doc["enabled"] = ring_enabled;
    doc["brightness"] = ring_brightness;
    doc["night_from"] = from;
    doc["night_to"] = to;
    doc["night_now"] = ring_night_now();
    doc["effect"] = ring_effect_name();
    doc["unread"] = notify_unread_count();
    uint8_t top;
    if (notify_top_unread_level(top)) doc["level"] = notify_level_name(top);
    if (ring_progress_pct >= 0) doc["progress"] = ring_progress_pct;
}

/* notify_take_body() and notify_send_error() are notify.cpp's, reused rather
   than copied: the skills are #included into one translation unit, and a third
   identical pair of four-line JSON helpers would be three too many. Every route
   below is registered with AsyncURIMatcher::exact(), without which /ring would
   also answer /ring/test and every test request would be read as a settings
   change with no body. */
static void ring_register_routes(AsyncWebServer &server) {

    server.on(AsyncURIMatcher::exact("/ring"), HTTP_GET, [](AsyncWebServerRequest *req) {
        if (!require_auth(req)) return;
        JsonDocument doc;
        ring_state_json(doc);
        String out;
        serializeJson(doc, out);
        req->send(200, "application/json", out);
    });

    /* Bodies are collected by handle_body_collect() into _tempObject and belong
       to the handler from then on, including on the unauthenticated path —
       hence check_auth() rather than require_auth()'s early return. */
    server.on(AsyncURIMatcher::exact("/ring"), HTTP_POST, [](AsyncWebServerRequest *req) {
        char *body = notify_take_body(req);
        if (!check_auth(req)) {
            free(body);
            notify_send_error(req, 401, "Authorization: Bearer <token> required");
            return;
        }
        if (!body) {
            notify_send_error(req, 400, "body must be JSON");
            return;
        }
        JsonDocument input;
        DeserializationError err = deserializeJson(input, body);
        free(body);
        if (err != DeserializationError::Ok) {
            notify_send_error(req, 400, "invalid JSON");
            return;
        }

        /* Parsed into locals first: a body that names four settings and gets
           one of them wrong applies none of them, rather than half. */
        bool enabled = ring_enabled;
        uint8_t brightness = ring_brightness;
        uint16_t from = ring_night_from, to = ring_night_to;

        if (input["enabled"].is<bool>()) enabled = input["enabled"].as<bool>();
        else if (!input["enabled"].isNull()) {
            notify_send_error(req, 400, "enabled must be true or false");
            return;
        }
        if (input["brightness"].is<int>()) {
            int b = input["brightness"].as<int>();
            if (b < 0 || b > 100) {
                notify_send_error(req, 400, "brightness must be 0..100 (percent)");
                return;
            }
            brightness = (uint8_t)b;
        } else if (!input["brightness"].isNull()) {
            notify_send_error(req, 400, "brightness must be a number, 0..100");
            return;
        }
        if (!input["night_from"].isNull() &&
            !ring_parse_time(input["night_from"], from)) {
            notify_send_error(req, 400, "night_from must be \"HH:MM\" or minutes past midnight");
            return;
        }
        if (!input["night_to"].isNull() &&
            !ring_parse_time(input["night_to"], to)) {
            notify_send_error(req, 400, "night_to must be \"HH:MM\" or minutes past midnight");
            return;
        }

        bool changed = (enabled != ring_enabled) || (brightness != ring_brightness) ||
                       (from != ring_night_from) || (to != ring_night_to);
        ring_enabled = enabled;
        ring_brightness = brightness;
        ring_night_from = from;
        ring_night_to = to;
        if (changed) {
            ring_cfg_mark_dirty();
            event_add("ring: %s, brightness %u%%, quiet %02u:%02u-%02u:%02u",
                      ring_enabled ? "on" : "off", (unsigned)ring_brightness,
                      (unsigned)(ring_night_from / 60), (unsigned)(ring_night_from % 60),
                      (unsigned)(ring_night_to / 60), (unsigned)(ring_night_to % 60));
        }

        JsonDocument doc;
        doc["ok"] = true;
        ring_state_json(doc);
        String out;
        serializeJson(doc, out);
        req->send(200, "application/json", out);
    }, NULL, handle_body_collect);

    server.on(AsyncURIMatcher::exact("/ring/test"), HTTP_POST, [](AsyncWebServerRequest *req) {
        char *body = notify_take_body(req);
        if (!check_auth(req)) {
            free(body);
            notify_send_error(req, 401, "Authorization: Bearer <token> required");
            return;
        }
        if (!body) {
            notify_send_error(req, 400, "body must be JSON with an effect");
            return;
        }
        JsonDocument input;
        DeserializationError err = deserializeJson(input, body);
        free(body);
        if (err != DeserializationError::Ok) {
            notify_send_error(req, 400, "invalid JSON");
            return;
        }

        const char *effect = input["effect"] | "levels";
        uint8_t level = NOTIFY_INFO;
        if (input["level"].is<const char *>() &&
            !notify_level_parse(input["level"].as<const char *>(), level)) {
            notify_send_error(req, 400, "level must be info, warn or crit");
            return;
        }
        int seconds = input["seconds"] | RING_TEST_DEF_S;
        if (seconds < 1 || seconds > RING_TEST_MAX_S) {
            notify_send_error(req, 400, "seconds must be 1..60");
            return;
        }

        if (strcmp(effect, "off") == 0) {
            ring_test = RING_TEST_NONE;
            ring_fx = RING_FX_NONE;
        } else if (strcmp(effect, "levels") == 0) {
            ring_test = RING_TEST_LEVELS;
            ring_test_until = millis() + (unsigned long)seconds * 1000UL;
        } else if (strcmp(effect, "breathe") == 0) {
            ring_test = RING_TEST_BREATHE;
            ring_test_level = level;
            ring_test_until = millis() + (unsigned long)seconds * 1000UL;
        } else if (strcmp(effect, "comet") == 0) {
            ring_test = RING_TEST_NONE;
            ring_fire(RING_FX_COMET, level);
        } else if (strcmp(effect, "wipe") == 0) {
            ring_test = RING_TEST_NONE;
            ring_fire(RING_FX_WIPE, NOTIFY_INFO);
        } else {
            notify_send_error(req, 400,
                              "effect must be levels, breathe, comet, wipe or off");
            return;
        }

        JsonDocument doc;
        doc["ok"] = true;
        doc["effect"] = effect;
        /* Said out loud rather than left as a mystery: the night window
           silences a test too, and the way out is the same API. */
        bool suppressed = !ring_ready || !ring_enabled || ring_night_now();
        doc["suppressed"] = suppressed;
        if (suppressed) {
            doc["reason"] = !ring_ready ? "ring unavailable"
                          : !ring_enabled ? "ring disabled"
                          : "inside the night window";
        }
        ring_state_json(doc);
        String out;
        serializeJson(doc, out);
        req->send(200, "application/json", out);
    }, NULL, handle_body_collect);
}

static const Skill ring_skill = {
    .name = "ring",
    .version = "0.1.0",
    .describe = ring_describe,
    .endpoints = ring_endpoints,
    .register_routes = ring_register_routes
};

/* Runs after skill_ir_init(), and the order is load-bearing: IR asks for two of
   the four TX memory blocks and must get them, so it allocates first and the
   ring takes what is left. Both channels are held for the life of the boot. */
static void skill_ring_init() {
    ring_cfg_load();

    /* Backdated so the very first frames are not read as "the knob was just
       turned". Unsigned wraparound makes this correct even when init runs
       before millis() has reached RING_KNOB_HOLD_MS. */
    ring_knob_at = millis() - RING_KNOB_HOLD_MS;

    /* 10MHz, so one duration tick is 100ns and the WS2812 bit cells above are
       whole numbers. Two memory blocks for interrupt-latency headroom, falling
       back to one rather than leaving the ring dark. */
    ring_blocks = 2;
    ring_ready = rmtInit(PIN_WS2812, RMT_TX_MODE, RMT_MEM_NUM_BLOCKS_2, 10000000);
    if (!ring_ready) {
        ring_blocks = 1;
        ring_ready = rmtInit(PIN_WS2812, RMT_TX_MODE, RMT_MEM_NUM_BLOCKS_1, 10000000);
    }
    if (!ring_ready) {
        ring_blocks = 0;
        event_add("ring: RMT init failed on pin %d", PIN_WS2812);
    } else {
        /* Idle low between frames: that gap is the WS2812 latch, and a line
           left high would be a permanent "reset never happened". */
        rmtSetEOT(PIN_WS2812, LOW);
        if (ring_blocks == 1)
            event_add("ring: only one RMT memory block available");
        /* The ring's state at reset is undefined, so the first frame is pushed
           unconditionally — ring_sent_valid is false and ring_poll() composes
           darkness on its first pass. */
    }

    skill_register(&ring_skill);
}
