#!/usr/bin/env bash
#
# Host-side regression test for the WAV header parser in src/skills/sound.cpp.
#
# Why this exists: a crafted chunk size could make the parser's chunk walk stop
# advancing, spinning forever on whichever task called it — the AsyncTCP task
# for an upload, which takes the entire HTTP interface down with it. That class
# of bug is invisible to a build and expensive to find on hardware, and it is
# exactly the kind a host test catches in a second.
#
# The parser is sliced straight out of sound.cpp between its `host-test:begin`
# and `host-test:end` markers, so this runs against the shipping code rather
# than a copy that could drift away from it. Nothing else from the firmware is
# needed: the parser touches only memcmp and two little-endian readers.
#
# Usage: tools/test_wav_parse.sh          (skips the exhaustive sweep)
#        tools/test_wav_parse.sh --full   (adds the 2^32 sweep, ~10s)

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/sound.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

# Slice the marked regions out of the firmware source, in order.
slice() {
    awk -v tag="$1" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$src"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_wav_parse.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

/* The one firmware constant the sliced code needs; grepped from sound.cpp
   below so it cannot drift from the shipping value. */
PRELUDE
    grep -E '^#define SND_DATA_MAX' "$src"
    echo
    slice rates
    echo
    slice wav
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

/* Build a WAV header. `data_size` is written into the data chunk verbatim so a
   test can lie about it. An `extra_id`/`extra_size` chunk is inserted before
   fmt when extra_id is non-NULL — that is the position an attacker controls
   without tripping either of the parser's early returns. */
static size_t build(uint8_t *b, const char *extra_id, uint32_t extra_size,
                    uint16_t format, uint16_t channels, uint32_t rate,
                    uint16_t bits, uint32_t data_size, int with_data) {
    size_t at = 0;
    memcpy(b, "RIFF", 4); at += 4;
    b[at++] = 0; b[at++] = 0; b[at++] = 0; b[at++] = 0;   /* riff size, unread */
    memcpy(b + at, "WAVE", 4); at += 4;

    if (extra_id) {
        memcpy(b + at, extra_id, 4); at += 4;
        b[at++] = (uint8_t)(extra_size); b[at++] = (uint8_t)(extra_size >> 8);
        b[at++] = (uint8_t)(extra_size >> 16); b[at++] = (uint8_t)(extra_size >> 24);
        /* A body is emitted only when one plausibly fits. That is the whole
           difference between the two kinds of case here: a small size gets a
           real chunk the parser should skip cleanly, while a large or hostile
           size gets a header that lies about a body which is not there — which
           is precisely the shape an attacker sends. */
        if (extra_size <= 64) {
            size_t pad = extra_size + (extra_size & 1);
            memset(b + at, 0, pad);
            at += pad;
        }
    }

    memcpy(b + at, "fmt ", 4); at += 4;
    b[at++] = 16; b[at++] = 0; b[at++] = 0; b[at++] = 0;
    b[at++] = (uint8_t)format;   b[at++] = (uint8_t)(format >> 8);
    b[at++] = (uint8_t)channels; b[at++] = (uint8_t)(channels >> 8);
    b[at++] = (uint8_t)rate; b[at++] = (uint8_t)(rate >> 8);
    b[at++] = (uint8_t)(rate >> 16); b[at++] = (uint8_t)(rate >> 24);
    at += 6;                                    /* byte rate + block align */
    b[at++] = (uint8_t)bits; b[at++] = (uint8_t)(bits >> 8);

    if (with_data) {
        memcpy(b + at, "data", 4); at += 4;
        b[at++] = (uint8_t)(data_size); b[at++] = (uint8_t)(data_size >> 8);
        b[at++] = (uint8_t)(data_size >> 16); b[at++] = (uint8_t)(data_size >> 24);
    }
    return at;
}

static size_t good(uint8_t *b) {
    return build(b, NULL, 0, 1, 1, 16000, 16, 32000, 1);
}

int main(int argc, char **argv) {
    /* Any hang is a failure, not a hung test run. Every case below is
       microseconds of work; the sweep is seconds. */
    alarm(120);

    uint8_t b[256];
    SndWav w;
    const char *err;

    printf("valid headers\n");
    {
        size_t n = good(b);
        memset(&w, 0, sizeof(w)); err = NULL;
        check(snd_wav_parse(b, n, w, &err), "canonical 16kHz mono 16-bit parses");
        check(w.rate == 16000, "rate reported as 16000");
        check(w.data_len == 32000, "data_len reported as 32000");
        check(w.data_off == n, "data_off points just past the header");
    }
    for (int i = 0; i < 5; i++) {
        static const uint32_t rates[] = {8000, 16000, 32000, 44100, 48000};
        size_t n = build(b, NULL, 0, 1, 1, rates[i], 16, 32000, 1);
        memset(&w, 0, sizeof(w)); err = NULL;
        char msg[64];
        snprintf(msg, sizeof(msg), "%u Hz accepted", (unsigned)rates[i]);
        check(snd_wav_parse(b, n, w, &err), msg);
    }
    {
        /* A skippable chunk before fmt is legal and common (LIST/fact). */
        size_t n = build(b, "LIST", 4, 1, 1, 16000, 16, 32000, 1);
        memset(&w, 0, sizeof(w)); err = NULL;
        check(snd_wav_parse(b, n, w, &err), "a 4-byte LIST chunk is skipped");
    }

    printf("rejected headers\n");
    {
        size_t n = good(b);
        memcpy(b, "RIFX", 4);
        err = NULL;
        check(!snd_wav_parse(b, n, w, &err), "bad RIFF magic rejected");
        check(err != NULL, "  ...with a reason");
    }
    {
        size_t n = build(b, NULL, 0, 1, 2, 16000, 16, 32000, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "stereo rejected");
        n = build(b, NULL, 0, 1, 1, 16000, 8, 32000, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "8-bit rejected");
        n = build(b, NULL, 0, 0xFFFE, 1, 16000, 16, 32000, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "WAVE_FORMAT_EXTENSIBLE rejected");
        n = build(b, NULL, 0, 1, 1, 22050, 16, 32000, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "22050 Hz rejected (amp cannot clock it)");
        n = build(b, NULL, 0, 1, 1, 96000, 16, 32000, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "96000 Hz rejected");
        n = build(b, NULL, 0, 1, 1, 16000, 16, 0, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "zero-length data rejected");
        n = build(b, NULL, 0, 1, 1, 16000, 16, 32001, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "odd-length data rejected");
        n = build(b, NULL, 0, 1, 1, 16000, 16, SND_DATA_MAX + 2, 1);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "oversized data rejected");
        n = build(b, NULL, 0, 1, 1, 16000, 16, 32000, 0);
        err = NULL; check(!snd_wav_parse(b, n, w, &err), "missing data chunk rejected");
    }
    for (size_t n = 0; n < 12; n++) {
        err = NULL;
        if (snd_wav_parse(b, n, w, &err)) { printf("  FAIL: %zu-byte input accepted\n", n); failures++; }
    }
    check(1, "inputs shorter than 12 bytes all rejected");

    printf("the hang: chunk sizes that used to stop the walk advancing\n");
    {
        /* 8 + size + (size & 1) == 0 (mod 2^32). Before the fix each of these
           left `at` unchanged with `at + 8 <= n` still true. */
        static const uint32_t evil[] = {0xFFFFFFF7u, 0xFFFFFFF8u};
        for (int i = 0; i < 2; i++) {
            size_t n = build(b, "junk", evil[i], 1, 1, 16000, 16, 32000, 1);
            err = NULL;
            snd_wav_parse(b, n, w, &err);   /* must simply return */
            char msg[64];
            snprintf(msg, sizeof(msg), "size 0x%08X terminates", (unsigned)evil[i]);
            check(1, msg);
        }
    }
    {
        /* Sizes that used to walk backwards, plus the boundaries around them. */
        static const uint32_t nasty[] = {
            0u, 1u, 2u, 0x7FFFFFFFu, 0x80000000u, 0x80000001u,
            0xFFFFFFF0u, 0xFFFFFFF5u, 0xFFFFFFF6u, 0xFFFFFFF9u,
            0xFFFFFFFAu, 0xFFFFFFFEu, 0xFFFFFFFFu,
        };
        for (size_t i = 0; i < sizeof(nasty) / sizeof(nasty[0]); i++) {
            size_t n = build(b, "junk", nasty[i], 1, 1, 16000, 16, 32000, 1);
            err = NULL;
            snd_wav_parse(b, n, w, &err);
        }
        check(1, "13 boundary sizes all terminate");
    }
    {
        /* Two skippable chunks, so a crafted pair cannot cycle between them. */
        for (uint32_t s = 0; s < 70000u; s++) {
            size_t n = build(b, "junk", s, 1, 1, 16000, 16, 32000, 1);
            err = NULL;
            snd_wav_parse(b, n, w, &err);
        }
        check(1, "70000 consecutive sizes all terminate");
    }

    if (argc > 1 && strcmp(argv[1], "--full") == 0) {
        printf("exhaustive: every uint32 size advances the walk strictly forward\n");
        /* The advance, in isolation and in the firmware's own 64-bit form. The
           parser's termination argument is exactly this property plus the
           `next > n` break, so proving it for all 2^32 values proves no chunk
           size can stall the loop. */
        const uint64_t at = 12, body = at + 8;
        uint32_t bad = 0;
        uint32_t s = 0;
        do {
            uint64_t next = (uint64_t)body + (uint64_t)s + (uint64_t)(s & 1);
            if (next <= at) bad++;
            s++;
        } while (s != 0);
        check(bad == 0, "all 4294967296 sizes give next > at");
    } else {
        printf("exhaustive sweep skipped (pass --full to run it)\n");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test" "$@"
