#!/usr/bin/env bash
#
# Host-side regression test for the night window and its switch, in
# src/skills/ring.cpp.
#
# Why this exists: switching the silence off means setting the two boundaries
# equal, and this device has no time entry of any kind — so the hours are gone
# the instant they are erased, and nothing on the device can get them back. The
# owner's real 00:00-08:00 window only existed at all because it was written
# down in a chat message. A toggle that forgets is not a toggle that is slightly
# wrong; it is one that destroys the setting it exists to control, silently, on
# the click that was meant to be reversible.
#
# The wrap around midnight has the same shape of failure. `22:00-07:00` is the
# window most people actually want, and a boundary comparison that is written
# the obvious way makes it match nothing at all — the ring simply never goes
# dark, and the only witness is somebody awake at three in the morning.
#
# This release also EXTRACTED that rule out of ring_night_now(), which is live
# behaviour on a device that is in somebody's house. So the last section below
# is a characterization test: the 0.12.0 expression is kept here verbatim as an
# oracle and the shipping code is compared against it over every window in the
# day, so "the extraction changed nothing" is a measurement rather than a claim.
#
# What this DOES NOT cover, said plainly rather than papered over:
#
#   - the clock itself. ring_night_now() calls clock_local_time(), and that call
#     needs a device. What it does with the answer does not: the "time unknown
#     -> stay lit" rule is a parameter of ring_night_active() and is checked
#     below. What is NOT checked is that the minute handed to it is really
#     tm_hour * 60 + tm_min — that line has no test and cannot have one here.
#   - the panel and the ring. The menu row, the clock face's mark and whether a
#     click reaches ring_quiet_toggle() at all need TFT_eSPI, a WS2812 string
#     and a hand. The row's TEXT is here — ring_quiet_hours() takes a window
#     rather than reading the live words, precisely so that it can be, and the
#     decision a click makes is ring_quiet_flip()'s and is driven directly.
#   - SPIFFS. That the document reaches the flash and comes back is
#     read_spiffs_file()'s and write_spiffs_file_atomic()'s, and neither is here.
#     What IS here is the whole of what gets written, what a stored document
#     turns into, and whether reading one schedules a write at all — which is
#     where the version-to-version failures live.
#   - the HTTP layer, which tools/test_routes.sh checks for the failure mode it
#     actually has.
#
# One check below — "every window in the day is compared" — cannot be made to
# fail by any change to ring.cpp, and says so at its own site. It counts the
# test's own loop, so that a sweep somebody later guts does not go on reporting
# zero differences over nothing. Every other check here was verified by
# reintroducing the defect it claims to catch.
#
# The rules are sliced straight out of the shipping source between its
# `host-test:begin <tag>` and `host-test:end` markers — consts, quiet, settings,
# pair, stored, docapply and label — the same way tools/test_progress.sh slices
# its arbiter, so this runs the real implementation rather than a copy that
# could drift. The stored-document half is driven with literal JSON through the
# real ArduinoJson, the same idiom tools/test_notify_options.sh uses on the
# 0.9.0 snapshot.
#
# The live settings words and the real ring_cfg_mark_dirty() are sliced in as
# well, so "loading a file schedules no flash write" is checked against the
# actual save flag rather than against a promise. millis() is the only thing
# stubbed here, and it is Arduino's rather than ring.cpp's.
#
# Usage: tools/test_quiet.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/ring.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

json="${ARDUINOJSON_DIR:-$here/../.pio/libdeps/tembed/ArduinoJson/src}"
if [ ! -f "$json/ArduinoJson.h" ]; then
    echo "cannot find ArduinoJson.h under $json"
    echo "run 'pio run -e tembed' once to fetch it, or set ARDUINOJSON_DIR"
    exit 1
fi

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_quiet.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <string>
#include <ArduinoJson.h>

/* The one stub in this file, and it is Arduino's rather than ring.cpp's:
   ring_cfg_mark_dirty() stamps a deadline with it. Frozen, because nothing here
   is about when the deferred write lands — only about whether one was asked
   for at all. */
static unsigned long millis(void) { return 100000UL; }

PRELUDE
    # The compiled constants come out of the source too, rather than being
    # repeated here: "switching on with nothing remembered lands on the
    # firmware's own default" is a claim about the firmware's number, and a copy
    # that drifted would move the answer in the test only.
    slice "$src" consts
    slice "$src" quiet
    # The live words and the save scheduler that reads them, so the load
    # section below can ask the real flag whether a write was scheduled.
    slice "$src" settings
    slice "$src" pair
    slice "$src" stored
    slice "$src" docapply
    slice "$src" label
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

#define HM(h, m) ((uint16_t)((h) * 60 + (m)))

/* A window, and the state of the pair it is switched with. */
static RingQuiet made(uint16_t from, uint16_t to,
                      uint16_t saved_from, uint16_t saved_to) {
    RingQuiet q;
    q.from = from;
    q.to = to;
    q.saved_from = saved_from;
    q.saved_to = saved_to;
    return q;
}

static void window_is(const RingQuiet &q, uint16_t from, uint16_t to,
                      const char *what) {
    if (q.from != from || q.to != to) {
        printf("  FAIL: %s — window is %02u:%02u-%02u:%02u, wanted %02u:%02u-%02u:%02u\n",
               what, q.from / 60, q.from % 60, q.to / 60, q.to % 60,
               from / 60, from % 60, to / 60, to % 60);
        failures++;
    } else {
        printf("  ok:   %s — %02u:%02u-%02u:%02u\n", what,
               q.from / 60, q.from % 60, q.to / 60, q.to % 60);
    }
}

static void saved_is(const RingQuiet &q, uint16_t from, uint16_t to,
                     const char *what) {
    if (q.saved_from != from || q.saved_to != to) {
        printf("  FAIL: %s — saved is %02u:%02u-%02u:%02u, wanted %02u:%02u-%02u:%02u\n",
               what, q.saved_from / 60, q.saved_from % 60,
               q.saved_to / 60, q.saved_to % 60,
               from / 60, from % 60, to / 60, to % 60);
        failures++;
    } else {
        printf("  ok:   %s — %02u:%02u-%02u:%02u\n", what,
               q.saved_from / 60, q.saved_from % 60,
               q.saved_to / 60, q.saved_to % 60);
    }
}

/* The switch as the menu works it. This is the shipping ring_quiet_flip() with
   the compiled defaults filled in and nothing else: the decision used to be
   spelled out here, which pinned this file's copy of it rather than the
   firmware's. ring_quiet_toggle() is the same call against the live words. */
static void toggle(RingQuiet &q) {
    ring_quiet_flip(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
}

/* Load one stored settings document, exactly as ring_cfg_load() does: the pair
   starts at what the firmware would have with no file at all — the compiled
   defaults and nothing remembered — and the document is read over it. */
static RingQuiet load(const char *stored) {
    RingQuiet q = made(RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT, 0, 0);
    JsonDocument doc;
    if (deserializeJson(doc, stored) != DeserializationError::Ok) {
        printf("  FAIL: test JSON did not parse: %s\n", stored);
        failures++;
        return q;
    }
    ring_quiet_restore(doc.as<JsonObjectConst>(), q);
    return q;
}

/* The live words as a fresh boot has them, and the save scheduler's flag with
   them: the compiled defaults, nothing remembered, nothing to write. This is
   exactly the state ring_cfg_load() reads a stored document over. */
static void booted(void) {
    ring_enabled = true;
    ring_brightness = RING_BRIGHT_DEFAULT;
    ring_night_from = RING_NIGHT_FROM_DEFAULT;
    ring_night_to = RING_NIGHT_TO_DEFAULT;
    ring_night_saved_from = 0;
    ring_night_saved_to = 0;
    ring_cfg_dirty = false;
    ring_cfg_save_at = 0;
}

/* Boot, read one stored document exactly as ring_cfg_load() does past the file
   read and the parse, and answer the only question this section asks: did that
   schedule a flash write? */
static bool load_schedules_write(const char *stored) {
    booted();
    JsonDocument doc;
    if (deserializeJson(doc, stored) != DeserializationError::Ok) {
        printf("  FAIL: test JSON did not parse: %s\n", stored);
        failures++;
        return true;
    }
    ring_cfg_apply_doc(doc.as<JsonObjectConst>());
    return ring_cfg_dirty;
}

/*
 * ring_night_now()'s rule as 0.12.0 wrote it, kept verbatim as an oracle.
 *
 * This is a copy, and copies are normally the thing to avoid — but the point of
 * it is to be a copy: 0.13.0 lifted this expression out of ring_night_now()
 * into ring_night_holds(), on a device that is somebody's pager, and the only
 * honest way to say "that changed nothing" is to keep the old expression and
 * compare. It is frozen. If the rule is ever meant to change, this does not
 * get edited to match — it gets deleted along with the section that uses it.
 */
static bool oracle_0_12_0(uint16_t night_from, uint16_t night_to, bool clock_ok,
                          int m) {
    if (night_from == night_to) return false;
    if (!clock_ok) return false;
    if (night_from < night_to)
        return m >= night_from && m < night_to;
    return m >= night_from || m < night_to;
}

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    printf("an empty window is how the silence is switched off\n");
    {
        check(!ring_night_is_window(0, 0), "midnight to midnight is no window");
        check(!ring_night_is_window(HM(23, 30), HM(23, 30)), "and so is any other pair of equal hours");
        check(ring_night_is_window(0, HM(8, 0)), "00:00-08:00 is a window");
        check(ring_night_is_window(HM(22, 0), HM(7, 0)), "and so is one that wraps midnight");
        /* One minute apart is the shortest window there is, and it must not be
           mistaken for none: the predicate is equality, not nearness. */
        check(ring_night_is_window(HM(3, 0), HM(3, 1)), "one minute is still a window");
    }

    printf("inside the window, and outside it\n");
    {
        check(ring_night_holds(0, HM(8, 0), HM(3, 0)), "03:00 is inside 00:00-08:00");
        check(!ring_night_holds(0, HM(8, 0), HM(12, 0)), "noon is not");
        check(!ring_night_holds(0, 0, HM(3, 0)), "an empty window holds no minute at all");
        check(!ring_night_holds(HM(9, 0), HM(9, 0), HM(9, 0)),
              "not even the minute it is collapsed onto");
    }

    printf("the boundaries, which are asymmetric on purpose\n");
    {
        /* The start is inclusive and the end exclusive, so 08:00 is the first
           minute of the morning rather than the last of the night. Off by one
           either way is a minute of wrong silence a day, which nobody would
           ever notice as a bug. */
        check(ring_night_holds(0, HM(8, 0), 0), "the first minute of the window is inside it");
        check(ring_night_holds(0, HM(8, 0), HM(7, 59)), "the last minute before the end is inside it");
        check(!ring_night_holds(0, HM(8, 0), HM(8, 0)), "the end itself is outside");
        check(!ring_night_holds(HM(1, 0), HM(8, 0), HM(0, 59)),
              "and the minute before the start is outside");
    }

    printf("a window that wraps midnight — the shape people actually set\n");
    {
        check(ring_night_holds(HM(22, 0), HM(7, 0), HM(23, 30)), "23:30 is inside 22:00-07:00");
        check(ring_night_holds(HM(22, 0), HM(7, 0), HM(2, 0)), "and so is 02:00, on the far side of midnight");
        check(ring_night_holds(HM(22, 0), HM(7, 0), 0), "and midnight exactly");
        check(!ring_night_holds(HM(22, 0), HM(7, 0), HM(12, 0)), "noon is outside it");
        check(!ring_night_holds(HM(22, 0), HM(7, 0), HM(21, 59)), "and so is the minute before it opens");
        check(ring_night_holds(HM(22, 0), HM(7, 0), HM(22, 0)), "the opening minute is inside");
        check(!ring_night_holds(HM(22, 0), HM(7, 0), HM(7, 0)), "the closing one is not");
        /* The last minute of the day, which is the one a wrap gets wrong when
           the comparison is written as a range rather than as a union. */
        check(ring_night_holds(HM(22, 0), HM(7, 0), HM(23, 59)), "23:59 is inside");
    }

    printf("switching off remembers the hours\n");
    {
        /* THE test this commit exists for. Nothing else on the device holds
           these two numbers once the window is emptied. */
        RingQuiet q = made(0, HM(8, 0), 0, 0);
        ring_quiet_switch(q, false, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
        check(!ring_night_is_window(q.from, q.to), "the window is empty afterwards");
        saved_is(q, 0, HM(8, 0), "and the hours are still here");
    }

    printf("switching back on restores exactly what was switched off\n");
    {
        RingQuiet q = made(HM(22, 30), HM(6, 45), 0, 0);
        toggle(q);
        check(!ring_night_is_window(q.from, q.to), "off empties a wrapped window too");
        toggle(q);
        window_is(q, HM(22, 30), HM(6, 45), "and on brings that same window back");
        check(ring_night_holds(q.from, q.to, HM(2, 0)),
              "which still wraps midnight, so 02:00 is inside it again");

        /* Round and round: a toggle that leaked a minute per cycle would look
           fine once and be wrong by morning. */
        for (int i = 0; i < 20; i++) toggle(q);
        window_is(q, HM(22, 30), HM(6, 45), "and after ten more round trips it is unchanged");
    }

    printf("the switch says which way it went\n");
    {
        /* ring_quiet_toggle()'s event line is written from this answer — "on"
           against "off, kept" — and it is the only record of a click anybody
           reads afterwards. A flip that moved the window correctly and reported
           the opposite would log the reverse of what the device did, which is
           worse than no log. */
        RingQuiet q = made(0, HM(8, 0), 0, 0);
        check(!ring_quiet_flip(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT),
              "a window that is set switches off");
        check(ring_quiet_flip(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT),
              "and an empty one switches on");
        /* Said against the window it produced, so "reports on" and "is on"
           cannot drift apart. */
        check(ring_night_is_window(q.from, q.to),
              "and what it reported is what the window then is");
    }

    printf("switching on with nothing remembered\n");
    {
        /* The upgrade case, not a theoretical one: a device whose stored window
           was already empty before the saved pair existed comes up with nothing
           to restore, and the toggle must still do something. */
        RingQuiet q = made(0, 0, 0, 0);
        toggle(q);
        window_is(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "an empty saved pair falls back to the compiled default");
        saved_is(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                 "and the fallback becomes what is remembered");
        toggle(q);
        toggle(q);
        window_is(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "so the next round trip restores it rather than defaulting again");

        /* An equal saved pair that is not 00:00 is the same "nothing
           remembered", because that is the one encoding for "no window". A
           restore of 09:00-09:00 would be a toggle that switches on and stays
           audible — the failure that looks exactly like a broken button. */
        RingQuiet r = made(0, 0, HM(9, 0), HM(9, 0));
        toggle(r);
        window_is(r, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "an equal saved pair is nothing remembered, whatever hour it names");
        check(ring_night_is_window(r.from, r.to), "so switching on always lands on a real window");
    }

    printf("the restore point follows the window that is actually set\n");
    {
        /* ring_quiet_keep() is called wherever the window is set — the menu,
           POST /ring, the config load — so the toggle brings back the schedule
           this device was last keeping rather than the one it was given the
           last time somebody stood in front of it. */
        /* The pair starts out disagreeing, so that a keep() which did nothing
           at all would be caught here rather than looking like a pass. */
        RingQuiet q = made(0, HM(8, 0), HM(9, 0), HM(10, 0));
        ring_quiet_keep(q);
        saved_is(q, 0, HM(8, 0), "setting a window records it");

        q.from = HM(23, 0);
        q.to = HM(7, 30);
        ring_quiet_keep(q);
        saved_is(q, HM(23, 0), HM(7, 30), "and setting a different one replaces the record");

        toggle(q);
        toggle(q);
        window_is(q, HM(23, 0), HM(7, 30), "so a round trip returns the newer window, not the older");
    }

    printf("an empty window is never recorded as the thing to restore\n");
    {
        /* The one way the whole arrangement could still lose the hours: if
           emptying the window were itself remembered, the next switch-on would
           restore nothing and the schedule would be gone after two clicks. */
        RingQuiet q = made(HM(23, 0), HM(23, 0), HM(22, 0), HM(7, 0));
        ring_quiet_keep(q);
        saved_is(q, HM(22, 0), HM(7, 0), "keeping an empty window leaves the record alone");
        toggle(q);
        window_is(q, HM(22, 0), HM(7, 0), "and the hours are still there to switch back on");
    }

    printf("switching off is idempotent, and so is switching on\n");
    {
        /* Both directions are driven by a click, and a click that arrives twice
           — a bounce, a second hand on the knob — must not be able to move the
           hours anywhere. */
        RingQuiet q = made(HM(22, 0), HM(7, 0), 0, 0);
        ring_quiet_switch(q, false, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
        ring_quiet_switch(q, false, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
        ring_quiet_switch(q, false, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
        saved_is(q, HM(22, 0), HM(7, 0), "three switches off keep the first window");
        ring_quiet_switch(q, true, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
        ring_quiet_switch(q, true, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
        window_is(q, HM(22, 0), HM(7, 0), "and switching on twice lands on it exactly once");
    }

    printf("every window survives a round trip, not just the convenient ones\n");
    {
        /* Exhaustive over the minute: 1440 starts against a handful of shapes,
           including the wrap, the one-minute window and the window that ends at
           midnight. A remember/restore that dropped a special case — the hour
           0, the last minute of the day — would pass every example above. */
        int bad = 0, tried = 0;
        for (int f = 0; f < 1440; f++) {
            static const int spans[] = {1, 60, 480, 720, 1439};
            for (unsigned s = 0; s < sizeof(spans) / sizeof(spans[0]); s++) {
                uint16_t from = (uint16_t)f;
                uint16_t to = (uint16_t)((f + spans[s]) % 1440);
                if (!ring_night_is_window(from, to)) continue;
                tried++;
                RingQuiet q = made(from, to, 0, 0);
                toggle(q);
                if (ring_night_is_window(q.from, q.to)) { bad++; continue; }
                toggle(q);
                if (q.from != from || q.to != to) bad++;
            }
        }
        printf("  ..   %d window(s) tried, %d failed a round trip\n", tried, bad);
        /* The count is checked as well as the failures: a predicate that
           reported every window as empty would skip the whole loop and leave
           this looking like a pass over nothing. */
        check(tried == 1440 * 5, "every window in the day is exercised");
        check(bad == 0, "and every one of them switches off and comes back unchanged");
    }

    printf("what the window means is unchanged by switching it\n");
    {
        /* The predicate and the switch are one feature in two halves, and the
           half that decides silence must be reading the same window the half
           that stores it wrote. Checked against the minute, so a restore that
           swapped the two boundaries would be caught here rather than by
           somebody lying awake. */
        RingQuiet q = made(HM(22, 0), HM(7, 0), 0, 0);
        check(ring_night_holds(q.from, q.to, HM(23, 0)), "23:00 is silent before the switch");
        toggle(q);
        check(!ring_night_holds(q.from, q.to, HM(23, 0)), "and audible while it is off");
        toggle(q);
        check(ring_night_holds(q.from, q.to, HM(23, 0)), "and silent again after");
        check(!ring_night_holds(q.from, q.to, HM(12, 0)), "while noon is audible throughout");
    }

    printf("a settings file written by 0.12.0, read by this firmware\n");
    {
        /* Every /ring.json on every device was written without qf/qt, so this
           is the next boot everywhere rather than an edge case. */
        RingQuiet q = load("{\"on\":true,\"b\":50,\"nf\":1320,\"nt\":420}");
        window_is(q, HM(22, 0), HM(7, 0), "the stored window survives the update");
        saved_is(q, HM(22, 0), HM(7, 0), "and becomes what the toggle restores");
        toggle(q);
        check(!ring_night_is_window(q.from, q.to), "so the new row can switch it off");
        toggle(q);
        window_is(q, HM(22, 0), HM(7, 0), "and switch it back on, unchanged");
    }

    printf("the owner's own device tonight: switched off over the network\n");
    {
        /* nf == nt == 0, no qf/qt. The hours are already gone — this firmware
           cannot conjure them back, and must not pretend to. What it must do is
           come up switchable, with an honest "off". */
        RingQuiet q = load("{\"on\":true,\"b\":50,\"nf\":0,\"nt\":0}");
        check(!ring_night_is_window(q.from, q.to), "it comes up with the silence off");
        saved_is(q, 0, 0, "with nothing remembered, rather than a window invented for it");
        toggle(q);
        window_is(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "and switching on lands on the compiled default");
        toggle(q);
        toggle(q);
        window_is(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "which is then remembered like any other window");
    }

    printf("a stored empty saved pair is the same as no saved pair\n");
    {
        /* Deliberately indistinguishable: an empty pair IS "nothing
           remembered", one encoding rather than two. */
        RingQuiet a = load("{\"nf\":0,\"nt\":0,\"qf\":0,\"qt\":0}");
        RingQuiet b = load("{\"nf\":0,\"nt\":0}");
        check(a.saved_from == b.saved_from && a.saved_to == b.saved_to,
              "an equal stored pair loads the same as an absent one");
        RingQuiet c = load("{\"nf\":0,\"nt\":0,\"qf\":540,\"qt\":540}");
        toggle(c);
        window_is(c, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "and an equal pair naming 09:00 restores no 09:00 window");
    }

    printf("a file this firmware wrote, read back by it\n");
    {
        RingQuiet q = load("{\"on\":true,\"b\":50,\"nf\":0,\"nt\":0,\"qf\":1350,\"qt\":450}");
        check(!ring_night_is_window(q.from, q.to), "the silence is off, as stored");
        saved_is(q, HM(22, 30), HM(7, 30), "and the remembered window came back with it");
        toggle(q);
        window_is(q, HM(22, 30), HM(7, 30), "so a reboot did not cost the schedule");
    }

    printf("a stored document that is wrong, in each of the ways it can be\n");
    {
        /* A stored file gets the same treatment a request body does: this
           filesystem can be replaced by anyone who can write an image. A
           refused field leaves the compiled default standing rather than
           landing a nonsense window on a device nobody is looking at. */
        window_is(load("{}"), RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "an empty document leaves the compiled default");
        window_is(load("{\"nf\":1320}"), RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT,
                  "half a window is not half applied");
        window_is(load("{\"nf\":1320,\"nt\":1440}"), RING_NIGHT_FROM_DEFAULT,
                  RING_NIGHT_TO_DEFAULT, "a boundary at 24:00 is refused whole");
        window_is(load("{\"nf\":-1,\"nt\":420}"), RING_NIGHT_FROM_DEFAULT,
                  RING_NIGHT_TO_DEFAULT, "and so is a negative one");
        window_is(load("{\"nf\":\"22:00\",\"nt\":\"07:00\"}"), RING_NIGHT_FROM_DEFAULT,
                  RING_NIGHT_TO_DEFAULT, "the stored form is minutes, not \"HH:MM\"");
        saved_is(load("{\"nf\":0,\"nt\":0,\"qf\":1320,\"qt\":9999}"), 0, 0,
                 "an out-of-range saved boundary takes neither half with it");
        /* The last minute of the day is inside the range and must be accepted:
           an off-by-one in the clamp would quietly refuse 23:59. */
        window_is(load("{\"nf\":1439,\"nt\":420}"), HM(23, 59), HM(7, 0),
                  "23:59 is a valid boundary");
    }

    printf("reading the settings file schedules no flash write\n");
    {
        /* A power cycle must not cost an erase cycle. This is easy to get
           wrong in exactly one way: ring_quiet_restore() finishes by deriving
           the restore point from the live window, so the pair a load produces
           differs from the words it started with for very nearly every
           document there is — and an apply that also marked the config dirty
           therefore rewrote /ring.json on EVERY boot, not on some files. The
           three below are the three shapes every device is in. */
        check(!load_schedules_write("{\"on\":true,\"b\":50,\"nf\":0,\"nt\":0}"),
              "the owner's own file — window switched off — schedules nothing");
        check(!load_schedules_write("{\"on\":true,\"b\":50,\"nf\":0,\"nt\":480}"),
              "a file identical to the compiled defaults schedules nothing");
        check(!load_schedules_write("{}"),
              "and a document that says nothing at all schedules nothing");
        /* A file whose saved pair is already stored still schedules nothing:
           this is what the device writes once it has been switched, and it is
           the one that comes back byte for byte. */
        check(!load_schedules_write("{\"nf\":0,\"nt\":0,\"qf\":1320,\"qt\":420}"),
              "nor does one this firmware wrote itself");

        /* The precondition, without which every check above would pass on a
           load that did nothing at all. */
        booted();
        {
            JsonDocument doc;
            deserializeJson(doc, "{\"b\":35,\"nf\":1320,\"nt\":420}");
            ring_cfg_apply_doc(doc.as<JsonObjectConst>());
            check(ring_brightness == 35 && ring_night_from == HM(22, 0) &&
                  ring_night_to == HM(7, 0),
                  "while the document is still applied — the load is not a no-op");
            saved_is(made(0, 0, ring_night_saved_from, ring_night_saved_to),
                     HM(22, 0), HM(7, 0),
                     "and the restore point is still derived from it");
        }

        /* The other half of the split: a change somebody actually made does
           schedule one. Without this, deleting the mark everywhere would pass.
           These three lines are ring_quiet_toggle()'s body without its event
           line — every part of it that is not a live-word read. */
        booted();
        {
            RingQuiet q;
            ring_quiet_read(q);
            ring_quiet_flip(q, RING_NIGHT_FROM_DEFAULT, RING_NIGHT_TO_DEFAULT);
            if (ring_quiet_apply(q)) ring_cfg_mark_dirty();
            check(ring_cfg_dirty, "while switching the silence off does schedule one");
        }

        /* And a change that changes nothing does not, which is what makes the
           coalescing window worth having. */
        booted();
        {
            RingQuiet q;
            ring_quiet_read(q);
            if (ring_quiet_apply(q)) ring_cfg_mark_dirty();
            check(!ring_cfg_dirty, "and setting the window it already had does not");
        }
    }

    printf("the menu row's hours, which are the only new string on the device\n");
    {
        char s[16];
        ring_quiet_hours(0, HM(8, 0), s, sizeof(s));
        check(strcmp(s, "00:00-08:00") == 0, "a window reads as its two hours");
        ring_quiet_hours(HM(22, 30), HM(7, 0), s, sizeof(s));
        check(strcmp(s, "22:30-07:00") == 0, "including one that wraps midnight");
        ring_quiet_hours(0, 0, s, sizeof(s));
        check(strcmp(s, "off") == 0, "an empty window reads as off");
        ring_quiet_hours(HM(9, 0), HM(9, 0), s, sizeof(s));
        check(strcmp(s, "off") == 0, "and so does an equal pair naming any other hour");
        /* Both halves padded to two digits, or 09:05 would print as 9:5 and the
           row would change width as the clock moved. */
        ring_quiet_hours(HM(9, 5), HM(7, 0), s, sizeof(s));
        check(strcmp(s, "09:05-07:00") == 0, "hours and minutes are both padded");
        /* The width argument at the call site in ui.h counts these characters.
           ui.h writes "Quiet " in front of them, so eleven here is the
           seventeen that, with the row's marker, measures 218px of font 4
           against the 296px ui_draw_row() has. A longer string runs off the
           panel, so the length is pinned rather than left as a sentence in a
           comment. */
        ring_quiet_hours(HM(23, 59), HM(23, 58), s, sizeof(s));
        check(strlen(s) == 11, "the longest is 11 characters, the 17 ui.h measured less \"Quiet \"");
    }

    printf("the extraction out of ring_night_now(), against 0.12.0 itself\n");
    {
        /* The rule moved to its own function on a device in somebody's house.
           This compares the shipping code with the expression it was lifted
           from, over every window in the day and the minutes that decide one:
           the two boundaries and their neighbours, midnight, noon and the last
           minute of the day. Nothing about the shape of the new code is
           assumed — only that it answers the same thing. */
        long compared = 0, differed = 0;
        for (int f = 0; f < 1440; f++) {
            for (int t = 0; t < 1440; t++) {
                const int probes[] = { 0, f - 1, f, f + 1, t - 1, t, t + 1, 720, 1439 };
                for (unsigned i = 0; i < sizeof(probes) / sizeof(probes[0]); i++) {
                    int m = probes[i];
                    if (m < 0) m += 1440;
                    if (m > 1439) m -= 1440;
                    compared++;
                    if (ring_night_active((uint16_t)f, (uint16_t)t, true, m)
                            != oracle_0_12_0((uint16_t)f, (uint16_t)t, true, m))
                        differed++;
                }
            }
        }
        printf("  ..   %ld comparisons, %ld difference(s)\n", compared, differed);
        /* THIS ONE CANNOT BE MADE TO FAIL BY ANY CHANGE TO ring.cpp, and it is
           left in knowing that: `compared` counts the loop above, which nothing
           in the source can reach. It is a guard on the TEST — an edit that
           gutted the sweep would otherwise leave "0 differences" reading like a
           pass over nothing. Its sibling in the round-trip section IS killable,
           because that one counts only what the source called a window. */
        check(compared == 1440L * 1440L * 9, "every window in the day is compared");
        check(differed == 0, "and the extracted rule answers exactly what 0.12.0 answered");
    }

    printf("a clock that has never been set leaves the ring lit\n");
    {
        /* The direction to be wrong in: a node that has not reached NTP is
           usually a freshly booted or offline one, and going dark because the
           time is unknown is the failure that loses messages. */
        check(!ring_night_active(0, HM(8, 0), false, HM(3, 0)),
              "03:00 is not silent when the clock was never set");
        check(ring_night_active(0, HM(8, 0), true, HM(3, 0)),
              "and is silent once it has been");
        check(!ring_night_active(HM(22, 0), HM(7, 0), false, HM(23, 0)),
              "the same for a window that wraps midnight");
        /* Which is what 0.12.0 did too, so the extraction did not quietly
           change the answer for an unset clock either. */
        int differed = 0;
        for (int f = 0; f < 1440; f += 7)
            for (int m = 0; m < 1440; m += 7)
                if (ring_night_active((uint16_t)f, HM(8, 0), false, m)
                        != oracle_0_12_0((uint16_t)f, HM(8, 0), false, m))
                    differed++;
        check(differed == 0, "and 0.12.0 stayed lit in every one of those cases as well");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -I "$json" \
    -o "$work/test" "$work/test.cpp"
"$work/test"
