#!/usr/bin/env bash
#
# Host-side regression test for the backlight ladder in src/skills/backlight.cpp.
#
# Why this exists: the AW9364 has no readback. Nothing can ask the part what
# step it is standing on, so the firmware's idea of the level is a MODEL that is
# kept in step with the hardware by counting, and the only thing keeping the two
# together is the arithmetic below. If the pulse count is wrong by one the
# screen does not go dark and nothing throws — it settles on a neighbouring
# brightness, the model and the part disagree from then on, and every later
# change is wrong by the same one. There is no witness to that but somebody
# noticing the screen looks off, and no test on hardware finds it either,
# because reading the level back is exactly what the part cannot do.
#
# The wrap is the half of it that is easy to get wrong. The counter only ever
# steps DOWN and wraps modulo 16, so getting BRIGHTER means going all the way
# round: the naive subtraction gives a negative count, and the naive
# special-case gives the right answer for "brighter" and the wrong one for
# "already there". Both bugs look identical from a desk — the screen simply
# stops responding to some of the settings.
#
# So the ladder is checked against the datasheet in the datasheet's own terms:
# Table 1 of the AW9364 (Awinic, Feb 2018 V2.3) is copied in below as an oracle,
# and the pulse counts are checked against a simulated part that implements
# nothing but "each rising edge advances a counter modulo 16", which is the one
# sentence the whole protocol comes down to.
#
# What this DOES NOT cover, said plainly rather than papered over:
#
#   - the pulses reaching the pin. The register writes, the critical section
#     and the microsecond delays need the chip; nothing here claims otherwise.
#     What IS checked is the number those pulses have to come to.
#   - the timing. That T_LO stays under the part's 500us maximum is a property
#     of the critical section and of delayMicroseconds(), neither of which
#     exists on the host.
#   - the panel. Whether "night" is actually readable is a question for eyes in
#     a room, and it is the reason the preset table is four numbers in one place
#     rather than a curve.
#
# The core is sliced straight out of the shipping source between its
# `host-test:begin` markers, the same way tools/test_progress.sh and
# tools/test_quiet.sh slice theirs, so this runs the real implementation rather
# than a copy that could drift.
#
# Usage: tools/test_backlight.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/backlight.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_backlight.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

PRELUDE
    slice "$src" bl_ladder
    slice "$src" bl_presets
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

/*
 * Table 1 of the datasheet, copied by hand, indexed by the part's own EN rise
 * edge number. Entry 0 is unused padding so that the index reads as the edge.
 *
 * This is the whole point of the file: it is the hardware's answer, written
 * down independently of any expression in the firmware, so that a change to the
 * arithmetic has something to be wrong against. Microamps rather than
 * milliamps, to keep it in integers — every step is a multiple of 1.25mA.
 */
static const uint32_t table1_ua[BL_STEPS + 1] = {
    0,
    20000, 18750, 17500, 16250, 15000, 13750, 12500, 11250,
    10000,  8750,  7500,  6250,  5000,  3750,  2500,  1250,
};

/*
 * An AW9364, as far as the pulse count is concerned, and no further.
 *
 * It knows one thing: a rising edge advances the edge counter, and after 16 the
 * next one is 1 again. Figure 7 draws exactly that. Deliberately written in the
 * DATASHEET's numbering — edge 1 is 20mA and 16 is 1.25mA — and never in the
 * firmware's inverted one, so that a mistake in bl_edge_of() cannot cancel
 * itself out against a model that made the same mistake.
 */
typedef struct { int edge; } Aw9364;

/* The enabling edge is the first counted edge, and step 1 is maximum. */
static void chip_enable(Aw9364 *c) { c->edge = 1; }

static void chip_rise(Aw9364 *c) { c->edge = c->edge % BL_STEPS + 1; }

/*
 * Put the part on a firmware level directly, and read one back, by the relation
 * the datasheet states rather than by the function under test: level 16 is
 * edge 1.
 *
 * These two are textually identical to bl_edge_of(), and on their own that
 * would make the pulse-count section below a tautology — the same inversion
 * checked against itself. What stops it being one is table1_ua[] above, hand
 * transcribed from Table 1 in the DATASHEET's numbering and never touched by
 * the firmware: the ladder section checks bl_edge_of() against that table, and
 * the section below checks the CURRENT as well as the level, so an inverted
 * bl_edge_of() has to disagree with the table somewhere. Delete the table, or
 * stop comparing currents against it, and the 256 pairs stop saying anything.
 */
static void chip_park(Aw9364 *c, int level) { c->edge = BL_STEPS + 1 - level; }

static int chip_level(const Aw9364 *c) { return BL_STEPS + 1 - c->edge; }

static uint32_t chip_ua(const Aw9364 *c) { return table1_ua[c->edge]; }

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    printf("the ladder, against Table 1 of the datasheet\n");
    {
        int all = 1;
        for (int level = 1; level <= BL_STEPS; level++)
            if (bl_current_ua((uint8_t)level) != table1_ua[bl_edge_of((uint8_t)level)])
                all = 0;
        check(all, "every level draws what the part's own table says its step does");

        check(bl_current_ua(BL_STEPS) == 20000, "the brightest level is the 20mA step");
        check(bl_current_ua(1) == 1250, "the dimmest level is the 1.25mA step");
        check(bl_current_ua(0) == 0, "and off draws nothing");
        /* Out of range answers zero rather than indexing off the end of the
           ladder. The endpoint refuses these, so this is the second line. */
        check(bl_current_ua(BL_STEPS + 1) == 0, "a level past the top draws nothing");

        /* Linear, which is the fact the presets are spaced against: every step
           is the same 1.25mA and NOT a constant ratio. If this ever fails the
           part has been changed and the preset table's reasoning is void. */
        int even = 1;
        for (int level = 2; level <= BL_STEPS; level++)
            if (bl_current_ua((uint8_t)level) - bl_current_ua((uint8_t)(level - 1)) != BL_STEP_UA)
                even = 0;
        check(even, "the steps are evenly spaced in current, not in ratio");

        check(bl_total_ua(BL_STEPS) == 80000,
              "all four channels at full come to the 80mA behind the 85mA measured");
        check(bl_total_ua(0) == 0, "and to nothing when the part is off");
    }

    printf("the two numberings, which are inverses of each other\n");
    {
        int all = 1;
        for (int level = 1; level <= BL_STEPS; level++) {
            uint8_t edge = bl_edge_of((uint8_t)level);
            if (edge < 1 || edge > BL_STEPS) all = 0;
            if (bl_edge_of(edge) != level) all = 0;   /* its own inverse */
        }
        check(all, "every level maps to a step in range, and back to itself");
        check(bl_edge_of(BL_STEPS) == 1, "the brightest level is the part's first step");
        check(bl_edge_of(1) == BL_STEPS, "and the dimmest is its last");

        /* THE ASSUMPTION bl_drive() MAKES AND CANNOT VERIFY. Coming out of a
           shutdown it drives the line high, waits, and then sets its model to
           the brightest level without asking the part anything — because the
           part cannot be asked. The datasheet's step 1 is the enabling edge and
           step 1 is maximum, so that is right; if it were not, every level set
           after a blank would be wrong by however far off this is, silently and
           for as long as the device stayed up. */
        Aw9364 c;
        chip_enable(&c);
        check(chip_level(&c) == BL_STEPS,
              "the edge that enables the part leaves it at the brightest level");
        check(chip_ua(&c) == bl_current_ua(BL_STEPS),
              "drawing the full 20mA a channel, which is what a blank costs to undo");
    }

    printf("the pulse count, against a part that only counts rising edges\n");
    {
        /* The property that matters, over every pair there is: however many
           pulses the firmware says it takes, applying that many rising edges to
           a counter that wraps modulo 16 lands on the level that was asked for.
           256 pairs, so there is no sampling and no "representative case". */
        int wrong_level = 0, wrong_current = 0;
        for (int from = 1; from <= BL_STEPS; from++) {
            for (int to = 1; to <= BL_STEPS; to++) {
                Aw9364 c;
                chip_park(&c, from);
                uint8_t n = bl_pulses((uint8_t)from, (uint8_t)to);
                for (uint8_t i = 0; i < n; i++) chip_rise(&c);
                if (chip_level(&c) != to) wrong_level++;
                if (chip_ua(&c) != bl_current_ua((uint8_t)to)) wrong_current++;
            }
        }
        check(wrong_level == 0,
              "every one of the 256 level changes lands on the level asked for");
        check(wrong_current == 0,
              "and the part is then drawing what the firmware says it draws");
        /* No bound on the pulse count is asserted here. It would have to be
           "fewer than sixteen", which the modulo makes true by construction,
           and the round-trip property at the end of the next section already
           pins every pair to an exact count — a strictly stronger statement.
           A version that wasted a whole lap reddens there, not here. */
    }

    printf("the cases worth naming\n");
    {
        check(bl_pulses(11, 11) == 0,
              "asking for the level already set sends nothing at all");
        int quiet = 1;
        for (int level = 1; level <= BL_STEPS; level++)
            if (bl_pulses((uint8_t)level, (uint8_t)level) != 0) quiet = 0;
        check(quiet, "and that holds at every level, not just one");

        check(bl_pulses(BL_STEPS, BL_STEPS - 1) == 1,
              "one step dimmer is one pulse");
        check(bl_pulses(BL_STEPS, 1) == BL_STEPS - 1,
              "brightest to dimmest is fifteen, the long way down");

        /* THE WRAP. Getting brighter is not a negative count and not a special
           case — it is the rest of the lap. One step below the top is one pulse
           short of a full lap; one step above the bottom is a single pulse. */
        check(bl_pulses(1, BL_STEPS) == 1,
              "dimmest to brightest is ONE pulse, over the wrap");
        check(bl_pulses(8, 12) == 12,
              "and a dim level to a brighter one goes round rather than back");
        check(bl_pulses(BL_STEPS - 1, BL_STEPS) == BL_STEPS - 1,
              "one step below the top costs the whole lap but one");

        /* Round trip: going somewhere and coming back is always a whole lap,
           which is the arithmetic statement of "the counter only turns one
           way". A version that special-cased the brighter direction would give
           16 here for some pairs and something else for others. */
        int laps = 1;
        for (int a = 1; a <= BL_STEPS; a++) {
            for (int b = 1; b <= BL_STEPS; b++) {
                int there = bl_pulses((uint8_t)a, (uint8_t)b);
                int back = bl_pulses((uint8_t)b, (uint8_t)a);
                if (a != b && there + back != BL_STEPS) laps = 0;
                if (a == b && there + back != 0) laps = 0;
            }
        }
        check(laps, "there and back is always exactly one lap, or no pulses at all");
    }

    printf("what the endpoint will accept\n");
    {
        check(bl_level_valid(0), "0 is a level, and it means off");
        check(bl_level_valid(1), "so is the dimmest step");
        check(bl_level_valid(BL_STEPS), "so is the brightest");
        check(!bl_level_valid(BL_STEPS + 1), "one past the top is refused");
        check(!bl_level_valid(-1), "and so is a negative, which a JSON int can be");
        check(!bl_level_valid(255), "and so is a byte that overflowed somewhere");
    }

    printf("the preset table, whose shape the rest of the file assumes\n");
    {
        check(BL_PRESET_COUNT > 1, "there is more than one preset to cycle through");

        int ordered = 1, in_range = 1;
        for (int i = 0; i < BL_PRESET_COUNT; i++) {
            if (bl_preset_table[i].level < 1 || bl_preset_table[i].level > BL_STEPS)
                in_range = 0;
            if (i > 0 && bl_preset_table[i].level >= bl_preset_table[i - 1].level)
                ordered = 0;
        }
        check(in_range, "every preset is a level the part actually has");
        /* bl_preset_next() is written as "the first one dimmer than this", so a
           table out of order would silently skip presets rather than fail. */
        check(ordered, "and they are strictly descending, which the cycle relies on");
        check(bl_preset_table[0].level == BL_STEPS,
              "the first is full brightness, which is where the cycle wraps to");
        /* Off is the endpoint's to set, never the menu's: a click must not be
           able to blank the screen the menu is being read on. */
        int has_off = 0;
        for (int i = 0; i < BL_PRESET_COUNT; i++)
            if (bl_preset_table[i].level == 0) has_off = 1;
        check(!has_off, "and none of them is off");
    }

    printf("the click, which is the only way to set this with no network\n");
    {
        /* One click per preset gets back to where it started, having visited
           every one of them exactly once. That is the whole contract of the
           row, and it is checked by walking rather than by trusting the table. */
        uint8_t level = bl_preset_table[0].level;
        int seen[BL_PRESET_COUNT];
        memset(seen, 0, sizeof(seen));
        int stranger = 0;
        for (int step = 0; step < BL_PRESET_COUNT; step++) {
            int idx = -1;
            for (int i = 0; i < BL_PRESET_COUNT; i++)
                if (bl_preset_table[i].level == level) idx = i;
            if (idx < 0) stranger = 1; else seen[idx]++;
            level = bl_preset_next(level);
        }
        check(!stranger, "every click lands on a preset");
        check(level == bl_preset_table[0].level,
              "and a full cycle of clicks comes back to full brightness");
        int once = 1;
        for (int i = 0; i < BL_PRESET_COUNT; i++) if (seen[i] != 1) once = 0;
        check(once, "having passed through each preset exactly once");

        /* Levels the menu can never produce but the endpoint can. The row still
           has to do something sensible from them, and "join the cycle at the
           next one down" is that. */
        check(bl_preset_next(13) == 11,
              "a level between two presets goes to the next one down");
        check(bl_preset_next(2) == BL_STEPS,
              "a level below every preset wraps to full");
        check(bl_preset_next(0) == BL_STEPS,
              "and a click on a screen the endpoint blanked turns it back on");
        /* Nothing may ever cycle to off — see the table check above. */
        int never_off = 1;
        for (int level_in = 0; level_in <= BL_STEPS; level_in++)
            if (bl_preset_next((uint8_t)level_in) == 0) never_off = 0;
        check(never_off, "and no level whatsoever clicks through to a dark screen");
    }

    printf("the menu row's label, which is the only new string on the device\n");
    {
        /* The buffer the DEVICE uses, not a roomier one: a label that only fits
           because the test gave itself more space than ui.h has is a label that
           is cut short on the panel and whole here. */
        char s[BL_LABEL_MAX];
        /* Read out of the table rather than spelled out here. The table is four
           numbers and four words that the file it lives in invites editing, and
           a check naming one of those words fails on the edit rather than on a
           mistake — which is the opposite of what it is for. */
        int named = 1;
        for (int i = 0; i < BL_PRESET_COUNT; i++) {
            bl_level_label(bl_preset_table[i].level, s, sizeof(s));
            if (strcmp(s, bl_preset_table[i].name) != 0) named = 0;
        }
        check(named, "every preset reads as its own name, whatever the table says they are");
        bl_level_label(0, s, sizeof(s));
        check(strcmp(s, "off") == 0, "off says so");
        /* Never rounded into the nearest word: a level set for an experiment has
           to be readable off the panel as the level it is. Which levels have no
           word is the table's business, so this asks the table rather than
           naming one — and it covers all sixteen instead of the two a hand-
           picked pair would. */
        int unnamed = 0, spelled = 1;
        for (int level = 1; level <= BL_STEPS; level++) {
            if (bl_preset_name((uint8_t)level) != NULL) continue;
            unnamed++;
            char want[BL_LABEL_MAX];
            snprintf(want, sizeof(want), "step %d", level);
            bl_level_label((uint8_t)level, s, sizeof(s));
            if (strcmp(s, want) != 0) spelled = 0;
        }
        check(unnamed > 0, "there are levels the table has no word for, which is the point of sixteen");
        check(spelled, "and every one of them reads as its step number");

        /* The width argument at the call site in ui.h counts these characters.
           ui.h writes "Backlight " in front of them, so seven here is the row
           "Backlight step 16", which with the marker measures 210px of font 4
           against the 296px ui_draw_row() has. A longer string runs off the
           panel, so the length is pinned rather than left as a comment. */
        size_t longest = 0;
        for (int level = 0; level <= BL_STEPS; level++) {
            bl_level_label((uint8_t)level, s, sizeof(s));
            if (strlen(s) > longest) longest = strlen(s);
        }
        check(longest == 7,
              "the longest label is 7 characters: the 17 of \"Backlight step 16\" "
              "that ui.h measured, less the 10 of \"Backlight \"");
        /* And the buffer every caller sizes from that pin actually holds it.
           Tied together here so that a fifth preset with a longer name than
           "step 16" fails this rather than being cut short on the panel. */
        check(longest < BL_LABEL_MAX,
              "and the buffer the call sites take from this file holds it whole");
        /* Out of range prints whole too. The endpoint refuses these, so this is
           the second line — but a truncated label is a worse way to find out. */
        bl_level_label(255, s, sizeof(s));
        check(strcmp(s, "step 255") == 0 && strlen(s) < BL_LABEL_MAX,
              "a level off the ladder entirely still prints whole");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test"
