#!/usr/bin/env bash
#
# Host-side regression test for the target-URL parser in src/skills/voice.cpp.
#
# Why this exists: the parser is the one piece of that skill which is pure
# computation over a string, and it is also the piece whose mistakes are least
# visible on hardware. Everything else in voice.cpp needs a radio, a receiver
# and a microphone to exercise; a URL split the wrong way just quietly posts to
# the wrong place, or to port 0, or with a request line that starts with "?".
#
# What this DOES NOT cover, said plainly rather than papered over: the uploader
# task, the HTTP client, the buffer hold and every failure counter around them
# cannot be unit tested here. They need FreeRTOS, lwIP and a device. No coverage
# is claimed for them, and the shape of the tests below should not be read as
# implying any.
#
# The function is sliced straight out of the shipping source between its
# `host-test:begin url` and `host-test:end` markers, the same way
# tools/test_wav_header.sh and tools/test_wav_parse.sh slice theirs, so this
# runs the real implementation rather than a copy that could drift.
#
# Usage: tools/test_voice_url.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/voice.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_voice_url.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

PRELUDE
    slice "$src" url
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

/* One accepted URL, checked field by field. Passing NULL for a field skips it,
   so a case can assert only what it is about. */
static void ok_case(const char *url, const char *host, unsigned port,
                    const char *path) {
    VoiceUrl u;
    const char *err = "(not set)";
    if (!voice_url_parse(url, u, &err)) {
        printf("  FAIL: %s should parse (refused: %s)\n", url, err);
        failures++;
        return;
    }
    int bad = 0;
    if (host && strcmp(u.host, host) != 0) bad = 1;
    if (port && u.port != port) bad = 1;
    if (path && strcmp(u.path, path) != 0) bad = 1;
    if (bad) {
        printf("  FAIL: %s -> host=%s port=%u path=%s (want host=%s port=%u path=%s)\n",
               url, u.host, (unsigned)u.port, u.path,
               host ? host : "-", port, path ? path : "-");
        failures++;
    } else {
        printf("  ok:   %s -> %s:%u%s\n", url, u.host, (unsigned)u.port, u.path);
    }
}

/* One refused URL. The reason matters as much as the refusal: a parser that
   says "url must start with http://" for a bad port sends whoever is holding
   the curl command in the wrong direction. */
static void no_case(const char *url, const char *why) {
    VoiceUrl u;
    const char *err = NULL;
    if (voice_url_parse(url, u, &err)) {
        printf("  FAIL: %s should be refused (%s)\n", url, why);
        failures++;
        return;
    }
    if (!err || !err[0]) {
        printf("  FAIL: %s was refused with no reason\n", url);
        failures++;
        return;
    }
    printf("  ok:   %s refused — %s\n", url, err);
}

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    printf("the ordinary shapes\n");
    {
        ok_case("http://seed-rx.local/takes", "seed-rx.local", 80, "/takes");
        ok_case("http://192.168.1.50:9000/takes", "192.168.1.50", 9000, "/takes");
        ok_case("http://example.com/a/b/c.wav", "example.com", 80, "/a/b/c.wav");
    }

    printf("the empty path, which is where an off-by-one lives\n");
    {
        /* No path at all has to become "/", not "". A request target that is
           the empty string is not a request. */
        ok_case("http://host", "host", 80, "/");
        ok_case("http://host:8080", "host", 8080, "/");
        /* A trailing slash is a path of exactly "/" and must survive as one. */
        ok_case("http://host/", "host", 80, "/");
        /* A query with no path: the slash has to be synthesised in front of it
           or the request line starts with '?'. */
        ok_case("http://host?node=a1b2", "host", 80, "/?node=a1b2");
        ok_case("http://host/takes?node=a1b2", "host", 80, "/takes?node=a1b2");
    }

    printf("a bare IP is just a host, and mDNS names are ordinary hosts too\n");
    {
        ok_case("http://10.0.0.1", "10.0.0.1", 80, "/");
        ok_case("http://10.0.0.1:1/x", "10.0.0.1", 1, "/x");
        ok_case("http://10.0.0.1:65535/x", "10.0.0.1", 65535, "/x");
        ok_case("http://seed.local", "seed.local", 80, "/");
        ok_case("http://my_host-2.local/p", "my_host-2.local", 80, "/p");
    }

    printf("the scheme\n");
    {
        /* Schemes are case-insensitive per RFC 3986 and somebody will paste a
           capitalised one out of a browser bar. */
        ok_case("HTTP://host/p", "host", 80, "/p");
        ok_case("HtTp://host/p", "host", 80, "/p");
        no_case("host/takes", "no scheme at all");
        no_case("192.168.1.50:9000/takes", "a host:port with no scheme");
        no_case("//host/takes", "a protocol-relative url");
        no_case("ftp://host/takes", "a scheme we do not speak");
        /* https is refused with its own message: it is a reasonable thing to
           try, and the generic answer would read as a typo. */
        no_case("https://host/takes", "https, which needs a certificate store");
        no_case("HTTPS://host/takes", "https, capitalised");
        no_case("http:/host", "one slash short");
        no_case("http://", "the scheme and nothing else");
    }

    printf("a missing host\n");
    {
        no_case("http:///takes", "no host before the path");
        no_case("http://:9000/takes", "a port with no host");
        no_case("http://?x=1", "a query with no host");
    }

    printf("ports, where the range checks are\n");
    {
        no_case("http://host:/takes", "a colon with no port after it");
        no_case("http://host:0/takes", "port 0");
        no_case("http://host:65536/x", "one past the top of the range");
        no_case("http://host:99999999999/x", "a port that would overflow");
        no_case("http://host:80a/x", "a port with a letter in it");
        no_case("http://host:8:9/x", "two colons in the authority");
    }

    printf("things that must not reach a request line\n");
    {
        /* This is the one group that is not tidiness. A CR or an LF in a path
           is request splitting; refusing everything outside printable ASCII
           closes it without having to reason about which control character
           matters. */
        no_case("http://host/a b", "an embedded space");
        no_case("http://host/a\rb", "an embedded carriage return");
        no_case("http://host/a\nb", "an embedded newline");
        no_case("http://host/a\tb", "an embedded tab");
        no_case("http://ho st/x", "a space in the host");
        no_case("http://host/\x01", "a control character");
        no_case("http://host/caf\xc3\xa9", "a non-ASCII byte");
        no_case("http://host/x#frag", "a fragment, which a server never sees");
        no_case("http://user:pw@host/x", "userinfo, which we do not send");
        no_case("http://[::1]:8080/x", "an ipv6 literal");
        no_case("http://ho|st/x", "a pipe in the host");
    }

    printf("absurd lengths, at the boundary rather than near it\n");
    {
        char buf[512];

        /* Exactly at the whole-url cap and one over it. The host and the path
           both stay inside their own caps here, so this isolates the url one:
           7 scheme + 63 host + 1 slash + 56 path is 127. */
        {
            int n = 0;
            n += snprintf(buf + n, sizeof(buf) - n, "http://");
            memset(buf + n, 'h', VOICE_HOST_LEN - 1);
            n += VOICE_HOST_LEN - 1;
            buf[n++] = '/';
            int fill = VOICE_URL_LEN - 1 - n;
            memset(buf + n, 'p', (size_t)fill);
            buf[n + fill] = '\0';
            ok_case(buf, NULL, 80, NULL);

            buf[n + fill] = 'p';
            buf[n + fill + 1] = '\0';
            no_case(buf, "one byte over the url cap");
        }

        /* A host at the cap, and one over. */
        strcpy(buf, "http://");
        memset(buf + 7, 'h', VOICE_HOST_LEN - 1);
        buf[7 + VOICE_HOST_LEN - 1] = '\0';
        ok_case(buf, NULL, 80, "/");

        strcpy(buf, "http://");
        memset(buf + 7, 'h', VOICE_HOST_LEN);
        buf[7 + VOICE_HOST_LEN] = '\0';
        no_case(buf, "one byte over the host cap");

        /* A path at the cap, and one over. The synthesised leading slash counts
           against it, which is exactly the kind of thing to get wrong once. */
        strcpy(buf, "http://h");
        buf[8] = '/';
        memset(buf + 9, 'p', VOICE_PATH_LEN - 2);
        buf[9 + VOICE_PATH_LEN - 2] = '\0';
        ok_case(buf, "h", 80, NULL);

        strcpy(buf, "http://h");
        buf[8] = '/';
        memset(buf + 9, 'p', VOICE_PATH_LEN - 1);
        buf[9 + VOICE_PATH_LEN - 1] = '\0';
        no_case(buf, "one byte over the path cap");
    }

    printf("the degenerate inputs\n");
    {
        VoiceUrl u;
        const char *err = NULL;
        check(!voice_url_parse(NULL, u, &err), "a null url is refused");
        check(err != NULL, "  ...with a reason");
        no_case("", "an empty string");

        /* Every refusal must leave the fields cleared rather than half-filled,
           because the caller keeps its previous target on a failure and a
           partially overwritten struct would be a target nobody chose. */
        err = NULL;
        voice_url_parse("http://host:0/x", u, &err);
        check(u.host[0] == '\0' && u.path[0] == '\0' && u.port == 0,
              "a refused url leaves no fields behind");

        /* err is optional: nothing must dereference a null out-parameter. */
        check(voice_url_parse("http://host/x", u, NULL),
              "a null err pointer is not dereferenced on success");
        check(!voice_url_parse("nonsense", u, NULL),
              "a null err pointer is not dereferenced on failure");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test"
