#!/usr/bin/env bash
#
# Host-side regression test for the BQ25896 charger logic in
# src/skills/charger.cpp.
#
# Why this exists, and it is not the usual reason: REG06[7:2] sets the voltage
# this board drives into a lithium cell. The register accepts code 48, which is
# 4.608 V — roughly 400 mV of overcharge on a 3.7 V cell, which means plating,
# venting and fire. bq25896_write_allowed() refuses it. A guard is only a guard
# if something proves it refuses, and "the code looks right" has never been that
# proof: a `>=` where a `>` belongs does not fail a build, does not throw, and
# does not look broken.
#
# The firmware writes REG06 to 4.208 V, the value the vendor ships, so the
# bound is travelled from below rather than untravelled — but it is still the
# case that nothing in normal operation goes anywhere near the ceiling, which is
# exactly the condition under which a bound rots unnoticed. It is tested harder
# than anything else here for that reason: the guard exists for the day somebody
# edits that line in the configuration table, and this file is what will still
# be holding it then.
#
# The bound is asked on BOTH sides, and the read side is the half that a write
# guard cannot cover. This charger is powered by the cell, its registers survive
# a reflash of the ESP32, and on this specific device REG00 holds a value only a
# host write produces — so what the part is FOUND holding is not a datasheet
# fact. bq25896_vreg_in_bounds() judges a reading against the same ceiling, and
# charger_config_is_live() is what makes an out-of-bounds reading unable to
# coexist with `configured: true`. Both are checked below.
#
# So the checks below are written to FAIL if the guard is weakened, and every
# one of them was verified by weakening it. The specific mutations, and what
# each one turns red, are recorded next to the checks they belong to.
#
# The other half is arithmetic. VREG, ICHG, ITERM, IPRECHG and IINLIM are each
# a base and a step out of the datasheet's register tables (SLUSC76C, section
# 9.4), and every one of them is a place where an off-by-one offset produces a
# number that is wrong by exactly one step and looks entirely plausible. 256 mA
# against 128 mA is the whole bug this commit fixes, and it is one step.
#
# WHAT THIS DOES NOT COVER, said plainly rather than papered over: the I2C
# transaction. bq25896_write8() and bq25896_read8() are calls into Arduino's
# TwoWire and their failure modes are a NAK, a missing pull-up and a second task
# on the bus. None of that has a host equivalent, nothing below simulates it,
# and the only proof that half of it works is a reading taken off the device.
#
# Nor does it cover charger_configure(), charger_read() or charger_refresh()
# themselves — the loops that walk the table, issue the writes and decide when to
# re-issue them. They sit above the slice markers, on the far side of Wire and
# portMUX, and reaching them from the host would mean rearranging the shipping
# source to suit the test. What IS covered is everything they call: the table
# they walk, charger_verify_mask() and charger_live_readback() which together
# decide whether the part is still holding it, and charger_config_is_live()
# which decides what the endpoint claims. Each was split out of the I2C paths
# precisely so that the part which can be wrong without any hardware present is
# the part a host can hold to account.
#
# The logic is sliced straight out of the shipping source between its
# `host-test:begin charger` and `host-test:end` markers, the same way
# tools/test_battery.sh slices the gauge decode out of skills/battery.cpp, so
# this runs the real implementation rather than a copy that could drift.
#
# Usage: tools/test_charger.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/charger.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_charger.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

PRELUDE
    slice "$src" charger
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

static void eq_int(int got, int want, const char *what) {
    if (got != want) {
        printf("  FAIL: %s — got %d, wanted %d\n", what, got, want);
        failures++;
    } else {
        printf("  ok:   %s = %d\n", what, got);
    }
}

static void eq_str(const char *got, const char *want, const char *what) {
    if (strcmp(got, want) != 0) {
        printf("  FAIL: %s — got \"%s\", wanted \"%s\"\n", what, got, want);
        failures++;
    } else {
        printf("  ok:   %s = \"%s\"\n", what, got);
    }
}

/* The numbers the datasheet gives, transcribed here as literals so that the
   source is the thing under test. Comparing a decoder against the constant it
   is built from would pass whatever that constant was changed to. */
#define VREG_MAX_SAFE_MV   4208   /* code 23, the POR: our ceiling            */
#define VREG_DANGER_MV     4608   /* code 48, what the register itself allows */
#define ICHG_MAX_SAFE_MA   576    /* code 9: the vendor caps the board at 600 */

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    printf("VREG: the charge voltage arithmetic (REG06[7:2], 3.840 V + 16 mV per code)\n");
    {
        /* The four values in this ticket, by their register bytes. */
        eq_int(bq25896_vreg_mv(0x5A), 4192, "0x5A is 4.192 V — what we write");
        eq_int(bq25896_vreg_mv(0x5E), 4208, "0x5E is 4.208 V — the power-on default");
        eq_int(bq25896_vreg_mv(0xC0), 4608, "0xC0 is 4.608 V — what the register allows");
        eq_int(bq25896_vreg_mv(0x00), 3840, "0x00 is the 3.840 V offset itself");

        /* The low two bits are BATLOWV and VRECHG and belong to no voltage. A
           decoder that let them through would move the answer by a whole step
           on half the values it was given. */
        eq_int(bq25896_vreg_mv(0x5B), 4192, "BATLOWV and VRECHG do not move the voltage");
        eq_int(bq25896_vreg_mv(0x58), 4192, "and neither does clearing them");

        /* One step is 16 mV, everywhere, monotonically. */
        eq_int(bq25896_vreg_mv(0x5A) - bq25896_vreg_mv(0x56), 16, "one code is one 16 mV step");
        int prev = -1, monotonic = 1;
        for (int v = 0; v < 256; v += 4) {
            int mv = bq25896_vreg_mv((uint8_t)v);
            if (mv <= prev) monotonic = 0;
            prev = mv;
        }
        check(monotonic, "the voltage rises with the code across all 64 of them");

        /* The field is six bits and the part regulates to at most 4.608 V, so
           codes 49 to 63 decode ABOVE anything the silicon will do. The decoder
           does not clamp them, deliberately: its job is to say what the register
           holds, and the ceiling is bq25896_vreg_in_bounds()'s job. Pinned here
           so that "clamp it" is a decision somebody has to turn a check red to
           make, rather than a tidy-up. Unreachable in practice — the guard
           refuses every one of these on the way in. */
        eq_int(bq25896_vreg_mv(0xC0), 4608, "code 48 is 4.608 V, the part's own maximum");
        eq_int(bq25896_vreg_mv(0xC4), 4624, "code 49 decodes above it, unclamped by design");
        eq_int(bq25896_vreg_mv(0xFF), 4848, "and code 63, the top of the field, likewise");
        check(!bq25896_write_allowed(0x06, 0xC4) && !bq25896_write_allowed(0x06, 0xFF),
              "neither is reachable: the guard refuses both");
    }

    printf("the charge voltage bound, asked of a READING rather than of a write\n");
    {
        /* A write guard bounds what this firmware sends. It says nothing about
           what the part is found holding, and this device is the proof that the
           two are different questions: REG00 came to us at 0x3F where the
           power-on value is 0x48, which only a host write produces, and the
           charger keeps its registers across a reflash because it runs off the
           cell. A REG06 left at code 30 by other software is 4.32 V into a 3.7 V
           cell, forever, with the watchdog disabled and nothing to revert it.
           Verified red by replacing the body of bq25896_vreg_in_bounds() with
           `return true`, which turns every check in this block red, and by
           raising BQ25896_VREG_CODE_MAX from 23 to 48, which turns the first
           three red. */
        check(bq25896_vreg_in_bounds(0x5E),
              "REG06 0x5E — 4.208 V, what we write — reads as in bounds");
        check(!bq25896_vreg_in_bounds(0x78),
              "REG06 0x78 — code 30, 4.32 V, what another host could leave — is OUT of bounds");
        check(!bq25896_vreg_in_bounds(0xC0),
              "REG06 0xC0 — 4.608 V — is OUT of bounds");
        check(bq25896_vreg_in_bounds(0x5D),
              "and the low two bits, BATLOWV and VRECHG, do not move the answer");

        /* The read bound and the write bound are the same ceiling, and that is
           asserted rather than assumed: two copies of a constant is two places
           for it to be raised singly. Verified red by giving either one a
           different limit. */
        int disagree = -1;
        for (int v = 0; v < 256 && disagree < 0; v++) {
            if (bq25896_vreg_in_bounds((uint8_t)v) != (bool)bq25896_write_allowed(0x06, (uint8_t)v))
                disagree = v;
        }
        if (disagree >= 0) {
            printf("  FAIL: REG06 0x%02X is judged differently by the read bound and the write guard\n",
                   disagree);
            failures++;
        } else {
            printf("  ok:   the read bound and the write guard agree on all 256 REG06 bytes\n");
        }

        /* And the bound is the safe one, stated in volts rather than in codes. */
        int worst = 0;
        for (int v = 0; v < 256; v++)
            if (bq25896_vreg_in_bounds((uint8_t)v) && bq25896_vreg_mv((uint8_t)v) > worst)
                worst = bq25896_vreg_mv((uint8_t)v);
        eq_int(worst, VREG_MAX_SAFE_MV,
               "the highest charge voltage any in-bounds REG06 reading can mean, in mV");
    }

    printf("ICHG, ITERM, IPRECHG: the current arithmetic\n");
    {
        /* REG04[6:0], offset 0 mA, step 64 mA. */
        eq_int(bq25896_ichg_ma(0x08), 512,  "REG04 0x08 is 512 mA — what we write");
        eq_int(bq25896_ichg_ma(0x20), 2048, "REG04 0x20 is 2048 mA — the power-on default");
        eq_int(bq25896_ichg_ma(0x2F), 3008, "REG04 0x2F is 3008 mA — the part's maximum");
        eq_int(bq25896_ichg_ma(0x00), 0,    "REG04 0x00 is 0 mA, which disables charging");
        /* Bit 7 is EN_PUMPX and is not part of the number. */
        eq_int(bq25896_ichg_ma(0x88), 512,  "EN_PUMPX is masked out of the current");

        /* REG05[3:0], offset 64 mA, step 64 mA. This is the defect and the fix,
           and the two are one step apart. */
        eq_int(bq25896_iterm_ma(0x13), 256, "REG05 0x13 terminates at 256 mA — the defect");
        eq_int(bq25896_iterm_ma(0x11), 128, "REG05 0x11 terminates at 128 mA — the fix");
        eq_int(bq25896_iterm_ma(0x10), 64,  "the offset is 64 mA, not 0");
        eq_int(bq25896_iterm_ma(0x1F), 1024, "and the field tops out at 1024 mA");

        /* 128 mA on a 1300 mAh cell is C/10; 256 mA is C/5. The ratio is what
           the whole argument rests on, so it is asserted rather than assumed. */
        eq_int(1300 / bq25896_iterm_ma(0x11), 10, "128 mA against 1300 mAh is C/10");
        eq_int(1300 / bq25896_iterm_ma(0x13), 5,  "256 mA against 1300 mAh is C/5");

        /* REG05[7:4], same offset and step, and NOT the same nibble. Reading
           the wrong nibble is the mistake this pair exists to catch: 0x11 has
           the same value in both, so the values here deliberately differ. */
        eq_int(bq25896_iprechg_ma(0x11), 128, "REG05 0x11 precharges at 128 mA");
        eq_int(bq25896_iprechg_ma(0x13), 128, "and 0x13 does too — the default was never wrong");
        eq_int(bq25896_iprechg_ma(0x41), 320, "the high nibble is the precharge current");
        eq_int(bq25896_iterm_ma(0x41),   128, "and the low nibble is the termination current");
        check(bq25896_iprechg_ma(0x41) != bq25896_iterm_ma(0x41),
              "the two nibbles are not the same field");
    }

    printf("IINLIM: the input current limit (REG00[5:0] and REG13[5:0], 100 mA + 50 mA per code)\n");
    {
        eq_int(bq25896_iinlim_ma(0x08), 500,  "code 8 is the 500 mA default that starved the cell");
        eq_int(bq25896_iinlim_ma(0x00), 100,  "code 0 is the 100 mA offset itself");
        eq_int(bq25896_iinlim_ma(0x3F), 3250, "code 63 is 3.25 A, the top of the range");
        /* REG00[7] is EN_HIZ and REG00[6] is EN_ILIM; REG13[7:6] are the two
           DPM status bits. Neither pair is part of the current. */
        eq_int(bq25896_iinlim_ma(0xC8), 500,  "the two bits above the field are not part of it");
    }

    printf("THE GUARD: what may be written to the charger\n");
    {
        /* The three registers this firmware writes, at the values it writes. */
        check(bq25896_write_allowed(0x07, 0x8D), "REG07 0x8D is allowed");
        check(bq25896_write_allowed(0x04, 0x08), "REG04 0x08 is allowed");
        check(bq25896_write_allowed(0x05, 0x11), "REG05 0x11 is allowed");

        /* ---- The overcharge ceiling. This is the check the commit is for. ----
         *
         * Nothing in the firmware writes REG06 — it is left at its 4.208 V
         * power-on default. The bound is here for whoever adds that line
         * later, and it is checked as if they already had.
         *
         * Verified red by deleting the REG06 case from bq25896_write_allowed()
         * so it falls through to `return true` alongside REG05 and REG07, and
         * again by raising BQ25896_VREG_CODE_MAX from 23 to 48. Each mutation
         * turns the four checks below red; restoring the guard turns them green.
         */
        check(bq25896_write_allowed(0x06, 0x5A),
              "REG06 0x5A — 4.192 V, the margin we are declining — would be allowed");
        check(!bq25896_write_allowed(0x06, 0xC0),
              "REG06 0xC0 — 4.608 V, an overcharge — is REFUSED");
        check(!bq25896_write_allowed(0x06, 0x60),
              "REG06 0x60 — 4.224 V, one step over the ceiling — is REFUSED");
        check(bq25896_write_allowed(0x06, 0x5E),
              "REG06 0x5E — 4.208 V, the power-on default — is the last value allowed");
        check(!bq25896_write_allowed(0x06, 0xFF),
              "REG06 0xFF — every bit set — is REFUSED");

        /* The ceiling as a property rather than as four examples: across all
           256 bytes, a REG06 value is accepted if and only if it decodes to
           4.208 V or less, and NOTHING accepted can overcharge the cell. This
           is the check that cannot be satisfied by special-casing. */
        int accepted = 0, worst_accepted_mv = 0, wrong = 0;
        for (int v = 0; v < 256; v++) {
            int allowed = bq25896_write_allowed(0x06, (uint8_t)v);
            int mv = bq25896_vreg_mv((uint8_t)v);
            if (allowed != (mv <= VREG_MAX_SAFE_MV)) wrong = 1;
            if (allowed) {
                accepted++;
                if (mv > worst_accepted_mv) worst_accepted_mv = mv;
            }
        }
        check(!wrong, "over all 256 REG06 bytes, accepted is exactly \"decodes to 4.208 V or less\"");
        eq_int(worst_accepted_mv, VREG_MAX_SAFE_MV,
               "the highest voltage any accepted REG06 write can set, in mV");
        eq_int(accepted, 96, "and 96 of the 256 bytes are accepted");
        check(worst_accepted_mv < VREG_DANGER_MV,
              "which is below the 4.608 V the register itself would accept");

        /* ---- The charge current ceiling ----
         *
         * Verified red by raising BQ25896_ICHG_CODE_MAX from 9 to 47, which
         * turns the first two checks and the property check below red.
         */
        check(!bq25896_write_allowed(0x04, 0x2F),
              "REG04 0x2F — 3008 mA, 2.3 C on this cell — is REFUSED");
        check(!bq25896_write_allowed(0x04, 0x0A),
              "REG04 0x0A — 640 mA, over the 600 mA the board is rated for — is REFUSED");
        check(bq25896_write_allowed(0x04, 0x09),
              "REG04 0x09 — 576 mA — is the last value allowed");

        int ichg_wrong = 0, worst_ichg_ma = 0;
        for (int v = 0; v < 256; v++) {
            int allowed = bq25896_write_allowed(0x04, (uint8_t)v);
            int ma = bq25896_ichg_ma((uint8_t)v);
            if (allowed != (ma <= ICHG_MAX_SAFE_MA)) ichg_wrong = 1;
            if (allowed && ma > worst_ichg_ma) worst_ichg_ma = ma;
        }
        check(!ichg_wrong, "over all 256 REG04 bytes, accepted is exactly \"576 mA or less\"");
        eq_int(worst_ichg_ma, ICHG_MAX_SAFE_MA,
               "the highest current any accepted REG04 write can set, in mA");

        /* ---- The second overcharge path: REG08 ----
         *
         * VREG_ACTUAL = VREG + min(ICHRG * BAT_COMP, VCLAMP), and VCLAMP
         * reaches 224 mV, so a nonzero REG08 regulates near 4.43 V with a
         * perfectly correct REG06. An audit of the VREG write alone walks
         * straight past it. The guard refuses REG08 as a REGISTER, so there is
         * no combination of its bits to get wrong.
         *
         * Verified red by adding `case 0x08: return true;` to the switch.
         */
        int reg08_leak = 0;
        for (int v = 0; v < 256; v++)
            if (bq25896_write_allowed(0x08, (uint8_t)v)) reg08_leak = 1;
        check(!reg08_leak,
              "REG08 IRCOMP is REFUSED at every one of its 256 values — no BAT_COMP, no VCLAMP");

        /* ---- The registers that would make the device look dead, or a source ----
         *
         * Verified red by changing the switch's `default: return false` to
         * `return true`, which turns every check in this block red at once.
         */
        check(!bq25896_write_allowed(0x09, 0x20),
              "REG09 BATFET_DIS — ship mode, needs USB to recover — is REFUSED");
        check(!bq25896_write_allowed(0x00, 0x80),
              "REG00 EN_HIZ — input disconnected — is REFUSED");
        check(!bq25896_write_allowed(0x03, 0x20),
              "REG03 OTG_CONFIG — 5 V boost driving VBUS outward — is REFUSED");
        check(!bq25896_write_allowed(0x02, 0xFF),
              "REG02 ADC control is REFUSED: this firmware does not use the ADC");
        check(!bq25896_write_allowed(0x14, 0x80),
              "REG14 REG_RST is REFUSED: nothing here resets the part");

        /* Nothing outside the four is writable, at any value. The four are
           named as literals rather than as the macros so that renaming a macro
           cannot quietly widen this. */
        int stray = -1;
        for (int r = 0; r < 256 && stray < 0; r++) {
            if (r == 0x04 || r == 0x05 || r == 0x06 || r == 0x07) continue;
            for (int v = 0; v < 256; v++)
                if (bq25896_write_allowed((uint8_t)r, (uint8_t)v)) { stray = r; break; }
        }
        if (stray >= 0) {
            printf("  FAIL: register 0x%02X is writable and should not be\n", stray);
            failures++;
        } else {
            printf("  ok:   only REG04-REG07 are writable, over all 65536 register/value pairs\n");
        }

        /* REG05 and REG07 take any value, and that is a decision rather than an
           oversight: no bit in either raises the cell voltage or the charge
           current. Asserted so that narrowing them later is a deliberate act. */
        int r05 = 0, r07 = 0;
        for (int v = 0; v < 256; v++) {
            if (!bq25896_write_allowed(0x05, (uint8_t)v)) r05 = 1;
            if (!bq25896_write_allowed(0x07, (uint8_t)v)) r07 = 1;
        }
        check(!r05, "REG05 is accepted at every value: both its fields are current thresholds");
        check(!r07, "REG07 is accepted at every value: termination, watchdog and timers only");
    }

    printf("the configuration table, which is the shipping one\n");
    {
        eq_int(CHARGER_CONFIG_COUNT, 4, "four registers are written at boot");

        /* THE ORDER IS A CORRECTNESS PROPERTY. REG07 closes the 40 s watchdog
           window, and the writes carrying the fix must land inside it. It
           matters twice over now that the table is also re-issued on drift,
           where the reason for writing may well be a watchdog that expired and
           re-armed. Verified red by moving the REG07 entry to the end. */
        eq_int(charger_config[0].reg, 0x07,
               "REG07 is written FIRST, closing the watchdog before the rest land");
        eq_int(charger_config[1].reg, 0x04, "then REG04");
        eq_int(charger_config[2].reg, 0x05, "then REG05");
        eq_int(charger_config[3].reg, 0x06, "then REG06");

        /* REG06 IS WRITTEN, and it did not use to be. The check that used to
           stand here asserted its ABSENCE, on the argument that 4.208 V is what
           the part powers up holding so the way to arrive there is to touch
           nothing. It was a tripwire for exactly this edit and it did its job:
           the premise is false on this device — see the header — and the entry
           went in deliberately, with the check rewritten to pin the value
           rather than the absence.

           What must not change silently is the VALUE. 0x5E is 4.208 V, the
           vendor's number, and a byte higher here is a higher voltage into a
           lithium cell. Verified red by changing the entry to 0x78 (4.32 V),
           which turns the value check and the bound check below red together. */
        int reg06_entry = -1;
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++)
            if (charger_config[i].reg == 0x06) reg06_entry = i;
        check(reg06_entry >= 0, "REG06, the charge voltage, IS in the table — written, not trusted");
        eq_int(charger_config[reg06_entry].val, 0x5E, "and it is written 0x5E");
        eq_int(bq25896_vreg_mv(charger_config[reg06_entry].val), 4208,
               "which regulates the cell at, in mV");
        check(bq25896_vreg_in_bounds(charger_config[reg06_entry].val),
              "and the value the table ships is within the read-side bound too");

        /* The values, by what they mean rather than by their bytes. */
        eq_int(charger_config[0].val, 0x8D, "REG07 is written 0x8D");
        eq_int(charger_config[1].val, 0x08, "REG04 is written 0x08");
        eq_int(charger_config[2].val, 0x11, "REG05 is written 0x11");

        eq_int(bq25896_ichg_ma(charger_config[1].val), 512,
               "which charges the cell at, in mA");
        eq_int(bq25896_iterm_ma(charger_config[2].val), 128,
               "and terminates at, in mA");
        eq_int(bq25896_iprechg_ma(charger_config[2].val), 128,
               "with a precharge current of, in mA");

        /* REG07 0x8D, field by field: EN_TERM on, watchdog off, safety timer on
           at 12 h. The watchdog bits are the ones that matter — 01 would be the
           40 s default, and 60 s of battery tick is longer than 40. */
        check((charger_config[0].val & 0x80) != 0, "REG07 leaves termination ENABLED");
        eq_int((charger_config[0].val >> 4) & 0x3, 0,
               "REG07 sets the watchdog to 00, DISABLED, rather than to 01 = 40 s");
        check((charger_config[0].val & 0x08) != 0, "REG07 leaves the safety timer ENABLED");
        eq_int((charger_config[0].val >> 1) & 0x3, 2, "REG07 sets the safety timer to 10 = 12 h");

        /* Every entry passes the guard. This is what makes a wrong value edited
           into the table a caught bug rather than a shipped one — the write
           path calls the guard, so a table the guard refuses simply never
           reaches the wire. Verified red by adding a REG06 0xC0 entry. */
        int refused = -1;
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++)
            if (!bq25896_write_allowed(charger_config[i].reg, charger_config[i].val)) refused = i;
        if (refused >= 0) {
            printf("  FAIL: charger_config[%d] (%s) would be refused by the guard\n",
                   refused, charger_config[refused].name);
            failures++;
        } else {
            printf("  ok:   every entry in the shipping table passes the guard\n");
        }

        /* No register written twice: the later write would silently win and the
           table would document something the part never saw. */
        int dupe = 0;
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++)
            for (int j = i + 1; j < CHARGER_CONFIG_COUNT; j++)
                if (charger_config[i].reg == charger_config[j].reg) dupe = 1;
        check(!dupe, "no register appears twice in the table");

        /* Every entry has both strings: they are what the describe() paragraph
           and any future log line are built from. */
        int missing = 0;
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++)
            if (!charger_config[i].name || !charger_config[i].why ||
                !charger_config[i].name[0] || !charger_config[i].why[0]) missing = 1;
        check(!missing, "every entry carries a name and a reason");
    }

    printf("the read-back verification\n");
    {
        /* charger_verify_mask() compares what came back off the part against
           what the table sent, bit per table entry. A write that is
           acknowledged on the bus is not a write that took effect, which is
           the whole reason this exists.

           The mask is built from the SHIPPING table, so these fixtures are
           written by reading charger_config[] rather than by hardcoding three
           bytes — hardcoding them would make this test pass a table it no
           longer describes. */
        uint8_t good[CHARGER_CONFIG_COUNT];
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++) good[i] = charger_config[i].val;

        eq_int(charger_verify_mask(good), 0,
               "a read-back matching the table verifies clean");

        /* One register at a time, so a mask that ORs the wrong bit in is
           caught rather than averaged out. Verified red by changing the
           comparison to `<` or by masking the index. */
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++) {
            uint8_t bad[CHARGER_CONFIG_COUNT];
            memcpy(bad, good, sizeof(bad));
            bad[i] = (uint8_t)(good[i] ^ 0xFFu);
            char what[128];
            snprintf(what, sizeof(what), "%s alone failing to verify sets bit %d and no other",
                     charger_config[i].name, i);
            eq_int(charger_verify_mask(bad), 1 << i, what);
        }

        /* The single most important thing this can catch: the watchdog fired
           between the write and the read-back and REG05 came back at its
           256 mA default. That is the bug reintroducing itself, silently, and
           it must not read as a verified configuration. */
        uint8_t reverted[CHARGER_CONFIG_COUNT];
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++)
            reverted[i] = (charger_config[i].reg == 0x05) ? 0x13 : charger_config[i].val;
        check(charger_verify_mask(reverted) != 0,
              "REG05 reading back as 0x13, the 256 mA default, does NOT verify");
        eq_int(bq25896_iterm_ma(0x13), 256,
               "because that byte is the original defect, in mA");

        /* Every register wrong at once, and nothing wrong at all, as the two
           ends of the range. */
        uint8_t all_bad[CHARGER_CONFIG_COUNT];
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++)
            all_bad[i] = (uint8_t)(good[i] ^ 0xFFu);
        eq_int(charger_verify_mask(all_bad), (1 << CHARGER_CONFIG_COUNT) - 1,
               "every register disagreeing sets every bit");

        /* An all-zero read-back is what a dead bus looks like, and it must not
           come out clean. It only would if some entry were 0x00 — none is, and
           that is worth pinning. */
        uint8_t zeroes[CHARGER_CONFIG_COUNT];
        memset(zeroes, 0, sizeof(zeroes));
        check(charger_verify_mask(zeroes) != 0, "an all-zero read-back does not verify");

        /* "We could not check" is recorded as every register disagreeing, never
           as none. Both charger_configure() and charger_read() use this
           constant for a failed pass. */
        eq_int(CHARGER_MASK_ALL, (1 << CHARGER_CONFIG_COUNT) - 1,
               "the mask for an unreadable pass has one bit per table entry");
        check(CHARGER_MASK_ALL != 0, "and it is never zero, which is what clean looks like");
    }

    printf("the LIVE registers, mapped back onto the table\n");
    {
        /* This is finding number one. charger_read() re-read the written
           registers every 60 s and then carried the BOOT verdict forward
           verbatim — the comparison never ran again, so a REG05 that reverted to
           its 256 mA default at three in the morning still read
           `configured: true, verified: true` at noon, with the decoded
           `termination_current_ma: 256` sitting four lines underneath saying the
           opposite. The comparison now runs on the pass that re-reads, and this
           is the mapping it goes through.

           The mapping is derived from charger_config[] rather than written out
           at the call site, because the call site has these as named struct
           fields and the mask wants them in table order. Verified red by
           swapping the reg04 and reg05 arguments in charger_live_readback(),
           which turns the drift checks below green-for-the-wrong-reason — hence
           the per-register checks first. */
        uint8_t live[CHARGER_CONFIG_COUNT];

        /* Everything as the table has it: the part is still holding what we
           wrote, and the mask is clean. */
        charger_live_readback(0x08, 0x11, 0x5E, 0x8D, live);
        eq_int(charger_verify_mask(live), 0,
               "a part still holding all four written values compares clean");

        /* Each live byte lands on ITS OWN table entry, whatever order the table
           is in. Asserted by register rather than by index for that reason. */
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++) {
            uint8_t want = 0;
            switch (charger_config[i].reg) {
                case 0x04: want = 0x08; break;
                case 0x05: want = 0x11; break;
                case 0x06: want = 0x5E; break;
                case 0x07: want = 0x8D; break;
                default:   want = 0xFF; break;
            }
            char what[128];
            snprintf(what, sizeof(what), "%s's live byte lands on %s's table entry",
                     charger_config[i].name, charger_config[i].name);
            eq_int(live[i], want, what);
        }

        /* THE FAILURE THIS EXISTS FOR: the watchdog we believe is disabled
           expired hours after boot and put the 256 mA termination back. The boot
           record still says the write verified — it did — and the live
           comparison is what has to notice. */
        charger_live_readback(0x08, 0x13, 0x5E, 0x8D, live);
        check(charger_verify_mask(live) != 0,
              "REG05 reverting to 0x13 AFTER boot shows up in the live comparison");
        eq_int(bq25896_iterm_ma(0x13), 256, "because that byte is the 256 mA defect, in mA");

        /* And the same for the register the old code trusted without ever
           verifying: a charge voltage moved to 4.32 V by anything at all. */
        charger_live_readback(0x08, 0x11, 0x78, 0x8D, live);
        check(charger_verify_mask(live) != 0,
              "REG06 moving to 0x78 — 4.32 V — shows up in the live comparison");
        eq_int(bq25896_vreg_mv(0x78), 4320, "because that byte regulates at, in mV");

        /* A watchdog expiry reverts more than one register, and the mask has to
           carry all of them rather than the first. */
        charger_live_readback(0x20, 0x13, 0x5E, 0x8D, live);
        eq_int(__builtin_popcount(charger_verify_mask(live)), 2,
               "REG04 and REG05 both reverted sets exactly two bits");
    }

    printf("what makes the endpoint say `configured`\n");
    {
        /* The summary a caller reads first. It was the latched boot verdict;
           it is now re-derived from the pass that just read the part, and every
           one of the four inputs can veto it.

           Verified red by dropping each conjunct from charger_config_is_live()
           in turn: dropping `boot_verified` turns the second check red,
           `read_ok` the third, `live_mask == 0` the fourth, and
           `vreg_in_bounds` the fifth — which is the one the safety argument
           rests on. */
        check(charger_config_is_live(true, true, 0, true),
              "boot verified, pass read, nothing drifted, voltage in bounds: configured");
        check(!charger_config_is_live(false, true, 0, true),
              "a boot write that never verified is NOT made live by later agreement");
        check(!charger_config_is_live(true, false, 0, true),
              "a pass that could not read the part is NOT evidence the settings are live");
        check(!charger_config_is_live(true, true, 0x04, true),
              "any register that has drifted since boot makes it false");
        check(!charger_config_is_live(true, true, 0, false),
              "and an out-of-bounds charge voltage CANNOT coexist with configured");

        /* The bit that vetoes it is any bit, not a particular one. */
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++) {
            char what[128];
            snprintf(what, sizeof(what), "%s alone drifting is enough to make configured false",
                     charger_config[i].name);
            check(!charger_config_is_live(true, true, (uint8_t)(1u << i), true), what);
        }

        /* Stated as the property rather than as five examples: there is no
           combination of inputs where configured is true and something is
           wrong. This is the check that cannot be satisfied by special-casing. */
        int leak = 0;
        for (int b = 0; b < 2; b++)
            for (int r = 0; r < 2; r++)
                for (int m = 0; m <= CHARGER_MASK_ALL; m++)
                    for (int v = 0; v < 2; v++)
                        if (charger_config_is_live(b, r, (uint8_t)m, v) &&
                            !(b && r && m == 0 && v)) leak = 1;
        check(!leak,
              "over every combination of the four inputs, configured is true only when all four are");
    }

    printf("the whole verdict a pass derives, which is what charger_read() delegates to\n");
    {
        /* THE CHECK THAT WAS MISSING. The three functions above are pure and
           each was proven, and that was not enough: charger_read() wired them
           together itself, so the statement that turns "we re-read the
           registers" into "we re-compared them" sat outside the slice with
           nothing holding it. Setting the live mask to zero there disabled the
           entire re-comparison and every suite stayed green.
           charger_derive() is that statement, extracted, and this block drives
           it.

           Verified red by replacing charger_derive()'s mask line with
           `v.live_mask = 0;` — the mutation that used to pass — which turns
           four checks below red; and by dropping the `read_ok ?` so an
           unreadable pass compares clean, which turns three more red. */
        ChargerVerdict v;

        /* The part is still holding all four. This is the only shape in which
           the endpoint may lead with `configured`. */
        charger_derive(v, true, true, 0x08, 0x11, 0x5E, 0x8D);
        eq_int(v.live_mask, 0, "a pass finding all four registers unchanged derives a clean mask");
        check(v.vreg_in_bounds, "with the charge voltage in bounds");
        check(v.config_still_live, "and the configuration still live");
        check(v.configured, "so the pass derives configured TRUE");

        /* The finding itself: verified at boot, drifted afterwards. REG05 back
           at the 256 mA default is the bug reintroducing itself silently, hours
           after a boot write that really did verify. */
        charger_derive(v, true, true, 0x08, 0x13, 0x5E, 0x8D);
        check(v.live_mask != 0,
              "REG05 reverting to 0x13 after boot derives a NON-ZERO mask");
        eq_int(v.live_mask, (uint8_t)(1u << 2), "and names REG05 alone as the register that moved");
        check(!v.config_still_live, "which makes the configuration no longer live");
        check(!v.configured,
              "so a device that verified at boot and drifted after CANNOT derive configured true");

        /* The same for the register that used to be trusted and never checked:
           a charge voltage another host moved to 4.32 V. Both vetoes fire here
           — it disagrees with the table AND it is out of bounds — and the
           bound is isolated from the drift by the property check above. */
        charger_derive(v, true, true, 0x08, 0x11, 0x78, 0x8D);
        check(!v.vreg_in_bounds, "a charge voltage found at 4.32 V derives OUT of bounds");
        check(!v.configured, "and cannot derive configured true either");

        /* A pass that could not read the part concludes nothing, and nothing is
           not "fine". */
        charger_derive(v, false, true, 0x08, 0x11, 0x5E, 0x8D);
        eq_int(v.live_mask, CHARGER_MASK_ALL,
               "a pass that could not read derives every bit set, never a clean mask");
        check(!v.vreg_in_bounds, "and no claim about the charge voltage it did not see");
        check(!v.config_still_live, "nor that the configuration is still live");
        check(!v.configured, "nor configured");

        /* And the boot verdict still carries: agreement now does not
           retroactively land a write that never landed. */
        charger_derive(v, true, false, 0x08, 0x11, 0x5E, 0x8D);
        check(v.config_still_live,
              "a part holding the table is still live even when the boot write never verified");
        check(!v.configured,
              "but configured stays FALSE: later agreement does not land a write that failed");

        /* A watchdog expiry reverts more than one register at once, and the
           verdict has to carry all of them. */
        charger_derive(v, true, true, 0x20, 0x13, 0x5E, 0x8D);
        eq_int(__builtin_popcount(v.live_mask), 2,
               "REG04 and REG05 both reverted derives exactly two bits");
        check(!v.configured, "and configured false with them");

        /* Every single-register drift, one at a time, driven through the real
           derivation rather than through its ingredients: no register is
           exempt, whichever slot the table puts it in. */
        for (int i = 0; i < CHARGER_CONFIG_COUNT; i++) {
            uint8_t r04 = 0x08, r05 = 0x11, r06 = 0x5E, r07 = 0x8D;
            switch (charger_config[i].reg) {
                case 0x04: r04 = 0x20; break;   /* 2048 mA, the POR */
                case 0x05: r05 = 0x13; break;   /* 256 mA, the defect */
                case 0x06: r06 = 0x5A; break;   /* 4.192 V: in bounds, still wrong */
                case 0x07: r07 = 0x9D; break;   /* watchdog back at 40 s */
                default:   break;
            }
            charger_derive(v, true, true, r04, r05, r06, r07);
            char what[160];
            snprintf(what, sizeof(what),
                     "%s alone drifting derives configured false and bit %d set",
                     charger_config[i].name, i);
            check(!v.configured && v.live_mask == (uint8_t)(1u << i), what);
        }
    }

    printf("EN_ILIM: why the input current limit register is not the whole answer\n");
    {
        /* With EN_ILIM set — the part's default — the actual input current
           limit is the LOWER of the register field and the ILIM pin resistor.
           Reporting IINLIM without reporting this bit would give a caller a
           number that reads like an answer and is only half of one. */
        check(bq25896_ilim_pin_enabled(0x48), "EN_ILIM is bit 6, and it is set by default");
        check(!bq25896_ilim_pin_enabled(0x08), "and clear when the pin limit is disabled");
        check(!bq25896_ilim_pin_enabled(0xBF), "it reads false with every other bit set");
        check(bq25896_ilim_pin_enabled(0x40), "and true off its own bit alone");
        /* It sits above the IINLIM field and must not disturb it. */
        eq_int(bq25896_iinlim_ma(0x48), 500, "and it is not part of the current");
    }

    printf("REG0B: charge state, which is what answers \"why did it stop\"\n");
    {
        /* CHRG_STAT is bits 4:3. Getting the shift wrong reads PG_STAT and
           VSYS_STAT instead and reports a plausible wrong answer. */
        eq_str(bq25896_chrg_stat_name(0x00), "not_charging",     "CHRG_STAT 00");
        eq_str(bq25896_chrg_stat_name(0x08), "pre_charge",       "CHRG_STAT 01");
        eq_str(bq25896_chrg_stat_name(0x10), "fast_charging",    "CHRG_STAT 10");
        eq_str(bq25896_chrg_stat_name(0x18), "termination_done", "CHRG_STAT 11");

        eq_int(bq25896_chrg_stat(0x18), 3, "the raw bits behind termination_done");
        eq_int(bq25896_chrg_stat(0x10), 2, "and behind fast_charging");

        /* The field is read out of a whole byte, so every bit outside it must
           be ignored. 0xE7 is "everything set except CHRG_STAT". */
        eq_str(bq25896_chrg_stat_name(0xE7), "not_charging",
               "CHRG_STAT ignores every bit outside the field");
        eq_str(bq25896_chrg_stat_name(0xFF), "termination_done",
               "and reads the field when all bits are set");

        /* A whole plausible byte rather than one field at a time: VBUS_STAT
           010, CHRG_STAT 11, PG_STAT 1, the reserved bit 1 set as the datasheet
           says it always is. This is the shape of the reading that cost 296 mAh
           — still plugged in, and the part had decided it was finished. */
        eq_str(bq25896_chrg_stat_name(0x5E), "termination_done",
               "0x5E: adapter attached, power good, charge finished");
        eq_str(bq25896_vbus_stat_name(0x5E), "adapter", "and the input it saw");
        check(bq25896_power_good(0x5E), "with power good");
        check(!bq25896_vsys_regulating(0x5E), "and the system rail not in regulation");

        /* VBUS_STAT is bits 7:5, and this part documents FOUR of its eight
           codes. Borrowing the rest of the family's table would put a
           confident wrong name on silicon that does not define them. */
        eq_str(bq25896_vbus_stat_name(0x00), "none",         "VBUS_STAT 000");
        eq_str(bq25896_vbus_stat_name(0x20), "usb_host_sdp", "VBUS_STAT 001");
        eq_str(bq25896_vbus_stat_name(0x40), "adapter",      "VBUS_STAT 010");
        eq_str(bq25896_vbus_stat_name(0xE0), "otg",          "VBUS_STAT 111");
        eq_str(bq25896_vbus_stat_name(0x60), "unknown",      "VBUS_STAT 011 is undocumented here");
        eq_str(bq25896_vbus_stat_name(0x80), "unknown",      "and so is 100");
        eq_str(bq25896_vbus_stat_name(0xA0), "unknown",      "and 101");
        eq_str(bq25896_vbus_stat_name(0xC0), "unknown",      "and 110");

        /* PG_STAT is bit 2 and VSYS_STAT is bit 0. Bit 1 is reserved and always
           reads 1, so nothing may respond to it. */
        check(bq25896_power_good(0x04),   "PG_STAT is bit 2");
        check(!bq25896_power_good(0xFB),  "and reads false with every other bit set");
        check(bq25896_vsys_regulating(0x01),  "VSYS_STAT is bit 0");
        check(!bq25896_vsys_regulating(0xFE), "and reads false with every other bit set");
        check(!bq25896_power_good(0x02) && !bq25896_vsys_regulating(0x02),
              "the reserved bit 1, which always reads 1, is claimed by neither");
    }

    printf("REG0C: the faults\n");
    {
        /* CHRG_FAULT is bits 5:4. */
        eq_str(bq25896_chrg_fault_name(0x00), "normal",               "CHRG_FAULT 00");
        eq_str(bq25896_chrg_fault_name(0x10), "input",                "CHRG_FAULT 01");
        eq_str(bq25896_chrg_fault_name(0x20), "thermal_shutdown",     "CHRG_FAULT 10");
        eq_str(bq25896_chrg_fault_name(0x30), "safety_timer_expired", "CHRG_FAULT 11");
        eq_str(bq25896_chrg_fault_name(0xCF), "normal",
               "CHRG_FAULT ignores every bit outside the field");

        /* NTC_FAULT is bits 2:0 and its codes are NOT contiguous: 001 and 100
           are undefined in buck mode and must not be given a name. */
        eq_str(bq25896_ntc_fault_name(0x00), "normal",  "NTC 000");
        eq_str(bq25896_ntc_fault_name(0x02), "ts_warm", "NTC 010");
        eq_str(bq25896_ntc_fault_name(0x03), "ts_cool", "NTC 011");
        eq_str(bq25896_ntc_fault_name(0x05), "ts_cold", "NTC 101");
        eq_str(bq25896_ntc_fault_name(0x06), "ts_hot",  "NTC 110");
        eq_str(bq25896_ntc_fault_name(0x01), "unknown", "NTC 001 is undefined in buck mode");
        eq_str(bq25896_ntc_fault_name(0x04), "unknown", "and so is 100");
        eq_str(bq25896_ntc_fault_name(0xF8), "normal",  "NTC ignores every bit outside the field");

        /* The single-bit faults, each off its own bit and no other. */
        eq_int(BQ25896_FAULT_WATCHDOG, 0x80, "WATCHDOG_FAULT is bit 7");
        eq_int(BQ25896_FAULT_BOOST,    0x40, "BOOST_FAULT is bit 6");
        eq_int(BQ25896_FAULT_BAT_OVP,  0x08, "BAT_FAULT is bit 3");
        check((BQ25896_FAULT_BAT_OVP & 0x07) == 0,
              "BAT_FAULT does not overlap the NTC field");
        check((BQ25896_FAULT_WATCHDOG & 0x30) == 0 && (BQ25896_FAULT_BOOST & 0x30) == 0,
              "and neither single-bit fault overlaps CHRG_FAULT");

        /* ---- The watchdog bit, which reads 1 in default mode by definition ----
         *
         * Before the boot write is attempted, the part is telling us it is
         * running unconfigured. Rendering that as a fault would put a red flag
         * on the healthy state of a device nobody had configured yet.
         *
         * THE GATE IS THE ATTEMPT, NOT THE SUCCESS, and the third check is why.
         * Gating on a fully successful configuration suppresses the flag in
         * precisely the scenario it exists for: the REG07 write is the one that
         * fails, so the watchdog stays armed, expires, reverts REG05 and sets
         * bit 7 — and the response renders `watchdog: false` because the
         * configuration it was gated on never landed.
         *
         * Verified red by dropping the `configure_attempted &&` from
         * bq25896_watchdog_fault_is_real(), which turns the first check below
         * red; by replacing its body with `return false`, which turns the second
         * and third red; and — for the third specifically — by passing
         * `configured` rather than `write_attempted` at the call site in the
         * endpoint, which is the defect this restores.
         */
        check(!bq25896_watchdog_fault_is_real(0x80, false),
              "the watchdog bit is NOT a fault before the boot write was attempted");
        check(bq25896_watchdog_fault_is_real(0x80, true),
              "and IS a fault once it was — the settings would have reverted");
        check(!bq25896_watchdog_fault_is_real(0x00, true),
              "a clear bit is not a fault either way");
        check(!bq25896_watchdog_fault_is_real(0x7F, true),
              "and no other fault bit is mistaken for the watchdog");

        /* The scenario itself, composed out of the two functions the endpoint
           calls, because what was wrong was which value got passed here and
           that is a call site rather than a branch. The REG07 write failed, so
           the watchdog stayed armed, expired, and reverted REG05 to 0x13; the
           part sets bit 7. `configured` is false — correctly, the settings are
           NOT live — and the whole point is that the fault must not be gated on
           it. Verified red by passing `configured` in place of the attempt. */
        ChargerVerdict after_expiry;
        charger_derive(after_expiry, true, true, 0x08, 0x13, 0x5E, 0x8D);
        bool configured_after_expiry = after_expiry.configured;
        check(!configured_after_expiry,
              "after a watchdog expiry reverts REG05, `configured` is false");
        check(bq25896_watchdog_fault_is_real(0x80, /* write_attempted */ true),
              "and the watchdog fault is still REPORTED, because it is gated on the attempt");
        check(!bq25896_watchdog_fault_is_real(0x80, configured_after_expiry),
              "gating it on `configured` instead would hide exactly the case it exists for");
    }

    printf("REG13: the DPM status\n");
    {
        check(bq25896_in_vindpm(0x80),  "VDPM_STAT is bit 7");
        check(!bq25896_in_vindpm(0x7F), "and reads false with every other bit set");
        check(bq25896_in_iindpm(0x40),  "IDPM_STAT is bit 6");
        check(!bq25896_in_iindpm(0xBF), "and reads false with every other bit set");

        /* IDPM_LIM shares the IINLIM encoding, which is why one decoder serves
           both, and the two status bits above it must not leak into it. */
        eq_int(bq25896_iinlim_ma(0xC8), 500,
               "IDPM_LIM decodes with the status bits set exactly as it does without");
        eq_int(bq25896_iinlim_ma(0x08), 500, "and the same byte without them");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test"
