#!/usr/bin/env bash
#
# Host-side regression test for the progress arbiter in src/skills/progress.cpp.
#
# Why this exists: which job the bar shows is pure computation over an array of
# structs and a clock reading, and it is also the piece whose mistakes are least
# visible. A wrong arc does not fail a build, does not throw, does not appear in
# GET /events and does not even look broken — it looks like a different job's
# progress, occasionally, and nobody finds out. There is no test on hardware
# that catches "showed the download instead of the blast" either, because the
# only witness is somebody standing in front of the device at the moment it
# happens.
#
# What this DOES NOT cover, said plainly rather than papered over: the drawing
# and the LED ring. Both need a panel, a WS2812 string and TFT_eSPI, and no
# coverage is claimed for them by anything below. Nor is the HTTP layer here —
# tools/test_routes.sh checks that POST /progress registers a body collector and
# an exact matcher, which is the failure mode that layer actually has.
#
# The core is sliced straight out of the shipping source between its
# `host-test:begin core` and `host-test:end` markers, the same way
# tools/test_voice_url.sh and tools/test_wav_header.sh slice theirs, so this
# runs the real implementation rather than a copy that could drift.
#
# Usage: tools/test_progress.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/progress.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_progress.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

PRELUDE
    slice "$src" core
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

/* An empty store. Zeroed, exactly as skill_progress_init() leaves it. */
static void reset(ProgressJob *jobs) {
    memset(jobs, 0, sizeof(ProgressJob) * PROGRESS_MAX);
}

/* Publish, asserting that it was accepted — for the cases that are about
   something other than acceptance. */
static void must_publish(ProgressJob *jobs, const char *label, int pct,
                         unsigned long ttl_s, uint8_t src, unsigned long now) {
    const char *err = "(not set)";
    if (!progress_core_publish(jobs, label, pct, ttl_s, src, now, &err)) {
        printf("  FAIL: publishing %s should have been accepted (refused: %s)\n",
               label, err);
        failures++;
    }
}

/* The label the arbiter picks, or "-" for none. */
static const char *showing(const ProgressJob *jobs, unsigned long now) {
    int i = progress_core_select(jobs, now);
    return (i < 0) ? "-" : jobs[i].label;
}

static void wins(const ProgressJob *jobs, unsigned long now, const char *want,
                 const char *what) {
    const char *got = showing(jobs, now);
    if (strcmp(got, want) != 0) {
        printf("  FAIL: %s — showing \"%s\", wanted \"%s\"\n", what, got, want);
        failures++;
    } else {
        printf("  ok:   %s — showing \"%s\"\n", what, got);
    }
}

/* How many jobs are live and unexpired. */
static int live_count(const ProgressJob *jobs, unsigned long now) {
    int n = 0;
    for (int i = 0; i < PROGRESS_MAX; i++)
        if (jobs[i].live && !progress_expired(jobs[i], now)) n++;
    return n;
}

/* One refused label. The reason matters as much as the refusal: a caller told
   "label is required" when the real problem was a Cyrillic character is being
   sent to look in the wrong place. */
static void bad_label(const char *label, const char *why) {
    const char *err = NULL;
    if (progress_label_check(label, &err)) {
        printf("  FAIL: label should be refused (%s)\n", why);
        failures++;
        return;
    }
    if (!err || !err[0]) {
        printf("  FAIL: label was refused with no reason (%s)\n", why);
        failures++;
        return;
    }
    printf("  ok:   %s refused — %s\n", why, err);
}

#define S 1000UL   /* one second of deadline, in the units the core uses */

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    ProgressJob jobs[PROGRESS_MAX];
    unsigned long t0 = 100000;

    printf("nothing to show\n");
    {
        reset(jobs);
        check(progress_core_select(jobs, t0) < 0, "an empty store selects nothing");
        wins(jobs, t0, "-", "an empty store");
    }

    printf("one job\n");
    {
        reset(jobs);
        must_publish(jobs, "download", 42, 30, PROGRESS_NET, t0);
        wins(jobs, t0, "download", "the only live job");
        int i = progress_core_select(jobs, t0);
        check(i >= 0 && jobs[i].percent == 42, "and it carries its percentage");
        check(i >= 0 && jobs[i].source == PROGRESS_NET, "and the class it was published under");
        check(i >= 0 && jobs[i].deadline_ms == t0 + 30 * S,
              "and a deadline of exactly the ttl it asked for");
    }

    printf("device beats network, whatever order they arrived in\n");
    {
        /* This is the rule the whole commit exists for: the owner's finger is
           on the knob, and that is what he is looking at. */
        reset(jobs);
        must_publish(jobs, "download", 90, 30, PROGRESS_NET, t0);
        must_publish(jobs, "IR blast", 3, 5, PROGRESS_DEVICE, t0 + 1);
        wins(jobs, t0 + 2, "IR blast", "a blast started after a download");

        /* ...and the other way round, so it cannot be passing by accident of
           arrival order. Here the NETWORK job is the more recent one and the
           more advanced one, and it still loses. */
        reset(jobs);
        must_publish(jobs, "IR blast", 3, 5, PROGRESS_DEVICE, t0);
        must_publish(jobs, "download", 90, 30, PROGRESS_NET, t0 + 1000);
        wins(jobs, t0 + 1001, "IR blast", "a download pushed after a blast started");
    }

    printf("two jobs of the same class: whoever spoke last\n");
    {
        reset(jobs);
        must_publish(jobs, "gates", 10, 60, PROGRESS_NET, t0);
        must_publish(jobs, "review", 10, 60, PROGRESS_NET, t0 + 5 * S);
        wins(jobs, t0 + 6 * S, "review", "the more recently updated of two pushes");

        /* An update to the older one takes the bar back. */
        must_publish(jobs, "gates", 20, 60, PROGRESS_NET, t0 + 7 * S);
        wins(jobs, t0 + 8 * S, "gates", "after the older job reports again");

        /* Two device jobs follow the same rule as two network ones. */
        reset(jobs);
        must_publish(jobs, "IR blast", 10, 5, PROGRESS_DEVICE, t0);
        must_publish(jobs, "upload", 10, 5, PROGRESS_DEVICE, t0 + 1 * S);
        wins(jobs, t0 + 2 * S, "upload", "the more recently updated of two device jobs");
    }

    printf("an exact tie is broken deterministically, not by luck\n");
    {
        /* A display that flickers between two jobs is worse than one that picks
           the wrong job, so the lower slot wins and keeps winning. */
        reset(jobs);
        must_publish(jobs, "a", 10, 60, PROGRESS_NET, t0);
        must_publish(jobs, "b", 10, 60, PROGRESS_NET, t0);
        wins(jobs, t0 + 1, "a", "two jobs updated in the same millisecond");
        wins(jobs, t0 + 2, "a", "and the same answer a millisecond later");
    }

    printf("an expired job is not a candidate\n");
    {
        reset(jobs);
        /* The expired one is a DEVICE job, so if expiry were not checked first
           it would outrank the live network job and this would fail. */
        must_publish(jobs, "IR blast", 50, 5, PROGRESS_DEVICE, t0);
        must_publish(jobs, "download", 50, 600, PROGRESS_NET, t0 + 1 * S);
        wins(jobs, t0 + 2 * S, "IR blast", "before the blast's ttl runs out");
        wins(jobs, t0 + 6 * S, "download", "after it does");

        /* The boundary itself: a deadline is reached, not merely passed. */
        reset(jobs);
        must_publish(jobs, "job", 50, 5, PROGRESS_NET, t0);
        wins(jobs, t0 + 5 * S - 1, "job", "one millisecond before the deadline");
        wins(jobs, t0 + 5 * S, "-", "at the deadline exactly");
    }

    printf("everything expired\n");
    {
        reset(jobs);
        must_publish(jobs, "one", 10, 5, PROGRESS_NET, t0);
        must_publish(jobs, "two", 20, 5, PROGRESS_DEVICE, t0);
        must_publish(jobs, "three", 30, 5, PROGRESS_NET, t0);
        wins(jobs, t0 + 60 * S, "-", "three dead jobs select nothing");
        check(progress_core_select(jobs, t0 + 60 * S) < 0,
              "and the selector says so with -1 rather than a stale index");
    }

    printf("the label is the key: publishing again updates, never duplicates\n");
    {
        reset(jobs);
        must_publish(jobs, "download", 10, 60, PROGRESS_NET, t0);
        must_publish(jobs, "download", 20, 60, PROGRESS_NET, t0 + 1 * S);
        must_publish(jobs, "download", 30, 60, PROGRESS_NET, t0 + 2 * S);
        check(live_count(jobs, t0 + 3 * S) == 1, "three publishes leave one job");
        int i = progress_core_select(jobs, t0 + 3 * S);
        check(i >= 0 && jobs[i].percent == 30, "and it holds the newest percentage");

        /* A different label is a different job, which is the other half of the
           same claim. */
        must_publish(jobs, "download2", 5, 60, PROGRESS_NET, t0 + 4 * S);
        check(live_count(jobs, t0 + 5 * S) == 2, "a different label opens a second job");

        /* Case matters: keys are compared byte for byte, so "Download" is not
           "download". Worth pinning because the alternative is a caller whose
           two jobs mysteriously become one. */
        must_publish(jobs, "Download", 7, 60, PROGRESS_NET, t0 + 6 * S);
        check(live_count(jobs, t0 + 7 * S) == 3, "and so does the same label capitalised");

        /* Republishing under a label whose deadline has just passed revives it
           in place rather than opening a second job beside it. */
        reset(jobs);
        must_publish(jobs, "download", 10, 5, PROGRESS_NET, t0);
        must_publish(jobs, "download", 60, 60, PROGRESS_NET, t0 + 30 * S);
        check(live_count(jobs, t0 + 31 * S) == 1, "an expired label is revived, not duplicated");
        wins(jobs, t0 + 31 * S, "download", "and it is back on the bar");
    }

    printf("percent is clamped rather than allowed to draw past the end\n");
    {
        reset(jobs);
        must_publish(jobs, "over", 142, 60, PROGRESS_NET, t0);
        must_publish(jobs, "under", -7, 60, PROGRESS_NET, t0);
        check(jobs[progress_find(jobs, "over")].percent == 100, "142 becomes 100");
        check(jobs[progress_find(jobs, "under")].percent == 0, "-7 becomes 0");
        check(jobs[progress_find(jobs, "over")].percent <= 100 &&
              jobs[progress_find(jobs, "under")].percent <= 100,
              "and nothing lands outside 0..100");
    }

    printf("a finished job lingers, then goes\n");
    {
        reset(jobs);
        /* An hour of ttl does not keep 100%% on the screen for an hour. */
        must_publish(jobs, "done", 100, 3600, PROGRESS_NET, t0);
        wins(jobs, t0 + 1 * S, "done", "still up a second after reaching 100");
        wins(jobs, t0 + PROGRESS_DONE_LINGER_MS + 1, "-", "gone once the linger is over");

        /* ...and a ttl SHORTER than the linger is not stretched to it: the
           publisher asked for one second and gets one second. */
        reset(jobs);
        must_publish(jobs, "done", 100, 1, PROGRESS_NET, t0);
        wins(jobs, t0 + 1 * S + 1, "-", "a one-second ttl is not stretched by finishing");
    }

    printf("ttl: the default, the ceiling, and what zero means\n");
    {
        reset(jobs);
        must_publish(jobs, "default", 10, 0, PROGRESS_NET, t0);
        check(jobs[progress_find(jobs, "default")].deadline_ms
                  == t0 + PROGRESS_TTL_DEFAULT_S * S,
              "a ttl of 0 asks for the default rather than expiring at once");

        must_publish(jobs, "max", 10, PROGRESS_TTL_MAX_S, PROGRESS_NET, t0);
        check(jobs[progress_find(jobs, "max")].deadline_ms
                  == t0 + PROGRESS_TTL_MAX_S * S,
              "the maximum ttl is accepted whole");

        const char *err = NULL;
        check(!progress_core_publish(jobs, "toolong", 10, PROGRESS_TTL_MAX_S + 1,
                                     PROGRESS_NET, t0, &err),
              "one second over the ceiling is refused");
        check(err && err[0], "  ...with a reason");

        /* A long ttl is the whole point: an agent updating the bar between the
           steps of a build must not have it blink out mid-step. */
        reset(jobs);
        must_publish(jobs, "gates", 40, 600, PROGRESS_NET, t0);
        wins(jobs, t0 + 300 * S, "gates", "five minutes into a ten-minute ttl");
        wins(jobs, t0 + 601 * S, "-", "and gone once even that has run out");
    }

    printf("clearing\n");
    {
        reset(jobs);
        must_publish(jobs, "download", 40, 600, PROGRESS_NET, t0);
        check(progress_core_clear(jobs, "download"), "clearing a live job reports it did");
        wins(jobs, t0 + 1, "-", "and the bar is empty");
        check(!progress_core_clear(jobs, "download"),
              "clearing it again reports there was nothing to clear");
        check(!progress_core_clear(jobs, "never-existed"),
              "and so does clearing a label that never existed");
        check(!progress_core_clear(jobs, ""), "an empty label clears nothing");
        check(!progress_core_clear(jobs, NULL), "and a null one is not dereferenced");
    }

    printf("reaping frees slots, not just the bar\n");
    {
        reset(jobs);
        must_publish(jobs, "a", 10, 5, PROGRESS_NET, t0);
        must_publish(jobs, "b", 10, 600, PROGRESS_NET, t0);
        check(progress_core_reap(jobs, t0 + 1 * S) == 0, "nothing is reaped early");
        check(progress_core_reap(jobs, t0 + 10 * S) == 1, "the expired one is reaped");
        check(progress_core_reap(jobs, t0 + 10 * S) == 0, "and only once");
        check(live_count(jobs, t0 + 10 * S) == 1, "the live one survives");
    }

    printf("a full store: who gives up a slot\n");
    {
        /* Four network pushes, then a fifth. The least recently updated one
           loses its slot; the rest are untouched. */
        reset(jobs);
        must_publish(jobs, "n1", 10, 600, PROGRESS_NET, t0 + 4 * S);
        must_publish(jobs, "n2", 10, 600, PROGRESS_NET, t0 + 1 * S);
        must_publish(jobs, "n3", 10, 600, PROGRESS_NET, t0 + 3 * S);
        must_publish(jobs, "n4", 10, 600, PROGRESS_NET, t0 + 2 * S);
        must_publish(jobs, "n5", 10, 600, PROGRESS_NET, t0 + 5 * S);
        check(progress_find(jobs, "n2") < 0, "the stalest push loses its slot");
        check(progress_find(jobs, "n5") >= 0, "and the new one has it");
        check(live_count(jobs, t0 + 5 * S) == PROGRESS_MAX, "the store stays full, not over");

        /* An expired job is taken before any live one, however stale the live
           one is. */
        reset(jobs);
        must_publish(jobs, "dead", 10, 1, PROGRESS_NET, t0);
        must_publish(jobs, "n1", 10, 600, PROGRESS_NET, t0 + 1);
        must_publish(jobs, "n2", 10, 600, PROGRESS_NET, t0 + 2);
        must_publish(jobs, "n3", 10, 600, PROGRESS_NET, t0 + 3);
        must_publish(jobs, "n4", 10, 600, PROGRESS_NET, t0 + 5 * S);
        check(progress_find(jobs, "dead") < 0, "the expired job's slot is taken first");
        check(progress_find(jobs, "n1") >= 0, "and the stalest LIVE job keeps its own");

        /* The priority rule again, on the admission side: a curl command must
           not be able to cancel the blast the owner is standing in front of. */
        reset(jobs);
        must_publish(jobs, "d1", 10, 600, PROGRESS_DEVICE, t0);
        must_publish(jobs, "d2", 10, 600, PROGRESS_DEVICE, t0);
        must_publish(jobs, "d3", 10, 600, PROGRESS_DEVICE, t0);
        must_publish(jobs, "d4", 10, 600, PROGRESS_DEVICE, t0);
        {
            const char *err = NULL;
            check(!progress_core_publish(jobs, "push", 10, 600, PROGRESS_NET, t0, &err),
                  "a push into a store full of device jobs is refused");
            check(err && err[0], "  ...with a reason rather than silently");
            check(live_count(jobs, t0) == PROGRESS_MAX, "and nothing was dropped");
        }

        /* A device job, on the other hand, takes a network slot before it takes
           another device's — same order as the bar. */
        reset(jobs);
        must_publish(jobs, "d1", 10, 600, PROGRESS_DEVICE, t0);
        must_publish(jobs, "d2", 10, 600, PROGRESS_DEVICE, t0);
        must_publish(jobs, "n1", 10, 600, PROGRESS_NET, t0 + 5 * S);
        must_publish(jobs, "n2", 10, 600, PROGRESS_NET, t0 + 6 * S);
        must_publish(jobs, "d3", 10, 600, PROGRESS_DEVICE, t0 + 7 * S);
        check(progress_find(jobs, "n1") < 0, "a device job displaces the stalest network one");
        check(progress_find(jobs, "d1") >= 0 && progress_find(jobs, "d2") >= 0,
              "and leaves both device jobs alone");
    }

    printf("labels: what is refused, and why\n");
    {
        bad_label(NULL, "a null label");
        bad_label("", "an empty label");
        bad_label("   ", "a label of nothing but spaces");
        /* PROGRESS_LABEL_LEN - 1 characters fit; one more does not. Checked at
           the boundary rather than near it. */
        {
            char buf[64];
            memset(buf, 'x', PROGRESS_LABEL_LEN - 1);
            buf[PROGRESS_LABEL_LEN - 1] = '\0';
            const char *err = NULL;
            check(progress_label_check(buf, &err), "a label at the cap is accepted");

            memset(buf, 'x', PROGRESS_LABEL_LEN);
            buf[PROGRESS_LABEL_LEN] = '\0';
            bad_label(buf, "one character over the cap");
        }
        /* The one that already bit this firmware once. These bytes are a
           Cyrillic word in UTF-8; the panel's compiled fonts cover 32..126 and
           would draw them as garbage with no error raised anywhere, so they are
           refused at the endpoint while somebody is still holding the curl. */
        bad_label("\xd0\xb7\xd0\xb0\xd0\xb3\xd1\x80\xd1\x83\xd0\xb7\xd0\xba\xd0\xb0",
                  "a non-ASCII label");
        bad_label("caf\xc3\xa9", "an accented character");
        bad_label("a\nb", "an embedded newline");
        bad_label("a\rb", "an embedded carriage return");
        bad_label("a\tb", "an embedded tab");
        bad_label("a\x01" "b", "a control character");
        bad_label("a\x7f" "b", "DEL, which is above the printable range");

        /* And what is accepted, so the rule is not quietly stricter than it
           says. A space inside a label is fine — "IR blast" is one. */
        const char *err = NULL;
        check(progress_label_check("IR blast", &err), "a label with a space inside it");
        check(progress_label_check("download-1", &err), "digits and a hyphen");
        check(progress_label_check("a", &err), "a single character");
        check(progress_label_check("~!@#$%^&*()_+", &err), "the printable punctuation");

        /* Refusing must not touch the store: a bad label from one caller cannot
           disturb the job another caller has on the bar. */
        reset(jobs);
        must_publish(jobs, "download", 42, 600, PROGRESS_NET, t0);
        err = NULL;
        check(!progress_core_publish(jobs, "", 10, 600, PROGRESS_NET, t0 + 1, &err),
              "an empty label is refused by publish too");
        check(live_count(jobs, t0 + 1) == 1, "and the store is untouched");
        wins(jobs, t0 + 1, "download", "and the bar still shows what it did");
    }

    printf("the millis() rollover, which this firmware has paid for four times\n");
    {
        /* Deadlines are stamped on the web-server task and read on the loop
           task, so the comparisons have to be signed. Near the wrap, unsigned
           arithmetic turns "three seconds left" into forty-nine days. */
        unsigned long near_wrap = 0xFFFFFFFFUL - 2 * S;
        reset(jobs);
        must_publish(jobs, "job", 40, 10, PROGRESS_NET, near_wrap);
        wins(jobs, near_wrap + 1 * S, "job", "a second before the counter wraps");
        /* Deliberately wrapped: 3 seconds past near_wrap is 1 second past zero. */
        wins(jobs, near_wrap + 3 * S, "job", "a second after it wrapped");
        wins(jobs, near_wrap + 11 * S, "-", "and expired on the far side of the wrap");

        /* And the other direction: a deadline stamped a few milliseconds AFTER
           the reading it is compared against, which is what a publish from the
           web-server task landing mid-poll produces. */
        reset(jobs);
        must_publish(jobs, "job", 40, 10, PROGRESS_NET, t0 + 5);
        check(!progress_expired(jobs[progress_find(jobs, "job")], t0),
              "a deadline stamped after the reading is not already expired");
    }

    printf("the ring, shared with an unread critical\n");
    {
        /* The property being defended: the ring is the across-the-room channel
           and a critical must never be outbid on it by a percentage. It is
           shared rather than surrendered, and the sharing is unequal. */
        const unsigned long cycle = PROGRESS_CRIT_PHASE_MS + PROGRESS_ARC_PHASE_MS;

        check(progress_ring_phase(false, false, 0) == PROGRESS_RING_NONE,
              "no crit and no job: the ring has nothing to say");
        check(progress_ring_phase(false, true, 0) == PROGRESS_RING_ARC,
              "a job with nothing unacknowledged: the arc, uninterrupted");
        check(progress_ring_phase(true, false, 0) == PROGRESS_RING_CRIT,
              "a crit with no job: red, uninterrupted");

        /* Unread info and warn are not criticals, so they do not alternate —
           they lose to a live job outright. ring.cpp is what reduces the top
           unread level to this bool; that wiring is not testable here, and no
           claim is made about it. */
        check(progress_ring_phase(false, true, 4 * S) == PROGRESS_RING_ARC,
              "an unread info or warn does not take turns with a job");

        /* Both present: alternation, and the boundaries exactly. */
        check(progress_ring_phase(true, true, 0) == PROGRESS_RING_CRIT,
              "a cycle opens on the critical, not on the arc");
        check(progress_ring_phase(true, true, PROGRESS_CRIT_PHASE_MS - 1) == PROGRESS_RING_CRIT,
              "the last millisecond of the critical phase is still red");
        check(progress_ring_phase(true, true, PROGRESS_CRIT_PHASE_MS) == PROGRESS_RING_ARC,
              "and the arc takes over on the boundary exactly");
        check(progress_ring_phase(true, true, cycle - 1) == PROGRESS_RING_ARC,
              "the last millisecond of the arc phase is still the arc");
        check(progress_ring_phase(true, true, cycle) == PROGRESS_RING_CRIT,
              "and the next cycle opens on red again");
        check(progress_ring_phase(true, true, 137 * cycle + 10) == PROGRESS_RING_CRIT,
              "and the same, a hundred and thirty-seven cycles later");

        /* Pure function of its arguments: the same `now` twice must give the
           same answer, or the alternation is hiding a static somewhere and none
           of the above proves anything. */
        {
            int stable = 1;
            for (unsigned long t = 0; t < 3 * cycle; t += 250) {
                uint8_t a = progress_ring_phase(true, true, t);
                uint8_t b = progress_ring_phase(true, true, t);
                uint8_t c = progress_ring_phase(true, true, t);
                if (a != b || b != c) stable = 0;
            }
            check(stable, "asking twice at the same instant gives the same answer");
        }

        /* THE test of the design, stated as the owner stated it: a glance from
           across the room during any five-second window must land on red. That
           is exactly the claim that the longest unbroken stretch without red is
           under five seconds — which an even 5s/5s split would fail, and which
           is why the two constants must not be tidied into a matching pair. */
        {
            unsigned long run = 0, worst = 0;
            for (unsigned long t = 0; t < 4 * cycle; t++) {
                if (progress_ring_phase(true, true, t) == PROGRESS_RING_ARC) {
                    run++;
                    if (run > worst) worst = run;
                } else {
                    run = 0;
                }
            }
            printf("  ..   longest stretch without red: %lums\n", worst);
            check(worst < 5000, "no five-second glance can miss the red");
            check(worst == PROGRESS_ARC_PHASE_MS,
                  "and that stretch is exactly one arc phase, not two joined up");
        }

        /* The critical gets the majority of every cycle. Stated as a share
           rather than as the two numbers, so it survives both being retuned. */
        {
            unsigned long red = 0;
            for (unsigned long t = 0; t < cycle; t++)
                if (progress_ring_phase(true, true, t) == PROGRESS_RING_CRIT) red++;
            check(red * 2 > cycle, "red owns more than half of every cycle");
        }

        /* Six seconds is a whole number of the ring's 2000ms critical breathe,
           so a phase never hands over mid-breath at some arbitrary brightness.
           Pinned here because it is a relationship between two files and
           nothing else would notice it being broken. */
        check(PROGRESS_CRIT_PHASE_MS % 2000 == 0,
              "the critical phase is a whole number of 2000ms breathe cycles");

        /* A millis() rollover restarts the cycle. The only thing that can do is
           give the red more time, because a cycle opens on the critical — the
           direction to be wrong in. */
        check(progress_ring_phase(true, true, 0) == PROGRESS_RING_CRIT,
              "a rollover lands at the start of a critical phase, never an arc");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test"
