#!/usr/bin/env bash
# Host regression tests for the bounded store in src/skills/panel.cpp.
# The implementation is compiled from its sole host-test marker pair; the
# shared UTF-8 copier is extracted from notify.cpp, where the firmware defines
# it. HTTP wiring and source-level side-effect rules are checked below.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/panel.cpp"
notify="$here/../src/skills/notify.cpp"
main="$here/../src/main.cpp"
arduinojson="$here/../.pio/libdeps/tembed/ArduinoJson/src"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice_core() {
    awk '
        /host-test:begin core/ { grab = 1; next }
        grab && /host-test:end/ { grab = 0; next }
        grab { print }
    ' "$src"
}

extract_copier() {
    awk '
        /^static void notify_cut_utf8\(/ { grab = 1 }
        grab {
            print
            opens = gsub(/{/, "{")
            closes = gsub(/}/, "}")
            depth += opens - closes
        }
        /^static void notify_copy_text\(/ { second = 1 }
        grab && second && depth == 0 { exit }
    ' "$notify"
}

extract_parser() {
    awk '
        /^static bool panel_parse_input\(/ { grab = 1 }
        grab {
            print
            opens = gsub(/{/, "{")
            closes = gsub(/}/, "}")
            depth += opens - closes
            if (opens) started = 1
        }
        grab && started && depth == 0 { exit }
    ' "$src"
}

extract_serializer() {
    awk '
        /^static void panel_serialize\(/ { grab = 1 }
        grab {
            print
            opens = gsub(/{/, "{")
            closes = gsub(/}/, "}")
            depth += opens - closes
            if (opens) started = 1
        }
        grab && started && depth == 0 { exit }
    ' "$src"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_panel.sh — do not edit. */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <string>
#include <unistd.h>
#include <ArduinoJson.h>
PRELUDE
    extract_copier
    slice_core
    extract_serializer
    extract_parser
    cat <<'TESTS'

static int failures = 0;

static void check(bool condition, const char *what) {
    if (condition) printf("  ok:   %s\n", what);
    else { printf("  FAIL: %s\n", what); failures++; }
}

static void reset_store() {
    memset(panel_slot, 0, sizeof(panel_slot));
}

static bool apply(const char *key, const char *title, const char *body,
                  uint32_t ttl, bool has_pos, int32_t pos, uint64_t now,
                  bool *created = NULL, bool *deleted = NULL) {
    Panel incoming;
    panel_prepare(incoming, key, title, body, ttl, pos);
    const char *err = NULL;
    bool ok = panel_core_apply(incoming, body[0] == '\0', has_pos, now,
                               created, deleted, &err);
    if (!ok && (!err || !err[0])) {
        printf("  FAIL: refusal for %s had no reason\n", key);
        failures++;
    }
    return ok;
}

static void bad_key(const char *key, const char *what) {
    const char *err = NULL;
    check(!panel_key_check(key, &err) && err && err[0], what);
}

static bool parse_apply(const char *json, uint64_t now, const char **error = NULL) {
    JsonDocument document;
    DeserializationError parse_error = deserializeJson(document, json);
    if (parse_error || !document.is<JsonObject>()) return false;
    Panel incoming;
    bool deleting = false;
    bool has_pos = false;
    const char *local_error = NULL;
    bool valid = panel_parse_input(document.as<JsonObjectConst>(), &incoming,
                                   &deleting, &has_pos, &local_error);
    if (error) *error = local_error;
    if (!valid) return false;
    return panel_core_apply(incoming, deleting, has_pos, now, NULL, NULL, error);
}

static void invalid_without_mutation(const char *json, const char *what) {
    Panel before[PANEL_MAX];
    memcpy(before, panel_slot, sizeof(before));
    const char *error = NULL;
    check(!parse_apply(json, 9999, &error) && error && error[0] &&
          memcmp(before, panel_slot, sizeof(before)) == 0, what);
}

int main(void) {
    alarm(30);

    printf("create and update in place\n");
    reset_store();
    bool created = false;
    check(apply("weather", "Today", "Sunny", 30, true, 7, 100, &created),
          "create is accepted");
    int first = panel_find("weather");
    check(created && first >= 0, "create reports a new entry");
    check(apply("weather", "Tomorrow", "Rain", 60, false, 0, 200, &created),
          "upsert is accepted");
    check(!created && panel_find("weather") == first, "upsert keeps its slot");
    check(strcmp(panel_slot[first].title, "Tomorrow") == 0 &&
          strcmp(panel_slot[first].payload.body, "Rain") == 0 &&
          panel_slot[first].ttl_s == 60 && panel_slot[first].arrived_ms == 200,
          "upsert replaces content, ttl, and arrival");

    printf("position is create-only\n");
    check(panel_slot[first].pos == 7, "create stores the supplied position");
    check(apply("weather", "Again", "Wind", 10, true, -99, 300),
          "update with an explicit position is accepted");
    check(panel_slot[first].pos == 7, "update ignores position and keeps it sticky");
    check(apply("default", "Default", "Here", 0, false, 123, 301),
          "create without position is accepted");
    check(panel_slot[panel_find("default")].pos == 0, "missing position defaults to zero");

    printf("capacity and admission policy\n");
    reset_store();
    char key[8];
    for (int i = 0; i < PANEL_MAX; i++) {
        snprintf(key, sizeof(key), "k%d", i);
        check(apply(key, "t", "b", 0, true, i, 100U + (unsigned)i),
              "fill slot");
    }
    check(apply("ninth", "t", "b", 0, false, 0, 200), "ninth entry is admitted");
    check(panel_find("k0") < 0 && panel_find("ninth") >= 0,
          "a full store evicts the oldest arrival");

    reset_store();
    for (int i = 0; i < PANEL_MAX; i++) {
        snprintf(key, sizeof(key), "f%d", i);
        apply(key, "t", "b", 0, false, 0, 100U + (unsigned)i);
    }
    int free_target = panel_find("f3");
    apply("f3", "", "", 0, false, 0, 200);
    apply("free", "t", "b", 0, false, 0, 201);
    check(panel_find("free") == free_target && panel_find("f0") >= 0,
          "a free slot is preferred to eviction");

    reset_store();
    for (int i = 0; i < PANEL_MAX; i++) {
        snprintf(key, sizeof(key), "e%d", i);
        apply(key, "t", "b", i == 5 ? 1U : 0U, false, 0,
              1000U + (unsigned)i);
    }
    int expired_target = panel_find("e5");
    apply("expired", "t", "b", 0, false, 0, 3000);
    check(panel_find("expired") == expired_target && panel_find("e0") >= 0,
          "an expired slot is preferred to the oldest live entry");

    printf("deterministic response order\n");
    Panel ordered[3];
    panel_prepare(ordered[0], "z", "t", "b", 0, 2);
    panel_prepare(ordered[1], "b", "t", "b", 0, 1);
    panel_prepare(ordered[2], "a", "t", "b", 0, 1);
    panel_sort(ordered, 3);
    check(strcmp(ordered[0].key, "a") == 0 &&
          strcmp(ordered[1].key, "b") == 0 &&
          strcmp(ordered[2].key, "z") == 0,
          "panels sort by position and then key");

    printf("ttl boundaries on the 64-bit monotonic clock\n");
    Panel p = {};
    snprintf(p.key, sizeof(p.key), "ttl");
    p.ttl_s = 0;
    p.arrived_ms = 10;
    check(!panel_expired(p, UINT64_C(9000000000000)), "ttl zero never expires");
    p.ttl_s = 2;
    p.arrived_ms = 1000;
    check(!panel_expired(p, 2999), "one millisecond before deadline is live");
    check(panel_expired(p, 3000), "the exact deadline is expired");
    p.ttl_s = 1;
    p.arrived_ms = UINT64_C(0xFFFFFF00);
    check(!panel_expired(p, UINT64_C(0x1000002E7)),
          "crossing the old 32-bit boundary remains live before deadline");
    check(panel_expired(p, UINT64_C(0x1000002E8)),
          "crossing the old 32-bit boundary expires at the deadline");

    p.ttl_s = UINT32_MAX;
    p.arrived_ms = 1000;
    uint64_t long_deadline = p.arrived_ms + (uint64_t)p.ttl_s * 1000ULL;
    check(!panel_expired(p, long_deadline - 1),
          "the full uint32 ttl is live one millisecond before deadline");
    check(panel_expired(p, long_deadline),
          "the full uint32 ttl expires at its exact deadline");
    check(panel_expired(p, long_deadline + UINT64_C(31536000000)),
          "a long ttl remains expired a year after its deadline");
    p.arrived_ms = 1001;
    check(!panel_expired(p, 1000), "a stamp just ahead of the sampled clock is fresh");

    printf("interleaved clock sampling regression\n");
    reset_store();
    panel_prepare(panel_slot[0], "fresh", "t", "b", 1, 0);
    panel_slot[0].arrived_ms = 1001;
    Panel snapshot[PANEL_MAX];
    check(panel_snapshot(snapshot, 1000) == 1 &&
          strcmp(snapshot[0].key, "fresh") == 0,
          "a future-stamped fresh entry remains in a GET snapshot");
    check(!panel_reap(1000) && panel_find("fresh") == 0,
          "a future-stamped fresh entry is not deleted by polling");

    for (int i = 1; i < PANEL_MAX; i++) {
        snprintf(key, sizeof(key), "a%d", i);
        panel_prepare(panel_slot[i], key, "t", "b", 0, 0);
        panel_slot[i].arrived_ms = 900U + (unsigned)i;
    }
    check(panel_admit(1000) != 0,
          "admission does not misclassify a future stamp as the oldest entry");

    printf("oldest eviction after months\n");
    reset_store();
    const uint64_t months_now = UINT64_C(10000000000);
    for (int i = 0; i < PANEL_MAX; i++) {
        snprintf(key, sizeof(key), "m%d", i);
        panel_prepare(panel_slot[i], key, "t", "b", 0, 0);
        panel_slot[i].arrived_ms = months_now - UINT64_C(1000000) + (unsigned)i;
    }
    panel_slot[4].arrived_ms = months_now - (UINT64_C(1) << 31) - 5000;
    check(panel_age(panel_slot[4], months_now) > (UINT64_C(1) << 31),
          "an indefinite panel keeps an age beyond the old signed half-range");
    check(panel_admit(months_now) == 4,
          "the months-old indefinite panel is still the oldest eviction victim");

    printf("delete semantics\n");
    reset_store();
    bool deleted = false;
    apply("gone", "t", "b", 0, false, 0, 1);
    check(apply("gone", "", "", 0, false, 0, 2, NULL, &deleted) && deleted,
          "empty body deletes an existing key without a title");
    check(panel_find("gone") < 0, "deleted key is absent");
    check(!apply("missing", "", "", 0, false, 0, 3),
          "empty body refuses a missing key");

    printf("key validation\n");
    const char *err = NULL;
    check(panel_key_check("1234567890123456", &err), "a 16-byte key is accepted");
    bad_key("12345678901234567", "a 17-byte key is rejected without truncation");
    bad_key("   ", "an all-space key is rejected");
    bad_key("line\nbreak", "a control byte is rejected");
    bad_key("caf\xC3\xA9", "a non-ASCII key is rejected");

    printf("shared text copy boundaries\n");
    reset_store();
    char long_title[80];
    memset(long_title, 'a', 63);
    memcpy(long_title + 63, "\xE2\x82\xAC", 4);
    char long_body[280];
    memset(long_body, 'b', 255);
    memcpy(long_body + 255, "\xE2\x82\xAC", 4);
    apply("utf", long_title, long_body, 0, false, 0, 1);
    int utf = panel_find("utf");
    check(strlen(panel_slot[utf].title) == 63,
          "title truncation drops an incomplete UTF-8 character");
    check(strlen(panel_slot[utf].payload.body) == 255,
          "body truncation drops an incomplete UTF-8 character");
    apply("utf", "a\nb", "x\ty", 0, false, 0, 2);
    check(strcmp(panel_slot[utf].title, "a b") == 0 &&
          strcmp(panel_slot[utf].payload.body, "x y") == 0,
          "title and body use the shared text copier's control-byte rule");

    printf("typed payloads and kind transitions\n");
    Panel typed = {};
    snprintf(typed.key, sizeof(typed.key), "typed");
    snprintf(typed.title, sizeof(typed.title), "Metrics");
    typed.kind = PANEL_KIND_KV;
    typed.payload.kv.count = PANEL_KV_MAX;
    for (int i = 0; i < PANEL_KV_MAX; i++) {
        snprintf(typed.payload.kv.items[i].label, PANEL_LABEL_LEN, "label%d", i);
        snprintf(typed.payload.kv.items[i].value, PANEL_VALUE_LEN, "value%d", i);
    }
    const char *apply_error = NULL;
    check(panel_core_apply(typed, false, true, 500, &created, NULL, &apply_error) &&
          panel_slot[panel_find("typed")].kind == PANEL_KIND_KV &&
          panel_slot[panel_find("typed")].payload.kv.count == PANEL_KV_MAX,
          "a maximum kv payload is stored by the shipping apply path");
    int typed_slot = panel_find("typed");
    typed.kind = PANEL_KIND_STATUS;
    memset(&typed.payload, 0, sizeof(typed.payload));
    snprintf(typed.payload.status.value, PANEL_STATUS_LEN, "ONLINE");
    snprintf(typed.payload.status.unit, PANEL_UNIT_LEN, "nodes");
    snprintf(typed.payload.status.detail, PANEL_DETAIL_LEN, "All systems nominal");
    typed.pos = -100;
    check(panel_core_apply(typed, false, true, 501, &created, NULL, &apply_error) &&
          panel_find("typed") == typed_slot &&
          panel_slot[typed_slot].kind == PANEL_KIND_STATUS &&
          strcmp(panel_slot[typed_slot].payload.status.value, "ONLINE") == 0,
          "an update changes kind and replaces the fixed union in place");
    check(panel_slot[typed_slot].pos == 0,
          "a kind transition keeps the original sticky position");

    printf("typed validation boundaries\n");
    check(panel_kind_valid(PANEL_KIND_TEXT) && panel_kind_valid(PANEL_KIND_STATUS) &&
          !panel_kind_valid((PanelKind)99), "only the five declared kinds are valid");
    PanelKind parsed_kind = PANEL_KIND_TEXT;
    check(panel_kind_parse("sparkline", &parsed_kind) &&
          parsed_kind == PANEL_KIND_SPARKLINE &&
          !panel_kind_parse("chart", &parsed_kind),
          "kind parsing accepts the contract and rejects unknown names");
    check(panel_field_allowed(PANEL_KIND_TEXT, "body") &&
          !panel_field_allowed(PANEL_KIND_TEXT, "items") &&
          panel_field_allowed(PANEL_KIND_BARS, "items") &&
          !panel_field_allowed(PANEL_KIND_BARS, "body"),
          "top-level field validation changes with kind");
    check(panel_nested_field_allowed(PANEL_KIND_KV, "value") &&
          !panel_nested_field_allowed(PANEL_KIND_KV, "unit") &&
          panel_nested_field_allowed(PANEL_KIND_BARS, "unit") &&
          !panel_nested_field_allowed(PANEL_KIND_BARS, "extra"),
          "nested item validation rejects unknown fields");
    char exact_label[17] = "1234567890123456";
    char long_label[18] = "12345678901234567";
    check(panel_string_check(exact_label, 1, 16, &err, "bad") &&
          !panel_string_check(long_label, 1, 16, &err, "bad"),
          "structured strings accept the exact maximum and reject max plus one");
    check(panel_bar_values_check(0.0f, 1.0f) &&
          panel_bar_values_check(1.0e9f, 1.0e9f) &&
          !panel_bar_values_check(-1.0f, 1.0f) &&
          !panel_bar_values_check(2.0f, 1.0f) &&
          !panel_bar_values_check(0.0f, 0.0f) &&
          !panel_bar_values_check(-1.0e-50, 1.0) &&
          !panel_bar_values_check(0.0, 1000000001.0) &&
          !panel_bar_values_check(NAN, 1.0f) &&
          !panel_bar_values_check(1.0f, INFINITY),
          "bar numeric boundaries and non-finite values use shipping validation");
    check(panel_spark_value_check(-1.0e9f) && panel_spark_value_check(1.0e9f) &&
          !panel_spark_value_check(-1.1e9f) && !panel_spark_value_check(1.1e9f) &&
          !panel_spark_value_check(-1000000001.0) &&
          !panel_spark_value_check(1000000001.0) &&
          !panel_spark_value_check(NAN) && !panel_spark_value_check(INFINITY),
          "sparkline numeric boundaries and non-finite values use shipping validation");

    printf("shipping JSON parser and no-mutation failures\n");
    reset_store();
    check(parse_apply("{\"key\":\"legacy\",\"title\":\"Old\",\"body\":\"Body\",\"pos\":4}", 1) &&
          panel_slot[panel_find("legacy")].kind == PANEL_KIND_TEXT,
          "missing kind preserves the legacy text contract");
    check(parse_apply("{\"key\":\"kv\",\"title\":\"KV\",\"kind\":\"kv\",\"items\":[{\"label\":\"a\",\"value\":\"1\"}]}", 2),
          "the shipping parser creates kv");
    check(parse_apply("{\"key\":\"bars\",\"title\":\"Bars\",\"kind\":\"bars\",\"items\":[{\"label\":\"a\",\"value\":0,\"max\":1},{\"label\":\"b\",\"value\":1000000000,\"max\":1000000000,\"unit\":\"W\"}]}", 3),
          "the shipping parser accepts bar numeric boundaries");
    check(parse_apply("{\"key\":\"spark\",\"title\":\"Spark\",\"kind\":\"sparkline\",\"values\":[-1000000000,1000000000],\"unit\":\"USD\"}", 4),
          "the shipping parser creates a boundary sparkline");
    check(parse_apply("{\"key\":\"status\",\"title\":\"Status\",\"kind\":\"status\",\"value\":\"ONLINE\",\"unit\":\"nodes\",\"detail\":\"All good\"}", 5),
          "the shipping parser creates status");
    check(parse_apply("{\"key\":\"legacy\",\"title\":\"Now status\",\"kind\":\"status\",\"value\":\"OK\",\"pos\":-8}", 6) &&
          panel_slot[panel_find("legacy")].kind == PANEL_KIND_STATUS &&
          panel_slot[panel_find("legacy")].pos == 4,
          "the shipping parser changes kind while apply keeps position sticky");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"chart\",\"body\":\"x\"}",
                             "unknown kind returns an error without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"status\",\"value\":\"x\",\"body\":\"unknown\"}",
                             "unknown top-level field returns an error without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"kv\",\"items\":[{\"label\":\"x\",\"value\":\"y\",\"extra\":1}]}",
                             "unknown nested field returns an error without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"kv\",\"items\":[{\"label\":\"12345678901234567\",\"value\":\"y\"}]}",
                             "max plus one label bytes are rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"kv\",\"items\":[{\"label\":\"x\",\"value\":\"123456789012345678901234567890123\"}]}",
                             "max plus one kv value bytes are rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"bars\",\"items\":[{\"label\":\"x\",\"value\":\"1\",\"max\":2}]}",
                             "a numeric string is rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"sparkline\",\"values\":[true,2]}",
                             "a boolean numeric impostor is rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"bars\",\"items\":[{\"label\":\"x\",\"value\":0,\"max\":1000000001}]}",
                             "bar max just above 1e9 is rejected before float rounding without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"bars\",\"items\":[{\"label\":\"x\",\"value\":-1e-50,\"max\":1}]}",
                             "tiny negative bar value is rejected before float underflow without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"sparkline\",\"values\":[0,1000000001]}",
                             "sparkline just above 1e9 is rejected before float rounding without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"sparkline\",\"values\":[-1000000001,0]}",
                             "sparkline just below minus 1e9 is rejected before float rounding without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"kv\",\"items\":[]}",
                             "zero kv items are rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"kv\",\"items\":[{\"label\":\"1\",\"value\":\"1\"},{\"label\":\"2\",\"value\":\"2\"},{\"label\":\"3\",\"value\":\"3\"},{\"label\":\"4\",\"value\":\"4\"},{\"label\":\"5\",\"value\":\"5\"},{\"label\":\"6\",\"value\":\"6\"}]}",
                             "max plus one kv items are rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"status\",\"value\":\"1234567890123456789012345\"}",
                             "max plus one status value bytes are rejected without mutation");
    check(parse_apply("{\"key\":\"limits\",\"title\":\"Limits\",\"kind\":\"status\",\"value\":\"123456789012345678901234\",\"unit\":\"12345678\",\"detail\":\"1234567890123456789012345678901234567890123456789012345678901234\"}", 7),
          "status accepts exact maximum string lengths");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"status\",\"value\":\"x\",\"unit\":\"123456789\"}",
                             "max plus one unit bytes are rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"status\",\"value\":\"x\",\"detail\":\"12345678901234567890123456789012345678901234567890123456789012345\"}",
                             "max plus one detail bytes are rejected without mutation");
    std::string max_kv = "{\"key\":\"maxkv\",\"title\":\"KV\",\"kind\":\"kv\",\"items\":[";
    for (int i = 0; i < PANEL_KV_MAX; i++) {
        if (i) max_kv += ",";
        max_kv += "{\"label\":\"1234567890123456\",\"value\":\"12345678901234567890123456789012\"}";
    }
    max_kv += "]}";
    check(parse_apply(max_kv.c_str(), 8) &&
          panel_slot[panel_find("maxkv")].payload.kv.count == PANEL_KV_MAX,
          "kv accepts maximum count and exact maximum strings");
    std::string max_bars = "{\"key\":\"maxbars\",\"title\":\"Bars\",\"kind\":\"bars\",\"items\":[";
    for (int i = 0; i < PANEL_BAR_MAX; i++) {
        if (i) max_bars += ",";
        max_bars += "{\"label\":\"1234567890123456\",\"value\":1,\"max\":1,\"unit\":\"12345678\"}";
    }
    max_bars += "]}";
    check(parse_apply(max_bars.c_str(), 9) &&
          panel_slot[panel_find("maxbars")].payload.bars.count == PANEL_BAR_MAX,
          "bars accepts maximum count and exact maximum strings");
    std::string too_many_bars = max_bars;
    too_many_bars.insert(too_many_bars.size() - 2,
                         ",{\"label\":\"fifth\",\"value\":1,\"max\":1}");
    invalid_without_mutation(too_many_bars.c_str(),
                             "max plus one bars are rejected without mutation");
    std::string max_spark = "{\"key\":\"maxspark\",\"title\":\"Spark\",\"kind\":\"sparkline\",\"values\":[";
    for (int i = 0; i < PANEL_SPARK_MAX; i++) {
        if (i) max_spark += ",";
        max_spark += std::to_string(i);
    }
    max_spark += "]}";
    check(parse_apply(max_spark.c_str(), 10) &&
          panel_slot[panel_find("maxspark")].payload.sparkline.count == PANEL_SPARK_MAX,
          "sparkline accepts its maximum count");
    std::string too_many_spark = max_spark;
    too_many_spark.insert(too_many_spark.size() - 2, ",49");
    invalid_without_mutation(too_many_spark.c_str(),
                             "max plus one sparkline values are rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"kind\":\"sparkline\",\"values\":[1]}",
                             "one sparkline value is rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"body\":\"x\",\"ttl_s\":4294967296}",
                             "ttl overflow is rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"body\":\"x\",\"ttl_s\":1.5}",
                             "non-integer ttl is rejected without mutation");
    invalid_without_mutation("{\"key\":\"legacy\",\"title\":\"bad\",\"body\":\"x\",\"pos\":2147483648}",
                             "position overflow is rejected without mutation");
    check(parse_apply("{\"key\":\"status\",\"kind\":\"text\",\"body\":\"\"}", 11) &&
          panel_find("status") < 0, "explicit text keeps empty-body deletion");

    printf("GET serialization contract\n");
    Panel serialized = {};
    snprintf(serialized.key, PANEL_KEY_LEN, "out");
    snprintf(serialized.title, PANEL_TITLE_LEN, "Output");
    serialized.ttl_s = 10;
    serialized.pos = -2;
    serialized.kind = PANEL_KIND_TEXT;
    snprintf(serialized.payload.body, PANEL_BODY_LEN, "hello");
    JsonDocument output;
    panel_serialize(output.to<JsonObject>(), serialized);
    JsonObjectConst view = output.as<JsonObjectConst>();
    check(strcmp(view["kind"].as<const char*>(), "text") == 0 &&
          strcmp(view["body"].as<const char*>(), "hello") == 0,
          "text GET output adds kind and retains body");
    serialized.kind = PANEL_KIND_KV;
    memset(&serialized.payload, 0, sizeof(serialized.payload));
    serialized.payload.kv.count = 1;
    snprintf(serialized.payload.kv.items[0].label, PANEL_LABEL_LEN, "A");
    snprintf(serialized.payload.kv.items[0].value, PANEL_VALUE_LEN, "B");
    output.clear(); panel_serialize(output.to<JsonObject>(), serialized);
    view = output.as<JsonObjectConst>();
    check(strcmp(view["kind"].as<const char*>(), "kv") == 0 &&
          view["body"].isUnbound() && view["items"].is<JsonArrayConst>() &&
          view["items"].as<JsonArrayConst>().size() == 1,
          "kv GET output emits items and never an empty body");
    serialized.kind = PANEL_KIND_BARS;
    memset(&serialized.payload, 0, sizeof(serialized.payload));
    serialized.payload.bars.count = 1;
    snprintf(serialized.payload.bars.items[0].label, PANEL_LABEL_LEN, "Load");
    serialized.payload.bars.items[0].value = 1.0f;
    serialized.payload.bars.items[0].max = 2.0f;
    output.clear(); panel_serialize(output.to<JsonObject>(), serialized);
    view = output.as<JsonObjectConst>();
    check(strcmp(view["kind"].as<const char*>(), "bars") == 0 &&
          view["body"].isUnbound() && view["items"].is<JsonArrayConst>(),
          "bars GET output emits typed items and no body");
    serialized.kind = PANEL_KIND_SPARKLINE;
    memset(&serialized.payload, 0, sizeof(serialized.payload));
    serialized.payload.sparkline.count = 2;
    serialized.payload.sparkline.values[0] = 1.0f;
    serialized.payload.sparkline.values[1] = 2.0f;
    output.clear(); panel_serialize(output.to<JsonObject>(), serialized);
    view = output.as<JsonObjectConst>();
    check(strcmp(view["kind"].as<const char*>(), "sparkline") == 0 &&
          view["body"].isUnbound() && view["values"].as<JsonArrayConst>().size() == 2,
          "sparkline GET output emits values and no body");
    serialized.kind = PANEL_KIND_STATUS;
    memset(&serialized.payload, 0, sizeof(serialized.payload));
    snprintf(serialized.payload.status.value, PANEL_STATUS_LEN, "OK");
    output.clear(); panel_serialize(output.to<JsonObject>(), serialized);
    view = output.as<JsonObjectConst>();
    check(strcmp(view["kind"].as<const char*>(), "status") == 0 &&
          view["body"].isUnbound() && strcmp(view["value"].as<const char*>(), "OK") == 0,
          "status GET output emits value and no body");

    printf("sizeof Panel: %zu bytes\n", sizeof(Panel));
    check(sizeof(Panel) == 360, "Panel has the pinned ESP32 layout on this host");
    check(sizeof(panel_slot) == 2880, "the eight-slot store remains exactly 2880 bytes");

    if (failures) {
        printf("FAILED: %d check(s)\n", failures);
        return 1;
    }
    printf("all panel core checks passed\n");
    return 0;
}
TESTS
} > "$work/test_panel.cpp"

c++ -std=c++17 -Wall -Wextra -Werror -I"$arduinojson" \
    "$work/test_panel.cpp" -o "$work/test_panel"
"$work/test_panel"

echo "HTTP source gates"
for field in key title body ttl_s pos; do
    variable="${field}_value"
    [ "$field" = "ttl_s" ] && variable="ttl_value"
    grep -Fq "$variable.is<" "$src" || {
        echo "  FAIL: $field has no strict JSON type gate"
        exit 1
    }
    echo "  ok:   $field has a strict JSON type gate"
done

grep -Fq 'server.on(AsyncURIMatcher::exact("/panel"), HTTP_GET' "$src"
grep -Fq 'server.on(AsyncURIMatcher::exact("/panel"), HTTP_POST' "$src"
grep -Fq '}, NULL, handle_body_collect);' "$src"
echo "  ok:   GET and POST use exact /panel routes; POST collects its body"

include_line=$(grep -n '#include "skills/panel.cpp"' "$main" | cut -d: -f1)
notify_line=$(grep -n '#include "skills/notify.cpp"' "$main" | cut -d: -f1)
[ "$include_line" -eq $((notify_line + 1)) ]
grep -Fq 'skill_panel_init();' "$main"
grep -Fq 'panel_poll();' "$main"
echo "  ok:   main includes, initializes, and polls the panel skill"

for function in panel_send_list panel_send_post panel_poll; do
    function_span=$(awk -v name="$function" '
        $0 ~ ("^static void " name "\\(") { grab = 1 }
        grab { print }
        grab && /^}/ { exit }
    ' "$src")
    lock_line=$(printf '%s\n' "$function_span" | grep -n 'portENTER_CRITICAL' | cut -d: -f1)
    now_line=$(printf '%s\n' "$function_span" | grep -n 'panel_now_ms()' | cut -d: -f1)
    [ -n "$lock_line" ] && [ -n "$now_line" ] && [ "$now_line" -gt "$lock_line" ] || {
        echo "  FAIL: $function samples the monotonic clock before taking panel_mux"
        exit 1
    }
done
echo "  ok:   GET, POST, and expiry poll sample the monotonic clock under panel_mux"

post_span=$(awk '
    /^static void panel_send_post\(/ { grab = 1 }
    grab { print }
    grab && /^}/ { exit }
' "$src")
registration_span=$(awk '
    /server\.on\(AsyncURIMatcher::exact\("\/panel"\), HTTP_POST/ { grab = 1 }
    grab { print }
    grab && /}, NULL, handle_body_collect\);/ { exit }
' "$src")
for forbidden in ui_note_input ui_last_input draw wake backlight; do
    if printf '%s\n%s\n' "$post_span" "$registration_span" | grep -qi "$forbidden"; then
        echo "  FAIL: POST /panel span touches forbidden '$forbidden'"
        exit 1
    fi
done
echo "  ok:   POST /panel span has no input, draw, wake, or backlight side effect"

[ "$(grep -c 'host-test:begin' "$src")" -eq 1 ]
[ "$(grep -c 'host-test:end' "$src")" -eq 1 ]
echo "  ok:   panel shipping core has exactly one marker pair"
