#!/usr/bin/env bash
#
# Host-side regression test for the WAV header WRITER in src/skills/mic.cpp.
#
# Why this exists: a recording that comes back unplayable is expensive to
# diagnose on hardware, because every layer between the microphone and the
# speaker is equally suspect — and a header with one field at the wrong offset
# looks exactly like a capture bug. Forty-four bytes of little-endian integers
# is pure computation over a byte buffer, so it can be settled here in a second
# instead of on a device with a knob.
#
# The interesting part is the round trip. The writer in mic.cpp and the strict
# parser in sound.cpp are separate code that has to agree byte for byte, and
# both are sliced straight out of the shipping sources between their
# `host-test:begin` and `host-test:end` markers — so this tests the two real
# implementations against each other rather than two copies that could drift
# apart. If somebody moves a field in one and not the other, this fails.
#
# Note the parser is stricter than the writer needs to be: sound.cpp caps an
# uploaded cue at SND_DATA_MAX (96KB), which is the speaker's own limit and has
# nothing to say about a 320KB recording. So the round-trip cases stay under
# that cap and the large ones are checked field by field instead.
#
# Usage: tools/test_wav_header.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mic="$here/../src/skills/mic.cpp"
snd="$here/../src/skills/sound.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$mic" ] || { echo "cannot find $mic"; exit 1; }
[ -f "$snd" ] || { echo "cannot find $snd"; exit 1; }

# Slice a marked region out of a firmware source.
slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_wav_header.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

/* The firmware constants the sliced code and the cases below need, grepped
   from the sources so they cannot drift from the shipping values. */
PRELUDE
    grep -E '^#define SND_DATA_MAX' "$snd"
    grep -E '^#define MIC_RATE|^#define MIC_FRAME_BYTES|^#define MIC_MAX_SEC|^#define MIC_MAX_BYTES' "$mic"
    echo
    slice "$mic" wavhdr
    echo
    slice "$snd" rates
    echo
    slice "$snd" wav
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

static void check_eq(unsigned long got, unsigned long want, const char *what) {
    if (got != want) {
        printf("  FAIL: %s (got %lu, want %lu)\n", what, got, want);
        failures++;
    } else {
        printf("  ok:   %s\n", what);
    }
}

/* Read the header back the way any other program would, rather than with the
   writer's own helpers — a shared byte order bug would otherwise cancel out. */
static uint32_t rd32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static uint16_t rd16(const uint8_t *p) {
    return (uint16_t)(p[0] | ((uint16_t)p[1] << 8));
}

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    uint8_t b[MIC_WAV_HDR_LEN + 32];

    printf("the header is exactly 44 bytes and writes no further\n");
    {
        /* Guard bytes on both sides, so a writer that ran long is caught here
           rather than by whatever it corrupted on the device. */
        memset(b, 0xA5, sizeof(b));
        mic_wav_header(b + 8, MIC_RATE, 32000);
        int lead_ok = 1, trail_ok = 1;
        for (int i = 0; i < 8; i++) if (b[i] != 0xA5) lead_ok = 0;
        for (size_t i = 8 + MIC_WAV_HDR_LEN; i < sizeof(b); i++)
            if (b[i] != 0xA5) trail_ok = 0;
        check(lead_ok, "nothing written before the buffer");
        check(trail_ok, "nothing written after 44 bytes");
        check_eq(MIC_WAV_HDR_LEN, 44, "the header length constant is 44");
    }

    printf("every field at every documented offset\n");
    {
        const uint32_t data_len = 32000;   /* one second at 16kHz mono */
        mic_wav_header(b, MIC_RATE, data_len);

        check(memcmp(b + 0, "RIFF", 4) == 0, "offset 0  is \"RIFF\"");
        check_eq(rd32(b + 4), 36 + data_len, "offset 4  is 36 + data length");
        check(memcmp(b + 8, "WAVE", 4) == 0, "offset 8  is \"WAVE\"");
        check(memcmp(b + 12, "fmt ", 4) == 0, "offset 12 is \"fmt \" (with the space)");
        check_eq(rd32(b + 16), 16, "offset 16 is 16, the PCM fmt body length");
        check_eq(rd16(b + 20), 1, "offset 20 is 1, WAVE_FORMAT_PCM");
        check_eq(rd16(b + 22), 1, "offset 22 is 1 channel");
        check_eq(rd32(b + 24), MIC_RATE, "offset 24 is the sample rate");
        check_eq(rd32(b + 28), MIC_RATE * 2, "offset 28 is the byte rate, rate * 2");
        check_eq(rd16(b + 32), 2, "offset 32 is the block align, 2");
        check_eq(rd16(b + 34), 16, "offset 34 is 16 bits per sample");
        check(memcmp(b + 36, "data", 4) == 0, "offset 36 is \"data\"");
        check_eq(rd32(b + 40), data_len, "offset 40 is the data length");
    }

    printf("byte for byte against a hand-written reference\n");
    {
        /* The whole header for one known case, computed by hand rather than by
           the code under test. This is the check that a field swapped with its
           neighbour cannot pass, because both would still be "the right value
           somewhere". */
        static const uint8_t want[MIC_WAV_HDR_LEN] = {
            'R','I','F','F', 0x24,0x7D,0x00,0x00, 'W','A','V','E',
            'f','m','t',' ', 0x10,0x00,0x00,0x00, 0x01,0x00, 0x01,0x00,
            0x80,0x3E,0x00,0x00, 0x00,0x7D,0x00,0x00, 0x02,0x00, 0x10,0x00,
            'd','a','t','a', 0x00,0x7D,0x00,0x00,
        };
        mic_wav_header(b, 16000, 32000);
        check(memcmp(b, want, MIC_WAV_HDR_LEN) == 0,
              "16kHz / 32000 bytes matches the reference header exactly");
    }

    printf("the length arithmetic holds across the whole capture range\n");
    {
        /* Every take the firmware can produce, at one-frame granularity near
           the interesting ends and coarsely in between. */
        static const uint32_t lens[] = {
            0, 2, 4, 32, 320, 32000, 65536, 96000,
            MIC_MAX_BYTES - 2, MIC_MAX_BYTES,
        };
        int riff_ok = 1, data_ok = 1;
        for (size_t i = 0; i < sizeof(lens) / sizeof(lens[0]); i++) {
            mic_wav_header(b, MIC_RATE, lens[i]);
            if (rd32(b + 4) != 36 + lens[i]) riff_ok = 0;
            if (rd32(b + 40) != lens[i]) data_ok = 0;
        }
        check(riff_ok, "RIFF size is 36 + data length at every size");
        check(data_ok, "data size is the length asked for at every size");

        /* The ceiling is nowhere near where either field would wrap, and that
           is the reason the writer can take the length verbatim. */
        check(MIC_MAX_BYTES == (uint32_t)MIC_RATE * MIC_FRAME_BYTES * MIC_MAX_SEC,
              "the capacity constant is rate * frame * seconds");
        check((uint64_t)MIC_MAX_BYTES + 36 < 0xFFFFFFFFull,
              "36 + the largest take cannot overflow the RIFF size field");
        check((uint64_t)MIC_RATE * 2 < 0xFFFFFFFFull,
              "the byte rate cannot overflow its field");
    }

    printf("round trip: what mic.cpp writes, sound.cpp's parser reads\n");
    {
        /* The two are separate implementations of the same 44 bytes and this
           is the only thing that keeps them honest. Sizes stay under
           SND_DATA_MAX because that cap is the speaker's upload limit, not a
           statement about the format — see the note at the top. */
        static const uint32_t lens[] = {2, 320, 32000, 65536, SND_DATA_MAX};
        for (size_t i = 0; i < sizeof(lens) / sizeof(lens[0]); i++) {
            SndWav w;
            const char *err = NULL;
            char msg[80];

            mic_wav_header(b, MIC_RATE, lens[i]);
            memset(&w, 0, sizeof(w));
            snprintf(msg, sizeof(msg), "%lu-byte take parses", (unsigned long)lens[i]);
            check(snd_wav_parse(b, MIC_WAV_HDR_LEN, w, &err), msg);
            snprintf(msg, sizeof(msg), "  ...rate reads back as %lu", (unsigned long)MIC_RATE);
            check_eq(w.rate, MIC_RATE, msg);
            check_eq(w.data_len, lens[i], "  ...data length reads back unchanged");
            check_eq(w.data_off, MIC_WAV_HDR_LEN, "  ...audio starts at byte 44");
        }
    }

    printf("the parser's own limits, confirmed rather than assumed\n");
    {
        /* Not a defect in either side: it is why the round-trip cases above
           stop where they do, and it is worth failing loudly if the cap ever
           moves without this note moving with it. */
        SndWav w;
        const char *err = NULL;
        mic_wav_header(b, MIC_RATE, MIC_MAX_BYTES);
        check(!snd_wav_parse(b, MIC_WAV_HDR_LEN, w, &err),
              "a full 10s take is refused by the speaker's 96KB upload cap");
        check(err != NULL, "  ...with a reason");

        err = NULL;
        mic_wav_header(b, MIC_RATE, 0);
        check(!snd_wav_parse(b, MIC_WAV_HDR_LEN, w, &err),
              "an empty take is refused (zero-length data)");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test"
