#!/usr/bin/env bash
#
# Host-side test for the persisted event log in src/main.cpp.
#
# Why this exists: the log is the only record of what the device did before
# its last reboot, and both halves of it run where nobody watches — the append
# on every event_add, the replay once at boot. A format the writer emits but
# the reader rejects loses history silently; a reader that trusts the file
# crashes the boot it was meant to inform. The five functions under test are
# the whole of that contract: escape, format, parse, the rotation alignment
# and the since matcher that keeps GET /events sane across a reboot. They are
# sliced straight out of the shipping source between its
# `host-test:begin events` and `host-test:end` markers (plus the
# TIME_VALID_EPOCH define, grepped out separately), so this runs the real
# implementation rather than a copy that could drift.
#
# What this DOES NOT cover, said plainly rather than papered over:
#
#   - the flash itself. events_log_append(), events_log_rotate() and
#     events_log_replay() need SPIFFS, the Arduino String and a reboot, none of
#     which exists here. What IS here is every byte they write and everything
#     they accept back: if the line round-trips through parse and the rotation
#     offset lands on a line boundary, the untested half is plumbing.
#   - the ring wiring. That replay fills the oldest entries first and that the
#     append carries the same timestamp GET /events serves are read off the
#     source in review, not executed.
#
# Every check below was verified by reintroducing the defect it claims to
# catch, except the sweep counters, which count the test's own loop so that a
# gutted sweep cannot go on reporting zero differences over nothing.
#
# Usage: tools/test_events.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/main.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_events.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

PRELUDE
    # The wall-clock gate the since matcher shares with the firmware. Grepped
    # rather than duplicated, so a changed epoch breaks the build here instead
    # of silently testing another threshold.
    grep -E '^#define TIME_VALID_EPOCH[[:space:]]' "$src" || { echo "TIME_VALID_EPOCH not found in $src"; exit 1; }
    slice "$src" events
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;
static long checks = 0;

static void check(int cond, const char *what) {
    checks++;
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

static int round_trip(unsigned long ts, unsigned long boot, const char *msg) {
    char line[EVENTS_LINE_MAX];
    events_format_line(ts, boot, msg, line, sizeof(line));
    unsigned long pts = 0;
    unsigned long pboot = 0;
    char pmsg[128];
    memset(pmsg, 0xAA, sizeof(pmsg));
    if (!events_parse_line(line, &pts, &pboot, pmsg, sizeof(pmsg))) return 0;
    return pts == ts && pboot == boot && strcmp(pmsg, msg) == 0;
}

int main(void) {
    printf("format matches the GET /events object shape\n");
    {
        char line[EVENTS_LINE_MAX];
        events_format_line(1700000001UL, 7UL, "seed started", line, sizeof(line));
        check(strcmp(line, "{\"ts\":1700000001,\"boot\":7,\"msg\":\"seed started\"}\n") == 0,
              "a plain entry formats exactly");
        events_format_line(0UL, 0UL, "", line, sizeof(line));
        check(strcmp(line, "{\"ts\":0,\"boot\":0,\"msg\":\"\"}\n") == 0,
              "empty message and zero timestamp still format");
    }

    printf("escaping keeps hostile messages inside one JSON string\n");
    {
        char line[EVENTS_LINE_MAX];
        events_format_line(7UL, 2UL, "q\"b\\c", line, sizeof(line));
        check(strcmp(line, "{\"ts\":7,\"boot\":2,\"msg\":\"q\\\"b\\\\c\"}\n") == 0,
              "quote and backslash are escaped");
        check(round_trip(9UL, 4UL, "a\nb\rc\td"), "newline, CR and tab round-trip");
        char ctrl[4];
        ctrl[0] = 'x'; ctrl[1] = 0x01; ctrl[2] = 'y'; ctrl[3] = '\0';
        char esc[32];
        events_escape(ctrl, esc, sizeof(esc));
        check(strcmp(esc, "x\\u0001y") == 0, "other control bytes become \\u00XX");
        check(round_trip(11UL, 1UL, ctrl), "and parse back to the same bytes");
    }

    printf("round-trip over the message space the ring can hold\n");
    {
        long compared = 0, differed = 0;
        char msg[128];
        for (int len = 0; len < 128; len++) {
            for (int k = 0; k < (int)sizeof(msg) - 1; k++)
                msg[k] = (char)(0x20 + ((k * 7 + len) % 0x5F));
            msg[len] = '\0';
            compared++;
            if (!round_trip(1700000000UL + (unsigned)len, (unsigned long)(len % 5), msg)) differed++;
        }
        check(compared == 128, "every length 0..127 is tried");
        check(differed == 0, "and every one survives the round-trip");
        /* Printable ASCII boundary plus the bytes JSON cares about. */
        const char edge[] = " ~\"\x7f\x80\xff\\";
        char line[EVENTS_LINE_MAX];
        events_format_line(3UL, 9UL, edge, line, sizeof(line));
        unsigned long ts = 0;
        unsigned long bt = 0;
        char back[128];
        check(events_parse_line(line, &ts, &bt, back, sizeof(back)) &&
              ts == 3UL && bt == 9UL && strcmp(back, edge) == 0,
              "DEL, high bytes and slashes pass through untouched");
    }

    printf("the parser rejects what the writer never emits\n");
    {
        unsigned long ts = 12345UL;
        unsigned long bt = 999UL;
        char msg[128];
        memset(msg, 'Z', sizeof(msg));
        check(!events_parse_line("", &ts, &bt, msg, sizeof(msg)), "empty string");
        check(!events_parse_line("garbage\n", &ts, &bt, msg, sizeof(msg)), "plain garbage");
        check(!events_parse_line("{\"ts\":abc,\"msg\":\"x\"}", &ts, &bt, msg, sizeof(msg)),
              "non-numeric timestamp");
        check(!events_parse_line("{\"ts\":12}", &ts, &bt, msg, sizeof(msg)), "missing msg");
        check(!events_parse_line("{\"msg\":\"x\"}", &ts, &bt, msg, sizeof(msg)), "missing ts");
        check(!events_parse_line("{\"ts\":12,\"msg\":\"x", &ts, &bt, msg, sizeof(msg)),
              "missing closing quote");
        check(!events_parse_line("{\"ts\":12,\"msg\":\"a\\qb\"}", &ts, &bt, msg, sizeof(msg)),
              "unknown escape");
        check(!events_parse_line("{\"ts\":12,\"msg\":\"a\\u12zb\"}", &ts, &bt, msg, sizeof(msg)),
              "bad \\u digits");
        check(!events_parse_line("{\"ts\":12,\"msg\":\"a\\u1234b\"}", &ts, &bt, msg, sizeof(msg)),
              "\\u outside 00XX");
        check(!events_parse_line("{\"ts\":12,\"msg\":\"a\\", &ts, &bt, msg, sizeof(msg)),
              "truncated escape at end of line");
        check(!events_parse_line("{\"ts\":12,\"boot\":\"x\",\"msg\":\"y\"}", &ts, &bt, msg, sizeof(msg)),
              "non-numeric boot");
        check(!events_parse_line("{\"ts\":12,\"boot\":,\"msg\":\"y\"}", &ts, &bt, msg, sizeof(msg)),
              "empty boot");
        {
            unsigned long lts = 0;
            unsigned long lbt = 77UL;
            char lmsg[128];
            check(events_parse_line("{\"ts\":12,\"msg\":\"x\"}", &lts, &lbt, lmsg, sizeof(lmsg)) &&
                  lts == 12UL && lbt == 0UL && strcmp(lmsg, "x") == 0,
                  "a line from before the epoch parses with boot zero");
            check(events_parse_line("{\"ts\":12,\"boot\":5,\"msg\":\"y\"}", &lts, &lbt, lmsg, sizeof(lmsg)) &&
                  lts == 12UL && lbt == 5UL && strcmp(lmsg, "y") == 0,
                  "a line with an epoch parses with its boot");
            check(events_parse_line("{\"ts\":12, \"boot\" : 6 , \"msg\" : \"z\"}", &lts, &lbt, lmsg, sizeof(lmsg)) &&
                  lts == 12UL && lbt == 6UL && strcmp(lmsg, "z") == 0,
                  "spaces around the boot field are tolerated");
        }
        {
            char raw[32];
            snprintf(raw, sizeof(raw), "{\"ts\":5,\"msg\":\"a%cb\"}", 0x02);
            check(!events_parse_line(raw, &ts, &bt, msg, sizeof(msg)), "raw control byte");
        }
        check(ts == 12345UL, "rejections leave the timestamp alone");
        check(bt == 999UL, "rejections leave the boot alone");
        /* A torn append — the power-loss case — is a prefix of a good line. */
        {
            char line[EVENTS_LINE_MAX];
            events_format_line(99UL, 3UL, "torn tail", line, sizeof(line));
            int torn_rejected = 1;
            /* Every strict prefix: the full line minus its newline is whole
               and must keep parsing, so it is not tried here. */
            for (size_t cut = 0; cut + 1 < strlen(line); cut++) {
                char prefix[EVENTS_LINE_MAX];
                memcpy(prefix, line, cut);
                prefix[cut] = '\0';
                unsigned long t2 = 0;
                unsigned long b2 = 0;
                char m2[128];
                if (events_parse_line(prefix, &t2, &b2, m2, sizeof(m2))) {
                    /* Only the empty prefix-adjacent degenerate parses: none
                       should, so any parse here is a failure. */
                    torn_rejected = 0;
                    break;
                }
            }
            check(torn_rejected, "every torn prefix of a line is rejected");
        }
    }

    printf("oversized entries degrade to a prefix, not a loss\n");
    {
        char line[EVENTS_LINE_MAX];
        /* A small cap still yields a parseable line. */
        char small[64];
        events_format_line(42UL, 3UL, "abcdefghijklmnopqrstuvwxyz", small, sizeof(small));
        unsigned long ts = 0;
        unsigned long bt = 0;
        char msg[128];
        check(events_parse_line(small, &ts, &bt, msg, sizeof(msg)) && ts == 42UL && bt == 3UL,
              "a truncated line still parses with the right timestamp and boot");
        /* A message longer than the ring slot keeps its head on replay. */
        char big[300];
        memset(big, 'w', sizeof(big) - 1);
        big[sizeof(big) - 1] = '\0';
        events_format_line(43UL, 5UL, big, line, sizeof(line));
        char slot[128];
        check(events_parse_line(line, &ts, &bt, slot, sizeof(slot)) && ts == 43UL && bt == 5UL,
              "a long line parses into a 128-byte slot");
        check((int)strlen(slot) == 127 && memcmp(slot, big, 127) == 0,
              "and the slot holds the first 127 bytes");
    }

    printf("the since filter stays sane across a reboot\n");
    {
        /* Numeric behaviour inside one clock domain is unchanged. */
        check(events_since_match(100UL, 4UL, 50UL, 4UL), "a newer timestamp passes");
        check(!events_since_match(40UL, 4UL, 50UL, 4UL), "an older timestamp is filtered");
        check(events_since_match(7UL, 9UL, 6UL, 9UL),
              "a newer same-boot entry passes a monotonic cursor");
        check(!events_since_match(3UL, 9UL, 6UL, 9UL),
              "an older same-boot entry stays filtered by a monotonic cursor");
        /* The reboot case: a wall cursor against a fresh, still-unsynced boot.
           Numerically the new entry reads older; chronologically it is newer,
           and without the exception a poller loses the whole early window. */
        check(events_since_match(5UL, 9UL, TIME_VALID_EPOCH + 500UL, 9UL),
              "this boot's unsynced entry passes a wall cursor");
        check(!events_since_match(5UL, 8UL, TIME_VALID_EPOCH + 500UL, 9UL),
              "an older boot's uptime entry stays filtered");
        check(!events_since_match(5UL, 0UL, TIME_VALID_EPOCH + 500UL, 9UL),
              "a boot-zero entry never takes the exception");
        check(!events_since_match(5UL, 9UL, TIME_VALID_EPOCH + 500UL, 0UL),
              "an unassigned epoch disables the exception");
        check(events_since_match(0UL, 0UL, 0UL, 1UL), "a zero cursor passes everything");
    }

    printf("rotation keeps whole entries\n");
    {
        const char buf[] = "{\"ts\":1,\"msg\":\"a\"}\n{\"ts\":2,\"msg\":\"b\"}\n{\"ts\":3";
        size_t half = 10;  /* lands inside the first line */
        size_t keep = events_align_line(buf, sizeof(buf) - 1, half);
        check(keep == 19, "alignment moves forward to the next line start");
        check(memcmp(buf + keep, "{\"ts\":2", 7) == 0,
              "and the survivor opens with a whole entry");
        check(events_align_line(buf, sizeof(buf) - 1, 0) == 0,
              "offset zero stays zero");
        check(events_align_line(buf, sizeof(buf) - 1, sizeof(buf) - 1) == sizeof(buf) - 1,
              "an offset past every newline stops at the end");
        check(events_align_line(NULL, 10, 5) == 0, "NULL input aligns to zero");
    }

    printf("\n%ld checks, %s\n", checks, failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter \
    -o "$work/test" "$work/test.cpp"
"$work/test"
