#!/usr/bin/env bash
#
# Host-side regression test for the backlight ladder and its idle policy in
# src/skills/backlight.cpp.
#
# Why this exists: the AW9364 has no readback. Nothing can ask the part what
# step it is standing on, so the firmware's idea of the level is a MODEL that is
# kept in step with the hardware by counting, and the only thing keeping the two
# together is the arithmetic below. If the pulse count is wrong by one the
# screen does not go dark and nothing throws — it settles on a neighbouring
# brightness, the model and the part disagree from then on, and every later
# change is wrong by the same one. There is no witness to that but somebody
# noticing the screen looks off, and no test on hardware finds it either,
# because reading the level back is exactly what the part cannot do.
#
# The wrap is the half of it that is easy to get wrong. The counter only ever
# steps DOWN and wraps modulo 16, so getting BRIGHTER means going all the way
# round: the naive subtraction gives a negative count, and the naive
# special-case gives the right answer for "brighter" and the wrong one for
# "already there". Both bugs look identical from a desk — the screen simply
# stops responding to some of the settings.
#
# So the ladder is checked against the datasheet in the datasheet's own terms:
# Table 1 of the AW9364 (Awinic, Feb 2018 V2.3) is copied in below as an oracle,
# and the pulse counts are checked against a simulated part that implements
# nothing but "each rising edge advances a counter modulo 16", which is the one
# sentence the whole protocol comes down to.
#
# What this DOES NOT cover, said plainly rather than papered over:
#
#   - the pulses reaching the pin. The register writes, the critical section
#     and the microsecond delays need the chip; nothing here claims otherwise.
#     What IS checked is the number those pulses have to come to.
#   - the timing. That T_LO stays under the part's 500us maximum is a property
#     of the critical section and of delayMicroseconds(), neither of which
#     exists on the host.
#   - the panel. Whether "night" is actually readable is a question for eyes in
#     a room, and it is the reason the preset table is four numbers in one place
#     rather than a curve.
#
# The idle policy is here for a different reason: not because it is delicate,
# but because it is a decision with boundaries, and boundaries are exactly what
# a person cannot check by watching a screen. "Does it dim at thirty seconds or
# at thirty-one" is not a question anybody will ever answer with a stopwatch, so
# it is answered here — both thresholds from both sides, the switch, each
# exemption on its own, and the case that would otherwise be found by somebody
# noticing their screen got BRIGHTER when they walked away.
#
# The wrap of millis() is covered too, in uint32_t rather than in the host's
# wider unsigned long, because that is the arithmetic the device does. What the
# policy sees is an elapsed time the caller already subtracted, which is the
# whole defence: this file checks that the defence holds and that nothing in the
# policy needs a second one.
#
# What it does NOT cover, again plainly: the wiring in ui.h and main.cpp. That
# the policy is asked once a pass, that the answer reaches the pin, and that a
# turn of the knob restores the level are properties of a running loop and are
# checked by reading and by the device. The one wiring fact that IS enforced
# mechanically is the compile-time assertion in ui.h that the dim threshold
# outlasts the screen's own idle timeout — see ui_backlight_idle().
#
# The core is sliced straight out of the shipping source between its
# `host-test:begin` markers, the same way tools/test_progress.sh and
# tools/test_quiet.sh slice theirs, so this runs the real implementation rather
# than a copy that could drift.
#
# Usage: tools/test_backlight.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/backlight.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_backlight.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

PRELUDE
    slice "$src" bl_ladder
    slice "$src" bl_presets
    slice "$src" bl_idle
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

/*
 * Table 1 of the datasheet, copied by hand, indexed by the part's own EN rise
 * edge number. Entry 0 is unused padding so that the index reads as the edge.
 *
 * This is the whole point of the file: it is the hardware's answer, written
 * down independently of any expression in the firmware, so that a change to the
 * arithmetic has something to be wrong against. Microamps rather than
 * milliamps, to keep it in integers — every step is a multiple of 1.25mA.
 */
static const uint32_t table1_ua[BL_STEPS + 1] = {
    0,
    20000, 18750, 17500, 16250, 15000, 13750, 12500, 11250,
    10000,  8750,  7500,  6250,  5000,  3750,  2500,  1250,
};

/*
 * An AW9364, as far as the pulse count is concerned, and no further.
 *
 * It knows one thing: a rising edge advances the edge counter, and after 16 the
 * next one is 1 again. Figure 7 draws exactly that. Deliberately written in the
 * DATASHEET's numbering — edge 1 is 20mA and 16 is 1.25mA — and never in the
 * firmware's inverted one, so that a mistake in bl_edge_of() cannot cancel
 * itself out against a model that made the same mistake.
 */
typedef struct { int edge; } Aw9364;

/* The enabling edge is the first counted edge, and step 1 is maximum. */
static void chip_enable(Aw9364 *c) { c->edge = 1; }

static void chip_rise(Aw9364 *c) { c->edge = c->edge % BL_STEPS + 1; }

/*
 * Put the part on a firmware level directly, and read one back, by the relation
 * the datasheet states rather than by the function under test: level 16 is
 * edge 1.
 *
 * These two are textually identical to bl_edge_of(), and on their own that
 * would make the pulse-count section below a tautology — the same inversion
 * checked against itself. What stops it being one is table1_ua[] above, hand
 * transcribed from Table 1 in the DATASHEET's numbering and never touched by
 * the firmware: the ladder section checks bl_edge_of() against that table, and
 * the section below checks the CURRENT as well as the level, so an inverted
 * bl_edge_of() has to disagree with the table somewhere. Delete the table, or
 * stop comparing currents against it, and the 256 pairs stop saying anything.
 */
static void chip_park(Aw9364 *c, int level) { c->edge = BL_STEPS + 1 - level; }

static int chip_level(const Aw9364 *c) { return BL_STEPS + 1 - c->edge; }

static uint32_t chip_ua(const Aw9364 *c) { return table1_ua[c->edge]; }

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    printf("the ladder, against Table 1 of the datasheet\n");
    {
        int all = 1;
        for (int level = 1; level <= BL_STEPS; level++)
            if (bl_current_ua((uint8_t)level) != table1_ua[bl_edge_of((uint8_t)level)])
                all = 0;
        check(all, "every level draws what the part's own table says its step does");

        check(bl_current_ua(BL_STEPS) == 20000, "the brightest level is the 20mA step");
        check(bl_current_ua(1) == 1250, "the dimmest level is the 1.25mA step");
        check(bl_current_ua(0) == 0, "and off draws nothing");
        /* Out of range answers zero rather than indexing off the end of the
           ladder. The endpoint refuses these, so this is the second line. */
        check(bl_current_ua(BL_STEPS + 1) == 0, "a level past the top draws nothing");

        /* Linear, which is the fact the presets are spaced against: every step
           is the same 1.25mA and NOT a constant ratio. If this ever fails the
           part has been changed and the preset table's reasoning is void. */
        int even = 1;
        for (int level = 2; level <= BL_STEPS; level++)
            if (bl_current_ua((uint8_t)level) - bl_current_ua((uint8_t)(level - 1)) != BL_STEP_UA)
                even = 0;
        check(even, "the steps are evenly spaced in current, not in ratio");

        check(bl_total_ua(BL_STEPS) == 80000,
              "all four channels at full come to the 80mA behind the 85mA measured");
        check(bl_total_ua(0) == 0, "and to nothing when the part is off");
    }

    printf("the two numberings, which are inverses of each other\n");
    {
        int all = 1;
        for (int level = 1; level <= BL_STEPS; level++) {
            uint8_t edge = bl_edge_of((uint8_t)level);
            if (edge < 1 || edge > BL_STEPS) all = 0;
            if (bl_edge_of(edge) != level) all = 0;   /* its own inverse */
        }
        check(all, "every level maps to a step in range, and back to itself");
        check(bl_edge_of(BL_STEPS) == 1, "the brightest level is the part's first step");
        check(bl_edge_of(1) == BL_STEPS, "and the dimmest is its last");

        /* THE ASSUMPTION bl_drive() MAKES AND CANNOT VERIFY. Coming out of a
           shutdown it drives the line high, waits, and then sets its model to
           the brightest level without asking the part anything — because the
           part cannot be asked. The datasheet's step 1 is the enabling edge and
           step 1 is maximum, so that is right; if it were not, every level set
           after a blank would be wrong by however far off this is, silently and
           for as long as the device stayed up. */
        Aw9364 c;
        chip_enable(&c);
        check(chip_level(&c) == BL_STEPS,
              "the edge that enables the part leaves it at the brightest level");
        check(chip_ua(&c) == bl_current_ua(BL_STEPS),
              "drawing the full 20mA a channel, which is what a blank costs to undo");
    }

    printf("the pulse count, against a part that only counts rising edges\n");
    {
        /* The property that matters, over every pair there is: however many
           pulses the firmware says it takes, applying that many rising edges to
           a counter that wraps modulo 16 lands on the level that was asked for.
           256 pairs, so there is no sampling and no "representative case". */
        int wrong_level = 0, wrong_current = 0;
        for (int from = 1; from <= BL_STEPS; from++) {
            for (int to = 1; to <= BL_STEPS; to++) {
                Aw9364 c;
                chip_park(&c, from);
                uint8_t n = bl_pulses((uint8_t)from, (uint8_t)to);
                for (uint8_t i = 0; i < n; i++) chip_rise(&c);
                if (chip_level(&c) != to) wrong_level++;
                if (chip_ua(&c) != bl_current_ua((uint8_t)to)) wrong_current++;
            }
        }
        check(wrong_level == 0,
              "every one of the 256 level changes lands on the level asked for");
        check(wrong_current == 0,
              "and the part is then drawing what the firmware says it draws");
        /* No bound on the pulse count is asserted here. It would have to be
           "fewer than sixteen", which the modulo makes true by construction,
           and the round-trip property at the end of the next section already
           pins every pair to an exact count — a strictly stronger statement.
           A version that wasted a whole lap reddens there, not here. */
    }

    printf("the cases worth naming\n");
    {
        check(bl_pulses(11, 11) == 0,
              "asking for the level already set sends nothing at all");
        int quiet = 1;
        for (int level = 1; level <= BL_STEPS; level++)
            if (bl_pulses((uint8_t)level, (uint8_t)level) != 0) quiet = 0;
        check(quiet, "and that holds at every level, not just one");

        check(bl_pulses(BL_STEPS, BL_STEPS - 1) == 1,
              "one step dimmer is one pulse");
        check(bl_pulses(BL_STEPS, 1) == BL_STEPS - 1,
              "brightest to dimmest is fifteen, the long way down");

        /* THE WRAP. Getting brighter is not a negative count and not a special
           case — it is the rest of the lap. One step below the top is one pulse
           short of a full lap; one step above the bottom is a single pulse. */
        check(bl_pulses(1, BL_STEPS) == 1,
              "dimmest to brightest is ONE pulse, over the wrap");
        check(bl_pulses(8, 12) == 12,
              "and a dim level to a brighter one goes round rather than back");
        check(bl_pulses(BL_STEPS - 1, BL_STEPS) == BL_STEPS - 1,
              "one step below the top costs the whole lap but one");

        /* Round trip: going somewhere and coming back is always a whole lap,
           which is the arithmetic statement of "the counter only turns one
           way". A version that special-cased the brighter direction would give
           16 here for some pairs and something else for others. */
        int laps = 1;
        for (int a = 1; a <= BL_STEPS; a++) {
            for (int b = 1; b <= BL_STEPS; b++) {
                int there = bl_pulses((uint8_t)a, (uint8_t)b);
                int back = bl_pulses((uint8_t)b, (uint8_t)a);
                if (a != b && there + back != BL_STEPS) laps = 0;
                if (a == b && there + back != 0) laps = 0;
            }
        }
        check(laps, "there and back is always exactly one lap, or no pulses at all");
    }

    printf("what the endpoint will accept\n");
    {
        check(bl_level_valid(0), "0 is a level, and it means off");
        check(bl_level_valid(1), "so is the dimmest step");
        check(bl_level_valid(BL_STEPS), "so is the brightest");
        check(!bl_level_valid(BL_STEPS + 1), "one past the top is refused");
        check(!bl_level_valid(-1), "and so is a negative, which a JSON int can be");
        check(!bl_level_valid(255), "and so is a byte that overflowed somewhere");
    }

    printf("the preset table, whose shape the rest of the file assumes\n");
    {
        check(BL_PRESET_COUNT > 1, "there is more than one preset to cycle through");

        int ordered = 1, in_range = 1;
        for (int i = 0; i < BL_PRESET_COUNT; i++) {
            if (bl_preset_table[i].level < 1 || bl_preset_table[i].level > BL_STEPS)
                in_range = 0;
            if (i > 0 && bl_preset_table[i].level >= bl_preset_table[i - 1].level)
                ordered = 0;
        }
        check(in_range, "every preset is a level the part actually has");
        /* bl_preset_next() is written as "the first one dimmer than this", so a
           table out of order would silently skip presets rather than fail. */
        check(ordered, "and they are strictly descending, which the cycle relies on");
        check(bl_preset_table[0].level == BL_STEPS,
              "the first is full brightness, which is where the cycle wraps to");
        /* Off is the endpoint's to set, never the menu's: a click must not be
           able to blank the screen the menu is being read on. */
        int has_off = 0;
        for (int i = 0; i < BL_PRESET_COUNT; i++)
            if (bl_preset_table[i].level == 0) has_off = 1;
        check(!has_off, "and none of them is off");
    }

    printf("the click, which is the only way to set this with no network\n");
    {
        /* One click per preset gets back to where it started, having visited
           every one of them exactly once. That is the whole contract of the
           row, and it is checked by walking rather than by trusting the table. */
        uint8_t level = bl_preset_table[0].level;
        int seen[BL_PRESET_COUNT];
        memset(seen, 0, sizeof(seen));
        int stranger = 0;
        for (int step = 0; step < BL_PRESET_COUNT; step++) {
            int idx = -1;
            for (int i = 0; i < BL_PRESET_COUNT; i++)
                if (bl_preset_table[i].level == level) idx = i;
            if (idx < 0) stranger = 1; else seen[idx]++;
            level = bl_preset_next(level);
        }
        check(!stranger, "every click lands on a preset");
        check(level == bl_preset_table[0].level,
              "and a full cycle of clicks comes back to full brightness");
        int once = 1;
        for (int i = 0; i < BL_PRESET_COUNT; i++) if (seen[i] != 1) once = 0;
        check(once, "having passed through each preset exactly once");

        /* Levels the menu can never produce but the endpoint can. The row still
           has to do something sensible from them, and "join the cycle at the
           next one down" is that. */
        check(bl_preset_next(13) == 11,
              "a level between two presets goes to the next one down");
        check(bl_preset_next(2) == BL_STEPS,
              "a level below every preset wraps to full");
        check(bl_preset_next(0) == BL_STEPS,
              "and a click on a screen the endpoint blanked turns it back on");
        /* Nothing may ever cycle to off — see the table check above. */
        int never_off = 1;
        for (int level_in = 0; level_in <= BL_STEPS; level_in++)
            if (bl_preset_next((uint8_t)level_in) == 0) never_off = 0;
        check(never_off, "and no level whatsoever clicks through to a dark screen");
    }

    /* Not "the only new string on the device" any more: the Auto-dim row's
       "on"/"off" is one too, and it is the one string here that this section
       does NOT reach. bl_idle_word() reads the live switch, which is a device
       global with no meaning on a host, so it stays outside the sliced region —
       and at two words neither of which is longer than a preset name, it cannot
       be what makes a row run off the panel. Said here rather than left as a
       heading that quietly stopped being true. */
    printf("the menu row's label, which is where a level becomes a word\n");
    {
        /* The buffer the DEVICE uses, not a roomier one: a label that only fits
           because the test gave itself more space than ui.h has is a label that
           is cut short on the panel and whole here. */
        char s[BL_LABEL_MAX];
        /* Read out of the table rather than spelled out here. The table is four
           numbers and four words that the file it lives in invites editing, and
           a check naming one of those words fails on the edit rather than on a
           mistake — which is the opposite of what it is for. */
        int named = 1;
        for (int i = 0; i < BL_PRESET_COUNT; i++) {
            bl_level_label(bl_preset_table[i].level, s, sizeof(s));
            if (strcmp(s, bl_preset_table[i].name) != 0) named = 0;
        }
        check(named, "every preset reads as its own name, whatever the table says they are");
        bl_level_label(0, s, sizeof(s));
        check(strcmp(s, "off") == 0, "off says so");
        /* Never rounded into the nearest word: a level set for an experiment has
           to be readable off the panel as the level it is. Which levels have no
           word is the table's business, so this asks the table rather than
           naming one — and it covers all sixteen instead of the two a hand-
           picked pair would. */
        int unnamed = 0, spelled = 1;
        for (int level = 1; level <= BL_STEPS; level++) {
            if (bl_preset_name((uint8_t)level) != NULL) continue;
            unnamed++;
            char want[BL_LABEL_MAX];
            snprintf(want, sizeof(want), "step %d", level);
            bl_level_label((uint8_t)level, s, sizeof(s));
            if (strcmp(s, want) != 0) spelled = 0;
        }
        check(unnamed > 0, "there are levels the table has no word for, which is the point of sixteen");
        check(spelled, "and every one of them reads as its step number");

        /* The width argument at the call site in ui.h counts these characters.
           ui.h writes "Backlight " in front of them, so seven here is the row
           "Backlight step 16", which with the marker measures 210px of font 4
           against the 296px ui_draw_row() has. A longer string runs off the
           panel, so the length is pinned rather than left as a comment. */
        size_t longest = 0;
        for (int level = 0; level <= BL_STEPS; level++) {
            bl_level_label((uint8_t)level, s, sizeof(s));
            if (strlen(s) > longest) longest = strlen(s);
        }
        check(longest == 7,
              "the longest label is 7 characters: the 17 of \"Backlight step 16\" "
              "that ui.h measured, less the 10 of \"Backlight \"");
        /* And the buffer every caller sizes from that pin actually holds it.
           Tied together here so that a fifth preset with a longer name than
           "step 16" fails this rather than being cut short on the panel. */
        check(longest < BL_LABEL_MAX,
              "and the buffer the call sites take from this file holds it whole");
        /* Out of range prints whole too. The endpoint refuses these, so this is
           the second line — but a truncated label is a worse way to find out. */
        bl_level_label(255, s, sizeof(s));
        check(strcmp(s, "step 255") == 0 && strlen(s) < BL_LABEL_MAX,
              "a level off the ladder entirely still prints whole");
    }

    printf("the idle policy, which is where the battery is actually won\n");
    {
        /* The shipped policy, and the same one switched off. Both built by the
           shipping factory rather than assembled here, so that the wiring
           between the macros and the fields is under test and not merely
           copied — see the section after this one. */
        const BacklightIdle live = bl_idle_policy(true);
        const BacklightIdle off = bl_idle_policy(false);
        /* Thresholds and a level the shipped policy does not use, so that a
           version reading the macros instead of its argument is caught. */
        const BacklightIdle other = {true, 1000, 5000, 7};

        /* The panel's facts, one case per constant, in the struct's declared
           order. Named rather than written as four booleans at each call site:
           a row of bare true/false is where an exemption ends up tested as its
           neighbour. */
        const BacklightPanel bare  = {false, false, false, false};
        const BacklightPanel blast = {true,  false, false, false};
        const BacklightPanel rec   = {false, true,  false, false};
        const BacklightPanel bar   = {false, false, true,  false};
        const BacklightPanel crit  = {false, false, false, true};
        const BacklightPanel live_out = {true, true, true, false};

        check(bl_idle_level(live, BL_STEPS, 0, bare) == BL_STEPS,
              "a device just touched is at the level its owner set");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_DIM_MS - 1, bare) == BL_STEPS,
              "and one millisecond before the dim threshold, still is");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_DIM_MS, bare) == BL_IDLE_LEVEL,
              "the dim threshold is the first millisecond of dim, not the last of full");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_DIM_MS + 1, bare) == BL_IDLE_LEVEL,
              "and it stays there through the middle of the window");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_OFF_MS - 1, bare) == BL_IDLE_LEVEL,
              "right up to one millisecond before the blank");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_OFF_MS, bare) == 0,
              "the blank threshold is inclusive in the same way");
        check(bl_idle_level(live, BL_STEPS, 3600000UL, bare) == 0,
              "and an hour later the panel is still dark");

        /* The thresholds are the struct's, not the file's. */
        check(bl_idle_level(other, BL_STEPS, 999, bare) == BL_STEPS,
              "a policy with its own thresholds is obeyed below the first of them");
        check(bl_idle_level(other, BL_STEPS, 1000, bare) == 7,
              "dims at its own threshold, to its own level");
        check(bl_idle_level(other, BL_STEPS, 5000, bare) == 0,
              "and blanks at its own");

        /* THE SWITCH. Off means the level set by hand is the level, full stop:
           this is the whole of what the menu row promises. */
        int handed_back = 1;
        const unsigned long spread[] = {0, 1, BL_IDLE_DIM_MS - 1, BL_IDLE_DIM_MS,
                                        BL_IDLE_OFF_MS, 3600000UL, 4294967295UL};
        const int spread_n = (int)(sizeof(spread) / sizeof(spread[0]));
        for (int i = 0; i < spread_n; i++)
            for (int level = 0; level <= BL_STEPS; level++)
                if (bl_idle_level(off, (uint8_t)level, spread[i], bare) != level)
                    handed_back = 0;
        check(handed_back,
              "with the switch off the level set by hand is what the panel is at, "
              "however long nobody comes");

        /* THE EXEMPTIONS, one at a time. Live output on the panel is never
           dimmed and never blanked, however long the last input was. */
        int blast_safe = 1, rec_safe = 1, bar_safe = 1;
        for (int i = 0; i < spread_n; i++) {
            if (bl_idle_level(live, BL_STEPS, spread[i], blast) != BL_STEPS)
                blast_safe = 0;
            if (bl_idle_level(live, BL_STEPS, spread[i], rec) != BL_STEPS)
                rec_safe = 0;
            if (bl_idle_level(live, BL_STEPS, spread[i], bar) != BL_STEPS)
                bar_safe = 0;
        }
        check(blast_safe, "a blast in flight is never dimmed out from under whoever started it");
        check(rec_safe, "and neither is a recording, at any idle time whatsoever");
        /* The one nothing on the device stamps input for: a job pushed over the
           network draws its bar on a panel nobody has touched, so without this
           the bar is drawn into the dark two minutes in. */
        check(bar_safe, "and neither is a progress bar, which nobody had to touch the knob to start");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_OFF_MS, live_out) == BL_STEPS,
              "all three at once is still the level set by hand");

        /* AN UNREAD CRITICAL STOPS THE BLANK. It never expires, and inside the
           ring's night window the breathing rule on the clock face is the only
           thing left saying it is there — so a blank would leave a critical with
           no indication anywhere at all, in a state that stays that way until
           somebody happens to look. It is a FLOOR: the panel still dims. */
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_OFF_MS, crit) == BL_IDLE_LEVEL,
              "an unread critical holds the panel at the dim step instead of letting it blank");
        check(bl_idle_level(live, BL_STEPS, 3600000UL, crit) == BL_IDLE_LEVEL,
              "and still holds it there an hour later, because a critical never expires");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_DIM_MS, crit) == BL_IDLE_LEVEL,
              "it does not stop the DIM, which is the half that costs almost nothing");
        check(bl_idle_level(live, BL_STEPS, BL_IDLE_DIM_MS - 1, crit) == BL_STEPS,
              "and it is not a reason to hold a panel up that nothing was taking down");
        /* Never a wake-up. Somebody sitting below the dim step, or with the
           screen switched off outright, asked for that. */
        check(bl_idle_level(live, 1, BL_IDLE_OFF_MS, crit) == 1,
              "a panel already dimmer than the dim step is held there and not raised to meet it");
        check(bl_idle_level(live, 0, BL_IDLE_OFF_MS, crit) == 0,
              "and a screen switched off by hand stays off, critical or no critical");
        int crit_off = 1;
        for (int i = 0; i < spread_n; i++)
            for (int level = 0; level <= BL_STEPS; level++)
                if (bl_idle_level(off, (uint8_t)level, spread[i], crit) != level)
                    crit_off = 0;
        check(crit_off, "and with the auto-dim switched off it changes nothing at all");

        /* NEVER BRIGHTER. Somebody sitting at "night" asked for less than the
           dim step offers, and raising it because they stopped touching the
           device would be the policy working against its own purpose. */
        check(bl_idle_level(live, BL_IDLE_LEVEL, BL_IDLE_DIM_MS, bare) == BL_IDLE_LEVEL,
              "a device already at the dim step is left exactly where it is");
        check(bl_idle_level(live, 1, BL_IDLE_DIM_MS, bare) == 1,
              "and one already dimmer than the dim step is not turned UP to meet it");
        check(bl_idle_level(live, 1, BL_IDLE_OFF_MS, bare) == 0,
              "though it still goes out at the blank, which is about power and not about level");

        /* A screen the endpoint blanked deliberately stays blanked, and the
           policy has nothing to add to it. */
        int stays_dark = 1;
        for (int i = 0; i < spread_n; i++)
            if (bl_idle_level(live, 0, spread[i], bare) != 0) stays_dark = 0;
        check(stays_dark, "a screen already switched off stays off rather than being dimmed to something");

        /* Monotone in the idle time, at every level: waiting longer can only
           ever take the panel DOWN. A threshold accidentally written the wrong
           way round shows up here as well as at the boundaries. Run with a
           critical outstanding too, because the floor is the one thing here
           that could plausibly hand a panel back up. */
        int monotone = 1;
        for (int level = 0; level <= BL_STEPS; level++) {
            for (int c = 0; c < 2; c++) {
                const BacklightPanel &s = c ? crit : bare;
                uint8_t prev = bl_idle_level(live, (uint8_t)level, 0, s);
                for (unsigned long t = 0; t <= BL_IDLE_OFF_MS + 2000; t += 500) {
                    uint8_t now = bl_idle_level(live, (uint8_t)level, t, s);
                    if (now > prev) monotone = 0;
                    prev = now;
                }
            }
        }
        check(monotone, "waiting longer only ever takes the panel down, never up");

        /* THE WRAP. millis() is 32 bits and goes round every 49 days. The
           caller subtracts, and the subtraction is unsigned, so the elapsed
           time this function sees stays small across the wrap — modelled in
           uint32_t here because a host's unsigned long is not the device's. */
        {
            uint32_t last = 0xFFFFF000UL;         /* 4096ms before the wrap */
            uint32_t now = 4000UL;                /* 4000ms after it */
            unsigned long since = (unsigned long)(uint32_t)(now - last);
            check(since == 8096UL,
                  "an unsigned subtraction across the wrap gives the real 8 seconds");
            check(bl_idle_level(live, BL_STEPS, since, bare) == BL_STEPS,
                  "so a panel in use when the clock wraps is not blanked by the wrap");

            /* And the other direction: genuinely idle ACROSS the wrap still
               goes dark, rather than having its clock reset by it. */
            uint32_t later = last + 200000UL;     /* wraps on the way */
            unsigned long idle = (unsigned long)(uint32_t)(later - last);
            check(idle == 200000UL, "and a real wait across the wrap is still the real wait");
            check(bl_idle_level(live, BL_STEPS, idle, bare) == 0,
                  "so the wrap does not hand a forgotten device its backlight back");
        }

        /* The shipped numbers. They are meant to be edited after looking at a
           screen; these are the properties that must survive the edit. */
        check(BL_IDLE_DIM_MS < BL_IDLE_OFF_MS,
              "the panel dims before it blanks, which is the order of the two names");
        check(BL_IDLE_LEVEL > 0 && BL_IDLE_LEVEL <= BL_STEPS,
              "the dim step is a level the part actually has");
        check(bl_preset_name(BL_IDLE_LEVEL) != NULL,
              "and it is one of the presets, not an arbitrary rung of a ladder "
              "nobody has looked at");
        /* The switch's default, which is the one number in this file that
           silently reverses the whole commit. Flipped to false the policy never
           runs, the panel sits at full around the clock exactly as it did
           before, and nothing else in this file has anything to say about it —
           bl_idle_level() is asked about a policy the test builds and never
           about the one the device boots with. */
        check(BL_IDLE_DEFAULT,
              "the policy is ON out of the box, which is the whole of what this saves");
    }

    printf("the wiring between the numbers and the fields they fill\n");
    {
        /* bl_idle_policy() is the only place the macros meet the struct, and it
           is here because it is the one place in this file where two fields of
           the same type sit side by side. Swapped, the panel blanks at the dim
           threshold and never dims at all — and every check above stays green,
           because every one of them hands bl_idle_level() a policy built from
           these same two macros in whatever order it was given them. Read back
           by name, which is the only way that mistake has to show. */
        const BacklightIdle p = bl_idle_policy(true);
        check(p.dim_ms == BL_IDLE_DIM_MS, "the dim threshold reaches the field that dims");
        check(p.off_ms == BL_IDLE_OFF_MS, "the blank threshold reaches the field that blanks");
        check(p.dim_level == BL_IDLE_LEVEL, "and the dim step reaches the level");
        check(p.on, "the switch is what it was handed");
        check(!bl_idle_policy(false).on, "both ways round");
        /* And the order the two thresholds have to be in, stated against the
           built policy rather than against the macros, so that this section
           says something even if the macros are read correctly and assigned to
           each other's fields. */
        check(p.dim_ms < p.off_ms,
              "the built policy dims before it blanks, whatever the macros are edited to");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test"
