#!/usr/bin/env bash
#
# Host-side regression test for the BQ27220 decode in src/skills/battery.cpp.
#
# Why this exists: GET /battery is a diagnostic, and a diagnostic that reports
# confidently and wrongly is worse than no diagnostic. The whole point of the
# endpoint is that somebody will read "sec: sealed" or "fc: true" off it and
# decide what to write to a live fuel gauge on the strength of it. A shift by
# one bit in a mask does not fail a build, does not throw and does not look
# broken — it looks like an answer.
#
# The two pieces below are pure computation over a uint16 and are therefore the
# pieces a host can hold to account:
#
#   1. The two-byte little-endian word assembly. Get it backwards and 4200 mV
#      reads as 26640 mV — which the voltage gate then rejects, so the panel
#      silently stops updating and nobody is told why.
#   2. The status bit fields. Every mask below is checked against the position
#      the TRM (SLUUBD4A, Tables 2-6 and 2-7) puts it at, and every named flag
#      is checked to respond to ITS OWN bit and to no other.
#
# WHAT THIS DOES NOT COVER, said plainly rather than papered over: the I2C
# transaction. bq27220_read16() is four calls into Arduino's TwoWire and its
# failure modes are a NAK, a missing pull-up and a second task on the bus. None
# of that has a host equivalent, nothing below simulates it, and the only proof
# that half of the skill works is a reading taken off the device. The endpoint
# layer is not here either — tools/test_routes.sh gates the exact matcher and
# the body-handler wiring, which is the failure mode that layer actually has.
#
# Nor is battery_read()'s at_boot gate: the rule that only the boot pass may set
# hw.has_battery, so that a bus glitch during a later refresh cannot make a
# device without a fuel gauge start claiming one. It sits above the slice
# markers, on the far side of Wire and hw, and reaching it from the host would
# mean rearranging the shipping source to suit the test. It is left uncovered on
# purpose and named here so that nobody reads this file's green as covering it.
#
# The decode is sliced straight out of the shipping source between its
# `host-test:begin gauge` and `host-test:end` markers, the same way
# tools/test_progress.sh and tools/test_voice_url.sh slice theirs, so this runs
# the real implementation rather than a copy that could drift.
#
# Usage: tools/test_battery.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../src/skills/battery.cpp"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$src" ] || { echo "cannot find $src"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

{
    cat <<'PRELUDE'
/* Generated by tools/test_battery.sh — do not edit. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

PRELUDE
    slice "$src" gauge
    cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;

static void check(int cond, const char *what) {
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

static void eq_int(int got, int want, const char *what) {
    if (got != want) {
        printf("  FAIL: %s — got %d, wanted %d\n", what, got, want);
        failures++;
    } else {
        printf("  ok:   %s = %d\n", what, got);
    }
}

static void eq_str(const char *got, const char *want, const char *what) {
    if (strcmp(got, want) != 0) {
        printf("  FAIL: %s — got \"%s\", wanted \"%s\"\n", what, got, want);
        failures++;
    } else {
        printf("  ok:   %s = \"%s\"\n", what, got);
    }
}

/* One named flag, with the bit the datasheet puts it at. The position is
   written here as a NUMBER rather than as the macro, so that this table is the
   datasheet and the source is the thing under test — comparing a macro to
   itself would pass whatever it was changed to. */
struct FlagCase {
    const char *name;
    uint16_t mask;
    int bit;
};

static const FlagCase op_flags[] = {
    {"CALMD",     BQ_OP_CALMD,      0},
    {"EDV2",      BQ_OP_EDV2,       3},
    {"VDQ",       BQ_OP_VDQ,        4},
    {"INITCOMP",  BQ_OP_INITCOMP,   5},
    {"SMTH",      BQ_OP_SMTH,       6},
    {"BTPINT",    BQ_OP_BTPINT,     7},
    {"CFGUPDATE", BQ_OP_CFGUPDATE, 10},
};

static const FlagCase batt_flags[] = {
    {"DSG",      BQ_BS_DSG,       0},
    {"SYSDWN",   BQ_BS_SYSDWN,    1},
    {"TDA",      BQ_BS_TDA,       2},
    {"BATTPRES", BQ_BS_BATTPRES,  3},
    {"AUTH_GD",  BQ_BS_AUTH_GD,   4},
    {"OCVGD",    BQ_BS_OCVGD,     5},
    {"TCA",      BQ_BS_TCA,       6},
    {"CHGINH",   BQ_BS_CHGINH,    8},
    {"FC",       BQ_BS_FC,        9},
    {"OTD",      BQ_BS_OTD,      10},
    {"OTC",      BQ_BS_OTC,      11},
    {"SLEEP",    BQ_BS_SLEEP,    12},
    {"OCVFAIL",  BQ_BS_OCVFAIL,  13},
    {"OCVCOMP",  BQ_BS_OCVCOMP,  14},
    {"FD",       BQ_BS_FD,       15},
};

#define COUNT(a) ((int)(sizeof(a) / sizeof((a)[0])))

/*
 * bq_soc_from_capacity() with its arguments laundered through volatiles, and
 * every capacity check below goes through this rather than calling directly.
 *
 * Not decoration. Removing the function's `full_mah == 0` guard does not
 * produce a wrong answer, it produces UNDEFINED BEHAVIOUR, and at -O2 the
 * compiler is entitled to resolve that however it likes — measured here, it
 * folded the comparison in the test's favour and the check for the guard
 * PASSED on a build that would divide by zero on the device. A check that
 * cannot fail when the thing it names is deleted is not a check.
 *
 * The volatiles take the constants away from the optimiser, so the division
 * genuinely happens: a trap on x86, a zero result on ARM, and a failure on
 * either. Verified by deleting the guard — red with this in place, green
 * without it.
 */
static int soc_from(uint16_t remaining, uint16_t full) {
    volatile uint16_t r = remaining, f = full;
    return bq_soc_from_capacity(r, f);
}

/* Each mask sits where the datasheet says, responds to its own bit, and stays
   clear for every other bit in the word. The last part is what catches a mask
   that was widened or duplicated: a flag reading true off somebody else's bit
   is the exact defect this endpoint must not have. */
static void flag_table(const FlagCase *cases, int n, const char *word_name) {
    char what[128];

    for (int i = 0; i < n; i++) {
        snprintf(what, sizeof(what), "%s.%s is bit %d", word_name, cases[i].name, cases[i].bit);
        check(cases[i].mask == (uint16_t)(1u << cases[i].bit), what);

        snprintf(what, sizeof(what), "%s.%s reads true off its own bit", word_name, cases[i].name);
        check(bq_flag((uint16_t)(1u << cases[i].bit), cases[i].mask), what);

        int leaked = -1;
        for (int b = 0; b < 16; b++) {
            if (b == cases[i].bit) continue;
            if (bq_flag((uint16_t)(1u << b), cases[i].mask)) { leaked = b; break; }
        }
        if (leaked >= 0) {
            printf("  FAIL: %s.%s also reads true off bit %d\n",
                   word_name, cases[i].name, leaked);
            failures++;
        } else {
            printf("  ok:   %s.%s reads false off all fifteen other bits\n",
                   word_name, cases[i].name);
        }
    }

    /* No two flags claim the same bit — the copy-paste mistake a table this
       long invites.

       Stated honestly: this one never fails ALONE. Duplicating a mask also
       moves it off the position the loop above checks, so that check fires
       too, and no mutation of the source has been found that trips this and
       nothing else. It is kept because it names the failure in the words a
       reader would use, not because it adds detection. */
    int clash = 0;
    for (int i = 0; i < n; i++)
        for (int j = i + 1; j < n; j++)
            if (cases[i].mask == cases[j].mask) clash = 1;
    snprintf(what, sizeof(what), "no two %s flags claim the same bit", word_name);
    check(!clash, what);
}

int main(void) {
    /* Any hang is a failure, not a hung test run. */
    alarm(60);

    printf("the wire order\n");
    {
        /* 0x1068 = 4200 mV, a full cell — the reading the whole ticket is
           about, and the one that becomes 26640 if the bytes are swapped. */
        eq_int(bq_word(0x68, 0x10), 4200, "low byte first: 0x68,0x10 is 4200 mV");
        eq_int(bq_word(0x10, 0x68), 26640, "and the other way round is not");
        eq_int(bq_word(0x00, 0x00), 0, "both bytes zero");
        eq_int(bq_word(0xFF, 0xFF), 65535, "both bytes set, and no sign extension");
        eq_int(bq_word(0xFF, 0x00), 255, "a high byte of zero keeps the low byte");
        eq_int(bq_word(0x00, 0x01), 256, "a low byte of zero shifts the high one");
    }

    printf("the voltage gate, bounds exclusive as they always were\n");
    {
        check(bq_voltage_ok(3950), "3.95 V, one of the two live readings");
        check(bq_voltage_ok(4200), "4.20 V, the other one");
        check(bq_voltage_ok(2001), "2001 mV is inside");
        check(bq_voltage_ok(5999), "5999 mV is inside");
        check(!bq_voltage_ok(2000), "2000 mV is out: the bound is exclusive");
        check(!bq_voltage_ok(6000), "6000 mV is out: so is that one");
        check(!bq_voltage_ok(0), "a dead bus reads zero and is refused");
        check(!bq_voltage_ok(26640), "and a byte-swapped 4.20 V is refused too");
    }

    printf("the state-of-charge gate\n");
    {
        check(bq_soc_ok(0), "0% is a value");
        check(bq_soc_ok(52), "52%, as reported at 3.95 V");
        check(bq_soc_ok(76), "76%, as reported at a full 4.20 V");
        check(bq_soc_ok(100), "100% is inside: this bound is inclusive");
        check(!bq_soc_ok(101), "101% is not a percentage");
        check(!bq_soc_ok(65535), "nor is an all-ones read");
    }

    printf("OperationStatus flags (TRM Table 2-7)\n");
    {
        flag_table(op_flags, COUNT(op_flags), "op");

        /* Named separately because it is the one whose position is easiest to
           get wrong: the table puts CFGUPDATE at HIGH byte bit 2, which is bit
           10 of the assembled word and not bit 2 and not bit 15. */
        check(bq_flag(0x0400, BQ_OP_CFGUPDATE), "CFGUPDATE responds to 0x0400");
        check(!bq_flag(0x0004, BQ_OP_CFGUPDATE), "and not to 0x0004, the low-byte bit 2");
        check(!bq_flag(0x8000, BQ_OP_CFGUPDATE), "and not to 0x8000, the top of the word");

        /* The bits SEC occupies belong to no named flag: it is a two-bit field
           and a flag reading off one half of it would be nonsense. */
        for (int i = 0; i < COUNT(op_flags); i++) {
            check(!bq_flag(0x0002, op_flags[i].mask) && !bq_flag(0x0004, op_flags[i].mask),
                  "no op flag claims a SEC bit");
        }
    }

    printf("the security mode\n");
    {
        eq_str(bq_sec_name(0x0006), "sealed",   "SEC 11");
        eq_str(bq_sec_name(0x0004), "unsealed", "SEC 10");
        eq_str(bq_sec_name(0x0002), "full",     "SEC 01");
        eq_str(bq_sec_name(0x0000), "unknown",  "SEC 00, which the TRM does not define");

        eq_int(bq_sec_bits(0x0006), 3, "the raw bits behind sealed");
        eq_int(bq_sec_bits(0x0004), 2, "the raw bits behind unsealed");
        eq_int(bq_sec_bits(0x0002), 1, "the raw bits behind full");
        eq_int(bq_sec_bits(0x0000), 0, "the raw bits behind unknown");

        /* The field is read out of a whole word, so every other bit must be
           ignored. 0xFFF9 is "everything set except SEC", which must still
           read as SEC 00. */
        eq_str(bq_sec_name(0xFFF9), "unknown", "SEC ignores every bit outside the field");
        eq_str(bq_sec_name(0xFFFF), "sealed",  "and reads the field when all bits are set");
        eq_int(bq_sec_bits(0xFFF9), 0, "and so do the raw bits");

        /* A sealed gauge with initialisation done and no CONFIG UPDATE in
           progress. NOT the state this device is in — it reads SEC 10,
           unsealed, confirmed off the live gauge — but sealed is the state
           that would block commit 2 from writing anything, so it is the one
           worth being sure the decode does not report by accident. It must
           come out as all three of those things at once rather than one of
           them swallowing the others. */
        uint16_t sealed_idle = 0x0006 | BQ_OP_INITCOMP;
        eq_str(bq_sec_name(sealed_idle), "sealed", "a sealed, initialised gauge");
        check(bq_flag(sealed_idle, BQ_OP_INITCOMP), "reports initialisation complete");
        check(!bq_flag(sealed_idle, BQ_OP_CFGUPDATE), "and is not in CONFIG UPDATE");
        check(!bq_flag(sealed_idle, BQ_OP_VDQ), "and has qualified no discharge");
    }

    printf("BatteryStatus flags (TRM Table 2-6)\n");
    {
        flag_table(batt_flags, COUNT(batt_flags), "batt");

        /* FC is what says "this pack is full", which is the claim the reported
           76% contradicts. High byte bit 1 is bit 9 of the word. */
        check(bq_flag(0x0200, BQ_BS_FC), "FC responds to 0x0200");
        check(!bq_flag(0x0002, BQ_BS_FC), "and not to 0x0002, the low-byte bit 1");
        check(!bq_flag(0x0000, BQ_BS_FC), "and an empty word is not full charge");

        /* Low-byte bit 7 is reserved on this part, and is where somebody
           looking for ITPOR would put it. Nothing may claim it. */
        int claimed = 0;
        for (int i = 0; i < COUNT(batt_flags); i++)
            if (bq_flag(0x0080, batt_flags[i].mask)) claimed = 1;
        check(!claimed, "the reserved low-byte bit 7 is claimed by no flag");
    }

    printf("state of charge derived from the capacities\n");
    {
        /* The pack this device is believed to carry. */
        eq_int(soc_from(676, 1300), 52, "676 of 1300 mAh is 52%");
        eq_int(soc_from(988, 1300), 76, "988 of 1300 mAh is 76%");
        eq_int(soc_from(1300, 1300), 100, "a full pack is 100%");
        eq_int(soc_from(0, 1300), 0, "an empty one is 0%");

        /* Rounds to nearest, so that a single point of disagreement with the
           gauge's own percentage is evidence rather than this function's
           truncation. */
        eq_int(soc_from(1, 3), 33, "1 of 3 rounds down to 33");
        eq_int(soc_from(2, 3), 67, "2 of 3 rounds up to 67");
        eq_int(soc_from(5, 1000), 1, "5 of 1000 rounds up to 1, not down to 0");
        eq_int(soc_from(4, 1000), 0, "4 of 1000 rounds down to 0");

        /* No overflow: the intermediate is remaining * 100, which leaves a
           uint16 at 6553 mAh and does not leave the uint32 the code uses. */
        eq_int(soc_from(65535, 65535), 100, "the largest pair either register can hold");
        eq_int(soc_from(65535, 65534), 100, "and one just over it does not wrap");

        /* A gauge that has never established a full charge divides by zero.
           That is a finding, and it is reported as one rather than crashed on. */
        eq_int(soc_from(676, 0), -1, "a FullChargeCapacity of zero is refused");
        eq_int(soc_from(0, 0), -1, "and so is a pair of zeroes");

        /* The reason the endpoint reports this figure at all: it is what tells
           a wrong FullChargeCapacity apart from a wrong RemainingCapacity. The
           popular diagnosis for this family — a 3000 mAh default against a
           1300 mAh pack — caps a full pack here, and the device reports 76%,
           which is how that theory was ruled out. */
        eq_int(soc_from(1300, 3000), 43, "a full 1300 mAh pack against a 3000 mAh default");
        check(soc_from(1300, 3000) < 76,
              "which is below the 76% the device actually reports");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.cpp"

cxx="${CXX:-c++}"
"$cxx" -std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -o "$work/test" "$work/test.cpp"
"$work/test"
