#!/usr/bin/env bash
#
# Host-side regression test for seeds/linux/skills/drop.c — the message drop
# that parallel agent sessions coordinate through.
#
# Why this exists: the drop's failure modes are all silent. A handle validator
# with a hole lets bytes into URLs and onto an ASCII-only pager. A cursor that
# advances on peek eats messages nobody read; one that fails to advance
# delivers the same message forever. A ring that miscounts at the wrap serves
# ghosts. A board renderer without a truncation guard is the repo's known
# accumulating-snprintf trap: after the first truncated snprintf, n exceeds
# size and size-n wraps to a huge size_t. And a JSONL reader that disagrees
# with the writer about escaping loses every message across a restart. None of
# that fails the build.
#
# The code is sliced straight out of the shipping source between its
# `host-test:begin drop` and `host-test:end` markers, the same way the tembed
# tools/test_notify_options.sh slices its regions, so this runs the real
# implementation rather than a copy that could drift. json_escape() is sliced
# out of seed.c by function name for the same reason: the JSONL writer uses it,
# and a stand-in would only prove the reader agrees with the stand-in.
#
# Two known traps of the slicing technique, both checked below rather than
# hoped away: the end-marker match is unanchored, so a stray mention of the
# marker string inside the region would cut the slice short silently — the
# marker counts are asserted and the region's last function is grepped for;
# and tags match as substrings, which stays safe here because there is exactly
# one region with one tag.
#
# What this DOES NOT cover: the HTTP handlers, the O_APPEND write path, and
# cursor persistence to disk. Those need the socket loop and a real
# INSTALL_DIR; they are thin wrappers over the functions covered here.
#
# Usage: tools/test_drop.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
drop="$here/../skills/drop.c"
seed="$here/../seed.c"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

[ -f "$drop" ] || { echo "cannot find $drop"; exit 1; }
[ -f "$seed" ] || { echo "cannot find $seed"; exit 1; }

# Exactly one marker pair, or the slice below is not what it claims to be.
[ "$(grep -c 'host-test:begin drop' "$drop")" -eq 1 ] \
    || { echo "expected exactly one begin marker in $drop"; exit 1; }
[ "$(grep -c 'host-test:end' "$drop")" -eq 1 ] \
    || { echo "expected exactly one end marker in $drop"; exit 1; }

slice() {
    awk -v tag="$2" '
        $0 ~ ("host-test:begin " tag) { grab = 1; next }
        grab && /host-test:end/       { grab = 0; next }
        grab                          { print }
    ' "$1"
}

# json_escape() sliced out of seed.c by name: first line of the function to
# the first line that is a lone closing brace.
json_escape_src="$(awk '
    /^static int json_escape\(/ { inf = 1 }
    inf                         { print }
    inf && /^}/                 { exit }
' "$seed")"
[ -n "$json_escape_src" ] || { echo "cannot find json_escape() in $seed"; exit 1; }

drop_src="$(slice "$drop" drop)"
[ -n "$drop_src" ] || { echo "empty slice from $drop"; exit 1; }
# drop_load_file() is the last function in the region; its absence means the
# region was cut short by something matching the end marker early.
printf '%s\n' "$drop_src" | grep -q 'static int drop_load_file' \
    || { echo "slice from $drop is cut short — check the markers"; exit 1; }

{
cat <<'PRELUDE'
/* Generated by tools/test_drop.sh — do not edit. */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <limits.h>
#include <stdarg.h>
#include <unistd.h>
#include <fcntl.h>

PRELUDE
printf '%s\n\n' "$json_escape_src"
printf '%s\n' "$drop_src"
cat <<'MAIN'

/* ---- test scaffolding ---- */

static int failures = 0;
static int checks = 0;

static void check(int cond, const char *what) {
    checks++;
    if (!cond) { printf("  FAIL: %s\n", what); failures++; }
    else       { printf("  ok:   %s\n", what); }
}

static void check_str(const char *got, const char *want, const char *what) {
    checks++;
    if (strcmp(got, want) != 0) {
        printf("  FAIL: %s — got \"%s\", wanted \"%s\"\n", what, got, want);
        failures++;
    } else {
        printf("  ok:   %s\n", what);
    }
}

/* The store as drop_init() finds it on a fresh node. */
static void drop_reset(void) {
    memset(g_drop_ring, 0, sizeof(g_drop_ring));
    g_drop_head = 0;
    g_drop_count = 0;
    g_drop_next_id = 1;
    memset(g_drop_cursors, 0, sizeof(g_drop_cursors));
    g_drop_cursor_count = 0;
}

/* Post a message the way the endpoint does, minus HTTP and the file. */
static int post(const char *from, const char *to, int reply_to,
                const char *link, const char *text) {
    drop_msg_t *m = drop_ring_add();
    m->id = g_drop_next_id++;
    m->ts = 49500; /* 13:45 UTC */
    m->reply_to = reply_to;
    drop_str_copy(m->from, sizeof(m->from), from);
    drop_str_copy(m->to, sizeof(m->to), to);
    drop_str_copy(m->link, sizeof(m->link), link ? link : "");
    drop_str_copy(m->text, sizeof(m->text), text);
    drop_scrub(m->text);
    drop_scrub(m->link);
    return m->id;
}

/* An inbox fetch as the handler runs it: list, then commit with a flag
 * saying whether the response reached the client. */
static int fetch_inbox(const char *handle, int peek, int delivered,
                       char *buf, int cap, int *out_count) {
    int cur = drop_cursor_get(handle);
    int count = 0, maxid = 0;
    drop_list_json(buf, cap, cur, handle, &count, &maxid);
    if (out_count) *out_count = count;
    return drop_inbox_commit(handle, peek, maxid, delivered);
}

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: test <workdir>\n"); return 2; }

    printf("handle validation\n");
    {
        check(drop_handle_ok("a"), "a single letter");
        check(drop_handle_ok("session-A_9"), "letters, digits, dash, underscore");
        check(drop_handle_ok("all"), "the broadcast handle");
        check(drop_handle_ok("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"),
              "32 chars, the maximum");
        check(!drop_handle_ok(""), "empty is refused");
        check(!drop_handle_ok("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"),
              "33 chars is refused");
        check(!drop_handle_ok("a b"), "a space is refused");
        check(!drop_handle_ok("a.b"), "a dot is refused");
        check(!drop_handle_ok("a/b"), "a slash is refused");
        check(!drop_handle_ok("a&b"), "an ampersand is refused");
        check(!drop_handle_ok("a\nb"), "a newline is refused");
        check(!drop_handle_ok("caf\xc3\xa9"), "non-ASCII bytes are refused");
    }

    printf("control bytes in text become spaces\n");
    {
        char t1[] = "a\x01" "b\nc\x7f" "d";
        drop_scrub(t1);
        check_str(t1, "a b c d", "0x01, newline and DEL");
        char t2[] = "tab\there\r\n";
        drop_scrub(t2);
        check_str(t2, "tab here  ", "tab, CR, LF");
        char t3[] = "caf\xc3\xa9 ok";
        drop_scrub(t3);
        check_str(t3, "caf\xc3\xa9 ok", "UTF-8 above 0x7F is left alone");
    }

    printf("JSON escaping\n");
    {
        char out[128];
        json_escape("say \"hi\" \\ done", out, sizeof(out));
        check_str(out, "say \\\"hi\\\" \\\\ done", "quote and backslash");
        json_escape("a\x01" "b", out, sizeof(out));
        check_str(out, "a\\u0001b", "a control byte becomes \\u00XX");
        json_escape("a\nb", out, sizeof(out));
        check_str(out, "a\\nb", "newline becomes \\n");
    }

    printf("UTF-8 trim after a byte-cap cut\n");
    {
        char t1[] = "aaaa\xc3";
        drop_utf8_trim(t1);
        check_str(t1, "aaaa", "a torn two-byte sequence is dropped whole");
        char t2[] = "caf\xc3\xa9";
        drop_utf8_trim(t2);
        check_str(t2, "caf\xc3\xa9", "a complete two-byte sequence is kept");
        char t3[] = "a\xf0\x9f\x98";
        drop_utf8_trim(t3);
        check_str(t3, "a", "a torn four-byte sequence is dropped whole");
        char t4[] = "a\xf0\x9f\x98\x80";
        drop_utf8_trim(t4);
        check_str(t4, "a\xf0\x9f\x98\x80", "a complete four-byte sequence is kept");
        char t5[] = "abc";
        drop_utf8_trim(t5);
        check_str(t5, "abc", "pure ASCII is left alone");
        char t6[] = "\x9f\x98";
        drop_utf8_trim(t6);
        check_str(t6, "", "nothing but continuation bytes empties out");
    }

    printf("parsed longs are clamped into id range\n");
    {
        check(drop_clamp_id(0) == 0, "zero stays zero");
        check(drop_clamp_id(42) == 42, "an ordinary id passes through");
        check(drop_clamp_id(-1) == 0, "negative clamps to 0");
        check(drop_clamp_id(4294967296L) == INT_MAX,
              "a value past INT_MAX clamps instead of wrapping");
    }

    printf("string extraction refuses non-string values\n");
    {
        char out[64];
        check(drop_json_str("{\"from\":123,\"to\":\"bob\"}", "from",
                            out, sizeof(out)) < 0,
              "a numeric value is refused, not drifted to the next token");
        check(out[0] == '\0', "and nothing is extracted");
        check(drop_json_str("{\"from\": \"alice\"}", "from",
                            out, sizeof(out)) == 5,
              "whitespace after the colon is still accepted");
        check_str(out, "alice", "with the right value");
        check(drop_json_str("{\"from\":null}", "from", out, sizeof(out)) < 0,
              "null is refused");
        drop_msg_t m;
        check(!drop_parse_line(
                  "{\"id\":1,\"ts\":1,\"from\":123,\"to\":\"bob\","
                  "\"reply_to\":0,\"link\":\"\",\"text\":\"x\"}", &m),
              "a stored line with a numeric from is refused whole");
    }

    printf("ring eviction at 256\n");
    {
        drop_reset();
        char text[32];
        for (int i = 0; i < 300; i++) {
            snprintf(text, sizeof(text), "msg %d", i + 1);
            post("alice", "all", 0, NULL, text);
        }
        check(g_drop_count == DROP_RING, "the ring holds exactly 256");
        check(drop_ring_at(0)->id == 45, "the oldest survivor is id 45");
        check(drop_ring_at(DROP_RING - 1)->id == 300, "the newest is id 300");
        check(g_drop_next_id == 301, "and the next id is 301");
    }

    printf("the since filter\n");
    {
        int count = 0, maxid = 0;
        int cap = DROP_RING * DROP_MSG_JSON_MAX + 64;
        char *buf = malloc(cap);
        check(buf != NULL, "list buffer allocates");
        drop_list_json(buf, cap, 298, NULL, &count, &maxid);
        check(count == 2, "since=298 returns two messages");
        check(maxid == 300, "up to id 300");
        check(strstr(buf, "\"id\":299,") != NULL, "and 299 is one of them");
        drop_list_json(buf, cap, 300, NULL, &count, &maxid);
        check(count == 0, "since=300 returns none");
        check_str(buf, "[]", "as an empty array");
        drop_list_json(buf, cap, 0, NULL, &count, &maxid);
        check(count == DROP_RING, "since=0 returns the whole ring");
        free(buf);
    }

    printf("inbox: cursor advance vs peek\n");
    {
        drop_reset();
        post("alice", "bob", 0, NULL, "one");        /* id 1 */
        post("alice", "bob", 0, NULL, "two");        /* id 2 */
        post("carol", "all", 0, NULL, "broadcast");  /* id 3 */
        post("alice", "carol", 0, NULL, "not bobs"); /* id 4 */

        int cap = DROP_RING * DROP_MSG_JSON_MAX + 64;
        char *buf = malloc(cap);
        check(buf != NULL, "inbox buffer allocates");
        int count = 0;

        int cur = fetch_inbox("bob", 1, 1, buf, cap, &count);
        check(count == 3, "peek sees two direct messages plus the broadcast");
        check(cur == 0, "and leaves the cursor at 0");
        check(strstr(buf, "not bobs") == NULL, "another handle's mail is not in it");

        cur = fetch_inbox("bob", 1, 1, buf, cap, &count);
        check(count == 3, "a second peek sees the same three");

        /* The Critical case: the response never reached the client. */
        cur = fetch_inbox("bob", 0, 0, buf, cap, &count);
        check(count == 3, "a fetch whose write failed still built the mail");
        check(cur == 0, "but the cursor did NOT advance");

        cur = fetch_inbox("bob", 0, 1, buf, cap, &count);
        check(count == 3, "so the next fetch redelivers all of it");
        check(cur == 3, "and only then advances the cursor");

        cur = fetch_inbox("bob", 0, 1, buf, cap, &count);
        check(count == 0, "a fetch after that delivers nothing");
        check(cur == 3, "and the cursor stays put");

        post("carol", "bob", 2, NULL, "reply");      /* id 5 */
        cur = fetch_inbox("bob", 0, 1, buf, cap, &count);
        check(count == 1, "a new message is delivered once");
        check(cur == 5, "and the cursor follows it");
        check(strstr(buf, "\"reply_to\":2") != NULL, "carrying its reply_to");

        cur = fetch_inbox("carol", 0, 1, buf, cap, &count);
        check(count == 1, "carol gets her direct message only");
        check(strstr(buf, "broadcast") == NULL,
              "her own to:all broadcast is not echoed back to her");
        free(buf);
    }

    printf("board.md rendering\n");
    {
        drop_reset();
        post("alice", "bob", 0, NULL, "first line");
        post("bob", "all", 1, "TICKET/7", "second line");
        drop_cursor_set("bob", 1);
        drop_cursor_set("carol", 0);
        static char board[3 * DROP_BOARD_LINE_MAX];  /* room for two lines + guard */
        int o = drop_board_render(board, sizeof(board));
        check(o > 0 && o < (int)sizeof(board), "renders within the buffer");
        check(strstr(board, "2 message(s)") != NULL, "with a count in the header");
        check(strstr(board,
              "- **alice→bob** (#1, 13:45 UTC) — first line") != NULL,
              "a plain message line");
        check(strstr(board,
              "- **bob→all** (#2 re #1, 13:45 UTC) — second line — TICKET/7") != NULL,
              "a reply with a link");
        check(strstr(board, "## Cursors") != NULL, "and a cursors footer");
        /* id 2 is bob's own broadcast, so it is not unread FOR bob */
        check(strstr(board, "- bob @ 1 (0 unread)") != NULL,
              "bob: own broadcast does not count as unread");
        /* carol never read anything; the broadcast is hers to read */
        check(strstr(board, "- carol @ 0 (1 unread)") != NULL,
              "carol: one unread broadcast");
    }

    printf("board.md truncation guard\n");
    {
        drop_reset();
        char big[DROP_TEXT_LEN + 1];
        memset(big, 'x', DROP_TEXT_LEN);
        big[DROP_TEXT_LEN] = '\0';
        char link[DROP_LINK_LEN + 1];
        memset(link, 'y', DROP_LINK_LEN);
        link[DROP_LINK_LEN] = '\0';
        for (int i = 0; i < DROP_RING; i++)
            post("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 999999999, link, big);

        int cap = 32768; /* RESP_BUF-sized, far too small for 256 such lines */
        char *buf = malloc(cap + 64);
        check(buf != NULL, "board buffer allocates");
        memset(buf + cap, 0xAA, 64); /* canary past the buffer */
        int o = drop_board_render(buf, cap);
        check(o > 0 && o < cap, "the offset stays inside the buffer");
        check(buf[o] == '\0', "and the output is terminated there");
        int intact = 1;
        for (int i = 0; i < 64; i++)
            if ((unsigned char)buf[cap + i] != 0xAA) intact = 0;
        check(intact, "nothing was written past the buffer");
        check(strstr(buf, "(truncated)") != NULL, "and the cut is announced");
        free(buf);
    }

    printf("JSONL format, parse and reload\n");
    {
        drop_reset();
        char path[1024];
        snprintf(path, sizeof(path), "%s/drop.jsonl", argv[1]);

        FILE *fp = fopen(path, "w");
        check(fp != NULL, "the store file opens for writing");

        drop_msg_t m;
        char line[DROP_LINE_MAX];
        memset(&m, 0, sizeof(m));
        m.id = 1; m.ts = 100;
        drop_str_copy(m.from, sizeof(m.from), "alice");
        drop_str_copy(m.to, sizeof(m.to), "bob");
        drop_str_copy(m.text, sizeof(m.text), "plain text");
        int n = drop_msg_format_jsonl(&m, line, sizeof(line));
        fwrite(line, 1, n, fp);

        memset(&m, 0, sizeof(m));
        m.id = 7; m.ts = 200; m.reply_to = 1;
        drop_str_copy(m.from, sizeof(m.from), "bob");
        drop_str_copy(m.to, sizeof(m.to), "all");
        drop_str_copy(m.link, sizeof(m.link), "PR/12");
        drop_str_copy(m.text, sizeof(m.text), "quote \" and backslash \\ here");
        n = drop_msg_format_jsonl(&m, line, sizeof(line));
        fwrite(line, 1, n, fp);

        fputs("this line is not a message\n", fp);
        fputs("{\"id\":0,\"text\":\"id zero is refused\"}\n", fp);
        /* A torn line, as a mid-write crash leaves it: id parses, the rest
         * is gone. Must not load as a ghost with empty to/text. */
        fputs("{\"id\":9,\"ts\":300,\"from\":\"al\n", fp);
        /* A foreign-edited line with an escaped quote in the handle. from/to
         * are rendered unescaped by drop_msg_json, so letting this in would
         * break every API response until the file is hand-cleaned. */
        fputs("{\"id\":10,\"ts\":300,\"from\":\"evil\\\"x\",\"to\":\"bob\","
              "\"reply_to\":0,\"link\":\"\",\"text\":\"hi\"}\n", fp);
        /* An id-only ghost. */
        fputs("{\"id\":11}\n", fp);
        /* Ids at and past the int ceiling: next_id = id + 1 must not
         * overflow, so these are refused outright. */
        fputs("{\"id\":2147483647,\"ts\":300,\"from\":\"mallory\",\"to\":\"bob\","
              "\"reply_to\":0,\"link\":\"\",\"text\":\"int max\"}\n", fp);
        fputs("{\"id\":9999999999,\"ts\":300,\"from\":\"mallory\",\"to\":\"bob\","
              "\"reply_to\":0,\"link\":\"\",\"text\":\"past long int\"}\n", fp);
        /* A foreign newline smuggled through JSON escaping: loads (handles
         * and text are valid) but the newline must be scrubbed, or board.md
         * grows fake lines. */
        fputs("{\"id\":12,\"ts\":300,\"from\":\"mallory\",\"to\":\"bob\","
              "\"reply_to\":0,\"link\":\"\",\"text\":\"line1\\nline2\"}\n", fp);
        fclose(fp);

        drop_reset();
        int loaded = drop_load_file(path);
        check(loaded == 3, "three of ten lines load");
        check(g_drop_count == 3, "into three ring slots");
        check(g_drop_next_id == 13, "and the next id clears the highest loaded");
        check(drop_ring_at(0)->id == 1, "the first message keeps its id");
        check(drop_ring_at(0)->ts == 100, "and its timestamp");
        check_str(drop_ring_at(0)->text, "plain text", "and its text");
        const drop_msg_t *r = drop_ring_at(1);
        check(r->id == 7 && r->reply_to == 1 && r->ts == 200,
              "the second keeps id, reply_to and ts");
        check_str(r->text, "quote \" and backslash \\ here",
                  "text round-trips through escaping");
        check_str(r->link, "PR/12", "and so does the link");
        check_str(r->from, "bob", "and the sender");
        check_str(drop_ring_at(2)->text, "line1 line2",
                  "a smuggled newline is scrubbed to a space on load");

        /* And the API output built from this file is still valid JSON:
         * no ghost entries, no quote injection, no raw newlines. */
        int cap = DROP_RING * DROP_MSG_JSON_MAX + 64;
        char *buf = malloc(cap);
        check(buf != NULL, "render buffer allocates");
        drop_list_json(buf, cap, 0, NULL, NULL, NULL);
        check(strstr(buf, "evil") == NULL, "the quoted-handle line never renders");
        check(strchr(buf, '\n') == NULL, "no raw newline in the rendered JSON");
        int quotes = 0;
        for (int i = 0; buf[i]; i++) {
            if (buf[i] == '\\' && buf[i + 1]) { i++; continue; }
            if (buf[i] == '"') quotes++;
        }
        check(quotes % 2 == 0, "every rendered quote is paired");
        free(buf);
    }

    printf("a max-size message survives the JSONL round trip\n");
    {
        /* Pins DROP_LINE_MAX to the derived message size: a hand-sized
         * line buffer would silently truncate full-size text on reload. */
        drop_reset();
        drop_msg_t m, r;
        static char line[DROP_LINE_MAX];
        memset(&m, 0, sizeof(m));
        m.id = 1;
        m.ts = 100;
        drop_str_copy(m.from, sizeof(m.from), "alice");
        drop_str_copy(m.to, sizeof(m.to), "bob");
        memset(m.text, 'x', DROP_TEXT_LEN);
        m.text[DROP_TEXT_LEN] = '\0';
        memset(m.link, 'y', DROP_LINK_LEN);
        m.link[DROP_LINK_LEN] = '\0';
        int n = drop_msg_format_jsonl(&m, line, sizeof(line));
        check(n < (int)sizeof(line) - 1, "the line buffer holds a max-size message");
        check(line[n - 1] == '\n', "with its newline intact");
        check(drop_parse_line(line, &r), "and it parses back");
        check((int)strlen(r.text) == DROP_TEXT_LEN, "with every text byte");
        check((int)strlen(r.link) == DROP_LINK_LEN, "and every link byte");
    }

    printf("torn append is sealed, never merged\n");
    {
        drop_reset();
        char path[1024];
        snprintf(path, sizeof(path), "%s/drop-torn.jsonl", argv[1]);

        /* One good line, then a fragment with NO trailing newline — exactly
         * what a crash mid-append leaves behind. */
        drop_msg_t m;
        char line[DROP_LINE_MAX];
        memset(&m, 0, sizeof(m));
        m.id = 1; m.ts = 100;
        drop_str_copy(m.from, sizeof(m.from), "alice");
        drop_str_copy(m.to, sizeof(m.to), "bob");
        drop_str_copy(m.text, sizeof(m.text), "before the crash");
        int n = drop_msg_format_jsonl(&m, line, sizeof(line));
        FILE *fp = fopen(path, "w");
        fwrite(line, 1, n, fp);
        fputs("{\"id\":2,\"ts\":200,\"from\":\"al", fp);  /* torn, no \n */
        fclose(fp);

        /* What drop_init does, then what the next POST does. */
        drop_seal_file(path);
        memset(&m, 0, sizeof(m));
        m.id = 3; m.ts = 300;
        drop_str_copy(m.from, sizeof(m.from), "carol");
        drop_str_copy(m.to, sizeof(m.to), "bob");
        drop_str_copy(m.text, sizeof(m.text), "after the crash");
        n = drop_msg_format_jsonl(&m, line, sizeof(line));
        fp = fopen(path, "a");
        fwrite(line, 1, n, fp);
        fclose(fp);

        drop_reset();
        int loaded = drop_load_file(path);
        check(loaded == 2, "both good messages load");
        check_str(drop_ring_at(0)->text, "before the crash", "the one before the tear");
        check_str(drop_ring_at(1)->text, "after the crash", "and the one appended after it");
        check(drop_ring_at(1)->id == 3, "under its own id — never merged with the fragment");
        check(g_drop_next_id == 4, "and the id counter is sane");

        /* Sealing an already-clean file must change nothing. */
        drop_seal_file(path);
        drop_reset();
        check(drop_load_file(path) == 2, "sealing a clean store is a no-op");
    }

    printf("stale cursors are clamped to the loaded range\n");
    {
        drop_reset();
        post("alice", "bob", 0, NULL, "one");
        post("alice", "bob", 0, NULL, "two");
        post("alice", "bob", 0, NULL, "three");
        /* A cursors file from a longer history: bob supposedly read #300. */
        drop_cursor_set("bob", 300);
        drop_cursors_clamp();
        check(drop_cursor_get("bob") == 3, "cursor 300 clamps to next_id - 1");

        int cap = DROP_RING * DROP_MSG_JSON_MAX + 64;
        char *buf = malloc(cap);
        check(buf != NULL, "clamp test buffer allocates");
        int count = 0;
        post("alice", "bob", 0, NULL, "four");       /* id 4, new mail */
        int cur = fetch_inbox("bob", 0, 1, buf, cap, &count);
        check(count == 1, "new mail is delivered instead of being swallowed");
        check(cur == 4, "and the cursor follows it");
        free(buf);
    }

    printf("\n%d checks, %d failed — %s\n", checks, failures,
           failures ? "FAILED" : "all passed");
    return failures ? 1 : 0;
}
MAIN
} > "$work/test.c"

cc="${CC:-cc}"
"$cc" -std=c11 -O2 -Wall -Wextra -o "$work/test" "$work/test.c"
"$work/test" "$work"
